/**
 * Fichas regionales de Sudamérica.
 *
 * ARCHIVO GENERADO desde _research/ecosistemas-saberes-sudamerica/
 * fase-1-ecologia/fichas-ecologicas-nuevas.json. No editar a mano: se regenera
 * desde el paquete de investigación, que es donde vive la trazabilidad (fuentes,
 * ECO_ID verificados por consulta espacial y nivel de confianza por ficha).
 *
 * Antes de este montaje, adentro de Sudamérica mandaban 12 fichas escritas para
 * la Argentina y una heurística Köppen: la Caatinga, el Chaco húmedo, el
 * Pantanal, los páramos, el Chocó y los valles secos interandinos caían al bioma
 * global o —peor— a la ficha argentina más parecida. Estas 47 fichas son las
 * dueñas propias de ese territorio.
 *
 * `saberes` va vacío a propósito en todas, igual que en los otros dos bloques
 * generados. Los saberes sudamericanos son subnacionales y necesitan geometría
 * propia con procedencia y licencia; viven en la fase 2 del paquete y se montan
 * aparte, en `lib/saberes.ts`.
 */

import type { BiomaFicha } from './biomaTipos';

export const BIOMAS_REGIONALES_SUDAMERICA: Record<string, BiomaFicha> = {
  // BR, CO, EC, PE · confianza alta
  amazonia_noroccidental_tierra_firme: {
    id: 'amazonia_noroccidental_tierra_firme',
    nombre: 'Amazonía noroccidental de tierra firme',
    emoji: '🌳',
    color: '#0B6B3A',
    resumen: 'Selvas siempreverdes de tierra firme del piedemonte y las cuencas de Caquetá, Napo, Japurá y Solimões, sin inundación fluvial anual generalizada.',
    vegetacion: 'Dosel alto y multiestrato con palmeras, leguminosas, lianas y epífitas; mosaicos de colinas, terrazas y bosques de piedemonte.',
    fauna: 'Jaguar, danta amazónica, monos lanudos, águila harpía, guacamayos y una diversidad excepcional de anfibios y peces de cabeceras.',
    suelos: 'Predominan ultisoles y oxisoles ácidos y pobres; terrazas jóvenes y piedemontes pueden ser más fértiles. La biomasa y la hojarasca concentran nutrientes.',
    saberes: [],
    especies: [
      'Ceiba',
      'Ungurahua',
      'Castaña amazónica',
      'Cedro',
      'Palmas de dosel',
    ],
    cultivos: ['yuca', 'platano', 'cacao', 'maracuya', 'maiz_tropical', 'inga', 'crotalaria'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'Science Panel for the Amazon — Assessment Report 2021', url: 'https://www.sp-amazon.org/publications/' },
    ],
  },
  // BR · confianza alta
  amazonia_oriental_tierra_firme: {
    id: 'amazonia_oriental_tierra_firme',
    nombre: 'Amazonía oriental y meridional de tierra firme',
    emoji: '🌴',
    color: '#2B7338',
    resumen: 'Selvas de tierra firme entre Madeira, Tapajós, Xingu, Tocantins y Pindaré, con una estación seca creciente hacia el arco sur y oriental.',
    vegetacion: 'Bosques altos siempreverdes a estacionales, lianas y palmeras; enclaves abiertos y transiciones hacia cerrado y bosques secos.',
    fauna: 'Jaguar, tapir, monos araña y capuchinos, águila harpía, guacamayos y tortugas terrestres.',
    suelos: 'Latosoles y argisoles antiguos, ácidos y pobres; el déficit estacional incrementa vulnerabilidad a incendios antrópicos.',
    saberes: [],
    especies: [
      'Castaña amazónica',
      'Ipê',
      'Angelim',
      'Babaçu',
      'Copaíba',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'Science Panel for the Amazon — Assessment Report 2021', url: 'https://www.sp-amazon.org/publications/' },
    ],
  },
  // BO, BR, PE · confianza alta
  amazonia_suroccidental_tierra_firme: {
    id: 'amazonia_suroccidental_tierra_firme',
    nombre: 'Amazonía suroccidental de tierra firme',
    emoji: '🌴',
    color: '#176F3B',
    resumen: 'Selvas de tierra firme del arco suroccidental amazónico, con fuerte gradiente de estacionalidad y grandes ríos pero extensas superficies no inundables.',
    vegetacion: 'Bosques altos con palmeras, bambusales de Guadua en sectores occidentales y transiciones a bosques estacionales hacia el sur.',
    fauna: 'Jaguar, pecarí labiado, lobo de río, monos, guacamayos y águila harpía.',
    suelos: 'Suelos meteorizados y ácidos, con parches jóvenes de origen andino; la compactación y la erosión aumentan tras desmontes y caminos.',
    saberes: [],
    especies: [
      'Castaña amazónica',
      'Shihuahuaco',
      'Bambú Guadua',
      'Caoba',
      'Aguaje',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'Science Panel for the Amazon — Assessment Report 2021', url: 'https://www.sp-amazon.org/publications/' },
    ],
  },
  // EC · confianza alta
  bosque_humedo_occidente_ecuador: {
    id: 'bosque_humedo_occidente_ecuador',
    nombre: 'Bosques húmedos del occidente ecuatoriano',
    emoji: '🌴',
    color: '#1F7A4D',
    resumen: 'Bosques tropicales húmedos y subhúmedos al oeste de los Andes ecuatorianos, con alta diversidad y transición hacia Chocó y bosques secos tumbesinos.',
    vegetacion: 'Dosel alto con palmeras, ceibas, lauráceas, lianas y epífitas; bosques semideciduos en el extremo más estacional.',
    fauna: 'Mono araña de cabeza café, jaguar, tucanes, anfibios y aves endémicas del Chocó-Tumbes.',
    suelos: 'Suelos arcillosos y muy meteorizados en colinas; aluviales en llanuras. Las lluvias intensas y pendientes elevan riesgo de erosión.',
    saberes: [],
    especies: [
      'Tagua',
      'Balsa',
      'Ceibo',
      'Guayacán',
      'Palma real',
    ],
    cultivos: ['cacao', 'platano', 'yuca', 'maracuya', 'vainilla', 'inga', 'nogal_cafetero', 'pasto_elefante'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'MAATE Ecuador — Socio Bosque', url: 'https://sociobosque.ambiente.gob.ec/?q=node%2F44' },
    ],
  },
  // CL · confianza alta
  bosque_juan_fernandez: {
    id: 'bosque_juan_fernandez',
    nombre: 'Bosques templados de Juan Fernández',
    emoji: '🏝️',
    color: '#326F55',
    resumen: 'Bosques insulares templados oceánicos de origen volcánico, extraordinariamente endémicos y vulnerables a invasoras y erosión.',
    vegetacion: 'Bosques siempreverdes, matorrales y helechales con numerosas plantas exclusivas del archipiélago.',
    fauna: 'Picaflor de Juan Fernández, cachudito de Juan Fernández, fardelas y lobo fino de Juan Fernández.',
    suelos: 'Suelos volcánicos en pendientes abruptas, húmedos pero muy erosionables cuando invasoras, incendios o herbívoros eliminan cobertura.',
    saberes: [],
    especies: [
      'Luma de Juan Fernández',
      'Chonta de Juan Fernández',
      'Cuminia',
      'Juan bueno',
      'Pangue insular',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'CONAF — Archipiélago Juan Fernández', url: 'https://www.conaf.cl/parque_nacionales/parque-nacional-archipielago-juan-fernandez/' },
      { label: 'MMA Chile — Nazca-Desventuradas', url: 'https://gestioncba.mma.gob.cl/SolicitudAP/Details/34' },
    ],
  },
  // BO, BR · confianza alta
  bosque_seco_chiquitano: {
    id: 'bosque_seco_chiquitano',
    nombre: 'Bosque seco chiquitano',
    emoji: '🌳',
    color: '#7A7134',
    resumen: 'Gran bosque estacional de transición entre Amazonía, Cerrado y Chaco, con estación seca marcada y un dosel todavía continuo.',
    vegetacion: 'Bosques semideciduos con tajibo, cuchi, curupaú y soto; afloramientos rocosos y sabanas intercaladas.',
    fauna: 'Jaguar, tapir, pecarí, armadillo gigante, pavas y guacamayos.',
    suelos: 'Suelos antiguos y variables, desde rojos profundos hasta someros sobre roca; el fuego repetido simplifica el bosque.',
    saberes: [],
    especies: [
      'Tajibo',
      'Cuchi',
      'Curupaú',
      'Soto',
      'Cuta',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'MMA Brasil — biomas y transiciones', url: 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade' },
    ],
  },
  // BR · confianza alta
  bosque_seco_mato_grosso: {
    id: 'bosque_seco_mato_grosso',
    nombre: 'Bosques estacionales del Mato Grosso',
    emoji: '🍂',
    color: '#6F7430',
    resumen: 'Bosques tropicales estacionales del sur amazónico, en la transición con Cerrado, sometidos a una estación seca creciente.',
    vegetacion: 'Bosque semideciduo alto con lianas, palmeras y especies amazónicas mezcladas con elementos del Cerrado.',
    fauna: 'Jaguar, tapir, pecarí, monos y aves forestales del arco sur amazónico.',
    suelos: 'Latosoles y argisoles ácidos; la sequía estacional vuelve al bosque especialmente vulnerable a incendios de borde.',
    saberes: [],
    especies: [
      'Copaíba',
      'Ipê',
      'Jatobá',
      'Castanha-do-pará',
      'Babaçu',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'IBGE — Vegetação do Brasil', url: 'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR' },
      { label: 'MMA Brasil — biodiversidade y biomas', url: 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade' },
    ],
  },
  // BR · confianza alta
  bosques_babacu_maranhao: {
    id: 'bosques_babacu_maranhao',
    nombre: 'Bosques de babaçu de Maranhão',
    emoji: '🌴',
    color: '#6F8535',
    resumen: 'Mosaico de bosque estacional y palmares de babaçu en la transición entre Amazonía, Cerrado y Caatinga.',
    vegetacion: 'Palmares densos de babaçu, bosques secundarios, capoeiras y remanentes semideciduos; la palma coloniza claros y áreas perturbadas.',
    fauna: 'Monos, armadillos, pecaríes, aves frugívoras y polinizadores de mosaicos forestales.',
    suelos: 'Suelos generalmente ácidos y meteorizados, con fertilidad variable; la cobertura de palmar protege pero no sustituye la diversidad del bosque maduro.',
    saberes: [],
    especies: [
      'Babaçu',
      'Jatobá',
      'Ipê',
      'Bacuri',
      'Burití',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'IBGE — Vegetação do Brasil', url: 'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR' },
      { label: 'MMA Brasil — biodiversidade y biomas', url: 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade' },
    ],
  },
  // CO, VE · confianza alta
  bosques_humedos_caribe_colombia_venezuela: {
    id: 'bosques_humedos_caribe_colombia_venezuela',
    nombre: 'Bosques húmedos del Caribe colombiano y Catatumbo',
    emoji: '🌧️',
    color: '#287B49',
    resumen: 'Bosques húmedos de tierras bajas y piedemontes del Catatumbo, Magdalena y Urabá, entre Andes y Caribe.',
    vegetacion: 'Bosques altos con palmeras, ceibas, leguminosas, lianas y humedales ribereños; transiciones rápidas hacia bosque seco.',
    fauna: 'Jaguar, tapir, mono araña, paujiles, tucanes y anfibios tropicales.',
    suelos: 'Aluviales jóvenes en valles y suelos meteorizados en colinas; drenaje y fertilidad varían mucho con terraza y río.',
    saberes: [],
    especies: [
      'Ceiba',
      'Cativo',
      'Caracolí',
      'Palma milpesos',
      'Cedro',
    ],
    cultivos: ['cacao', 'platano', 'yuca', 'maiz_tropical', 'cana_azucar', 'guandul', 'gliricidia', 'nogal_cafetero'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'PNN Colombia — sistema de áreas y ecosistemas', url: 'https://www.parquesnacionales.gov.co/' },
    ],
  },
  // CO, EC, VE · confianza alta
  bosques_montanos_andes_norte: {
    id: 'bosques_montanos_andes_norte',
    nombre: 'Bosques montanos de los Andes del norte',
    emoji: '🌫️',
    color: '#2C7250',
    resumen: 'Bosques nublados y montanos de las cordilleras septentrionales, fragmentados naturalmente por valles y con enorme recambio de especies con la altura.',
    vegetacion: 'Lauráceas, encenillos, palmas de cera, podocarpáceas, helechos arborescentes, bambúes y abundantes epífitas.',
    fauna: 'Oso andino, danta de montaña, puma, gallito de roca, tucanes andinos y numerosos anfibios endémicos.',
    suelos: 'Andisoles e inceptisoles húmedos, ricos en materia orgánica pero inestables en pendientes; la niebla aporta agua adicional.',
    saberes: [],
    especies: [
      'Palma de cera',
      'Encenillo',
      'Podocarpus',
      'Aliso andino',
      'Quina',
    ],
    cultivos: ['cafe', 'lulo', 'mora_andina', 'tomate_arbol', 'arracacha', 'aguacate', 'platano_sombra', 'inga', 'nogal_cafetero'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'MINAM Perú — Mapa Nacional de Ecosistemas', url: 'https://sinia.minam.gob.pe/documentos/mapa-nacional-ecosistemas-peru' },
      { label: 'PNN Colombia — bosque andino y páramo', url: 'https://www.parquesnacionales.gov.co/nuestros-parques/sff-guanenta-alto-rio-fonce/' },
    ],
  },
  // CO, VE · confianza alta
  bosques_secos_caribe_colombia_venezuela: {
    id: 'bosques_secos_caribe_colombia_venezuela',
    nombre: 'Bosques secos del Caribe suramericano y Orinoquía occidental',
    emoji: '🌵',
    color: '#9A7440',
    resumen: 'Bosques tropicales deciduos y matorrales estacionales de llanuras interiores y cuencas caribeñas, con sequía anual marcada.',
    vegetacion: 'Bosque bajo a mediano que pierde hojas, cardonales, espinares, palmares y bosques ribereños persistentes.',
    fauna: 'Venado cola blanca, pecarí, ocelote, iguanas, guacamayas y aves de bosque seco.',
    suelos: 'Suelos desde aluviales relativamente fértiles hasta arcillosos y salinos; alta erosión al retirar cobertura durante la estación seca.',
    saberes: [],
    especies: [
      'Dividivi',
      'Caracolí',
      'Ceiba',
      'Cují',
      'Guayacán',
    ],
    cultivos: ['sorgo', 'mijo', 'maiz_tropical', 'chile_seco', 'guandul', 'gliricidia', 'nopal', 'vetiver'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'MinAmbiente Colombia — Bosque Seco Tropical', url: 'https://www.minambiente.gov.co/direccion-de-bosques-biodiversidad-y-servicios-ecosistemicos/bosque-seco-tropical/' },
    ],
  },
  // EC, PE · confianza alta
  bosques_secos_tumbes_ecuador_peru: {
    id: 'bosques_secos_tumbes_ecuador_peru',
    nombre: 'Bosques secos de Tumbes, Piura y Ecuador',
    emoji: '🌳',
    color: '#A57A3D',
    resumen: 'Bosques deciduos del Pacífico ecuatorial sometidos a una estación seca prolongada y lluvias muy variables asociadas a El Niño.',
    vegetacion: 'Ceibales, algarrobales, guayacanes y matorral espinoso; el dosel reverdece rápidamente con las lluvias.',
    fauna: 'Zorro de Sechura, venado cola blanca, mono aullador de la costa, perico macareño y aves endémicas tumbesinas.',
    suelos: 'Suelos secos y a menudo pedregosos o arcillosos; abanicos y valles aluviales son más profundos, pero susceptibles a erosión torrencial.',
    saberes: [],
    especies: [
      'Ceibo',
      'Algarrobo peruano',
      'Guayacán',
      'Palo santo',
      'Hualtaco',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'MINAM Perú — Mapa Nacional de Ecosistemas', url: 'https://sinia.minam.gob.pe/documentos/mapa-nacional-ecosistemas-peru' },
      { label: 'PNN Colombia — bosque andino y páramo', url: 'https://www.parquesnacionales.gov.co/nuestros-parques/sff-guanenta-alto-rio-fonce/' },
      { label: 'MinAmbiente Colombia — referencia regional de bosque seco tropical', url: 'https://www.minambiente.gov.co/direccion-de-bosques-biodiversidad-y-servicios-ecosistemicos/bosque-seco-tropical/' },
    ],
  },
  // BR · confianza alta
  caatinga: {
    id: 'caatinga',
    nombre: 'Caatinga',
    emoji: '🌵',
    color: '#AA7D43',
    resumen: 'Bosque y matorral semiárido exclusivamente brasileño, regido por lluvias escasas e irregulares y sequías plurianuales.',
    vegetacion: 'Bosque bajo deciduo, cactáceas, bromelias terrestres y arbustos espinosos; muchas plantas rebrotan o almacenan agua.',
    fauna: 'Guacamayo de Lear, armadillos, mocó, zorro cangrejero y reptiles del sertão.',
    suelos: 'Muy variables y a menudo someros sobre roca cristalina; fertilidad local moderada, pero baja infiltración y erosión intensa en superficies desnudas.',
    saberes: [],
    especies: [
      'Mandacaru',
      'Umbuzeiro',
      'Juazeiro',
      'Xique-xique',
      'Aroeira-do-sertão',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'IBGE — Vegetação do Brasil', url: 'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR' },
      { label: 'MMA Brasil — biodiversidade y biomas', url: 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade' },
    ],
  },
  // BR · confianza alta
  caatinga_enclaves_humedos: {
    id: 'caatinga_enclaves_humedos',
    nombre: 'Enclaves húmedos de la Caatinga',
    emoji: '🌳',
    color: '#4F7D3B',
    resumen: 'Islas de bosque húmedo o subhúmedo sobre sierras del Nordeste brasileño, rodeadas por la matriz semiárida de Caatinga.',
    vegetacion: 'Bosques montanos y brejos de altitude con elementos atlánticos y amazónicos, epífitas y cursos de agua más persistentes.',
    fauna: 'Aves forestales aisladas, pequeños mamíferos, anfibios y reptiles con endemismos locales.',
    suelos: 'Más profundos y húmedos que la matriz semiárida, pero a menudo inclinados y erosivos; funcionan como refugios climáticos.',
    saberes: [],
    especies: [
      'Bromelias',
      'Orquídeas',
      'Jatobá',
      'Ingá',
      'Helechos',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'IBGE — Vegetação do Brasil', url: 'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR' },
      { label: 'MMA Brasil — biodiversidade y biomas', url: 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade' },
    ],
  },
  // BR, CO, VE · confianza alta
  campinaranas_aguas_negras: {
    id: 'campinaranas_aguas_negras',
    nombre: 'Campinaranas del río Negro',
    emoji: '🌿',
    color: '#557A45',
    resumen: 'Mosaicos de bosque bajo, matorral y sabana amazónica sobre arenas blancas extremadamente pobres y a menudo encharcadas.',
    vegetacion: 'Campinarana forestada, arbustiva y gramíneo-leñosa con dosel bajo, raíces superficiales y flora especializada.',
    fauna: 'Aves restringidas a arenas blancas, primates y pequeños vertebrados; alta especialización local.',
    suelos: 'Espodosoles arenosos, muy ácidos y oligotróficos, con acumulación subsuperficial de materia orgánica y aluminio; son muy sensibles al tránsito y al fuego.',
    saberes: [],
    especies: [
      'Macucu',
      'Caraipa',
      'Mauritia',
      'Orquídeas de arena blanca',
      'Bromelias terrestres',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'Science Panel for the Amazon — Assessment Report 2021', url: 'https://www.sp-amazon.org/publications/' },
      { label: 'IBGE — campinarana y suelos arenosos', url: 'https://educa.ibge.gov.br/jovens/materias-especiais/23226-conhecendo-os-tipos-de-vegetacao-do-brasil.html' },
    ],
  },
  // BR · confianza alta
  campos_rupestres: {
    id: 'campos_rupestres',
    nombre: 'Campos rupestres de Espinhaço',
    emoji: '🌼',
    color: '#778A4A',
    resumen: 'Sabanas montanas y afloramientos rocosos de las sierras brasileñas, con suelos mínimos, nacientes y excepcional endemismo vegetal.',
    vegetacion: 'Pastizales rupestres, matorrales, rosetas, siemprevivas, orquídeas y bromelias entre cuarcitas y arenas.',
    fauna: 'Lobo de crin, pequeños mamíferos, colibríes, anfibios de cabeceras y numerosos polinizadores.',
    suelos: 'Muy someros, arenosos, ácidos y oligotróficos; turberas de nacientes y grietas húmedas concentran materia orgánica.',
    saberes: [],
    especies: [
      'Sempre-vivas',
      'Vellozia',
      'Lychnophora',
      'Paepalanthus',
      'Orquídeas rupestres',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'IBGE — Vegetação do Brasil', url: 'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR' },
      { label: 'MMA Brasil — biodiversidade y biomas', url: 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade' },
      { label: 'FAO GIAHS — sistema del Espinhaço Meridional', url: 'https://www.fao.org/giahs/giahs-around-the-world/brazil-minas-gerais-agricultural-system/en' },
    ],
  },
  // AR, BR, UY · confianza alta
  campos_uruguayos: {
    id: 'campos_uruguayos',
    nombre: 'Campos y pastizales uruguayos',
    emoji: '🌾',
    color: '#77A84B',
    resumen: 'Pastizales subtropicales del Uruguay, sur de Brasil y noreste argentino, con mosaicos de campo, palmares, serranías y bosques ribereños.',
    vegetacion: 'Gramíneas C3 y C4, hierbas, pajonales, palmares de butiá y bosques de quebrada o galería.',
    fauna: 'Venado de campo, ñandú, mulita, zorro de campo y aves como capuchinos y tero.',
    suelos: 'Muy heterogéneos: profundos sobre basalto o sedimentos, someros en sierras y arenosos en costas; la cobertura permanente es clave.',
    saberes: [],
    especies: [
      'Paspalum',
      'Andropogon',
      'Flechillas',
      'Butiá',
      'Carqueja',
    ],
    cultivos: ['trigo', 'avena', 'girasol', 'maiz_tropical', 'durazno', 'vid', 'alfalfa', 'trebol_blanco'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'Argentina — ecorregiones oficiales', url: 'https://www.argentina.gob.ar/parquesnacionales/ecorregiones' },
      { label: 'Uruguay — ambientes naturales', url: 'https://www.gub.uy/ministerio-ambiente/politicas-y-gestion/ambientes-del-uruguay' },
    ],
  },
  // AR, BR, PY · confianza alta
  chaco_humedo: {
    id: 'chaco_humedo',
    nombre: 'Chaco húmedo',
    emoji: '🌴',
    color: '#4F8A45',
    resumen: 'Llanura subtropical más lluviosa que el Chaco seco, con bosques, sabanas de palmeras, esteros y lagunas sometidos a pulsos de inundación.',
    vegetacion: 'Quebrachales húmedos, palmares de caranday, pajonales, selvas en galería y vegetación acuática.',
    fauna: 'Carpincho, yacaré, aguará guazú, mono carayá, tapir, pecaríes y gran diversidad de aves acuáticas.',
    suelos: 'Arcillosos y aluviales, con drenaje impedido, sodicidad o salinidad en bajos; alternan saturación y contracción estacional.',
    saberes: [],
    especies: [
      'Quebracho colorado chaqueño',
      'Caranday',
      'Urunday',
      'Palo piedra',
      'Paja amarilla',
    ],
    cultivos: ['maiz_tropical', 'sorgo', 'cana_azucar', 'naranjo', 'girasol', 'mistol', 'algarrobo_ar', 'chanar', 'vetiver'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'Argentina — ecorregiones oficiales', url: 'https://www.argentina.gob.ar/parquesnacionales/ecorregiones' },
      { label: 'Uruguay — ambientes naturales', url: 'https://www.gub.uy/ministerio-ambiente/politicas-y-gestion/ambientes-del-uruguay' },
      { label: 'Argentina — Chaco Húmedo', url: 'https://www.argentina.gob.ar/parquesnacionales/ecorregiones/chaco-humedo' },
    ],
  },
  // EC · confianza alta
  galapagos_matorral_xerico: {
    id: 'galapagos_matorral_xerico',
    nombre: 'Galápagos: zonas áridas y de transición',
    emoji: '🐢',
    color: '#8B8350',
    resumen: 'Ecosistemas volcánicos insulares cuya zonación va de litoral y matorral árido a transiciones húmedas; RESOLVE los representa con un único ECO_ID xerófilo.',
    vegetacion: 'Palo santo, cactus Opuntia y lava, matorral de transición; en islas altas aparecen zonas húmedas de Scalesia que el ECO_ID no separa.',
    fauna: 'Tortugas gigantes, iguanas terrestres, pinzones de Darwin, sinsontes y reptiles endémicos.',
    suelos: 'Suelos volcánicos jóvenes y discontinuos; cenizas más desarrolladas en zonas altas húmedas, roca desnuda y costras en zonas áridas.',
    saberes: [],
    especies: [
      'Opuntia de Galápagos',
      'Palo santo',
      'Scalesia',
      'Cactus de lava',
      'Tortuga gigante',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'Parque Nacional Galápagos — áreas protegidas', url: 'https://galapagos.gob.ec/areas-protegidas/' },
    ],
  },
  // GF, GY, SR, VE · confianza alta
  guayanas_bosques_inundables_delta: {
    id: 'guayanas_bosques_inundables_delta',
    nombre: 'Bosques inundables de Guayanas y delta del Orinoco',
    emoji: '💧',
    color: '#126F62',
    resumen: 'Pantanos forestados y bosques deltaicos de muy baja pendiente, controlados por inundación dulce, mareas y sedimentos costeros.',
    vegetacion: 'Palmares pantanosos, bosques de pantano, herbazales y transiciones a manglar; canales y diques naturales producen mosaicos finos.',
    fauna: 'Manatí antillano y amazónico según cuenca, nutria gigante, caimanes, ibis, garzas y peces estuarinos.',
    suelos: 'Suelos hidromorfos, arcillosos u orgánicos, con anoxia prolongada; salinidad variable cerca de estuarios.',
    saberes: [],
    especies: [
      'Mora excelsa',
      'Euterpe oleracea',
      'Mauritia flexuosa',
      'Pterocarpus officinalis',
      'Heliconias',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'PNUD — Guiana Shield in Brief', url: 'https://www.undp.org/guyana/publications/guiana-shield-brief' },
      { label: 'Guyana Protected Areas Commission', url: 'https://www.pac.gov.gy/our-work/' },
    ],
  },
  // BR, GF, GY, SR, VE · confianza alta
  guayanas_bosques_tierras_bajas: {
    id: 'guayanas_bosques_tierras_bajas',
    nombre: 'Bosques de tierras bajas del Escudo Guayanés',
    emoji: '🌳',
    color: '#075B3A',
    resumen: 'Bosques húmedos sobre geología muy antigua del Escudo Guayanés y cuencas Negro–Branco, con endemismo elevado y extensas áreas continuas.',
    vegetacion: 'Bosques altos siempreverdes, palmares y bosques de piedemonte; especies de madera densa y mosaicos sobre arenas blancas o rocas precámbricas.',
    fauna: 'Jaguar, tapir, gallito de las rocas, águila harpía, monos y una ictiofauna muy diversa.',
    suelos: 'Suelos extremadamente meteorizados, ácidos y oligotróficos; arenas blancas y afloramientos generan mosaicos edáficos de baja resiliencia.',
    saberes: [],
    especies: [
      'Greenheart',
      'Wallaba',
      'Mora',
      'Balatá',
      'Palmas Euterpe',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'PNUD — Guiana Shield in Brief', url: 'https://www.undp.org/guyana/publications/guiana-shield-brief' },
      { label: 'Guyana Protected Areas Commission', url: 'https://www.pac.gov.gy/our-work/' },
    ],
  },
  // EC · confianza alta
  humedales_guayaquil: {
    id: 'humedales_guayaquil',
    nombre: 'Pastizales inundables de Guayaquil',
    emoji: '💧',
    color: '#3E8B77',
    resumen: 'Planicies y humedales estacionales de la cuenca baja del Guayas, sometidos a inundaciones, sedimentación y una estación seca marcada.',
    vegetacion: 'Herbazales inundables, pantanos, bosques ribereños y transiciones a bosque seco y manglar.',
    fauna: 'Aves acuáticas, iguanas, peces estacionales, anfibios y pequeños mamíferos de humedal.',
    suelos: 'Aluviales finos, arcillosos e hidromorfos; alta fertilidad potencial pero anoxia, salinidad y compactación limitan el uso.',
    saberes: [],
    especies: [
      'Totora',
      'Lechuguín',
      'Guachapelí',
      'Samán',
      'Gramíneas palustres',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'MAATE Ecuador — conservación de ecosistemas nativos', url: 'https://sociobosque.ambiente.gob.ec/?q=node%2F44' },
    ],
  },
  // CO, VE · confianza alta
  humedales_orinoco: {
    id: 'humedales_orinoco',
    nombre: 'Humedales del Orinoco',
    emoji: '🦆',
    color: '#2F887D',
    resumen: 'Complejo de esteros, lagunas, sabanas inundables y bosques ribereños regido por el pulso anual del Orinoco y sus tributarios.',
    vegetacion: 'Herbazales acuáticos, morichales, bosques de galería y vegetación flotante; comunidades cambian con profundidad y duración del agua.',
    fauna: 'Caimán del Orinoco, tonina, manatí, chigüiro, anaconda, peces migratorios y aves acuáticas.',
    suelos: 'Aluviales e hidromorfos con periodos de anoxia y desecación; sedimentos y conectividad lateral sostienen productividad.',
    saberes: [],
    especies: [
      'Moriche',
      'Congrio',
      'Bora',
      'Paspalum inundable',
      'Victoria amazónica',
    ],
    cultivos: ['arroz', 'yuca', 'guandul', 'pasto_elefante'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'FAO Colombia — pesca artesanal en Orinoco y Amazonía', url: 'https://www.fao.org/voluntary-guidelines-small-scale-fisheries/in-action/where-we-work/colombia/en' },
    ],
  },
  // AR, BR, PY, UY · confianza alta
  humedales_parana_mesopotamia: {
    id: 'humedales_parana_mesopotamia',
    nombre: 'Humedales del Paraná y Mesopotamia',
    emoji: '🌊',
    color: '#3D8973',
    resumen: 'Planicies, islas, esteros y sabanas inundables del Paraná medio e inferior y la Mesopotamia, modeladas por crecientes y estiajes.',
    vegetacion: 'Pajonales, camalotales, juncales, bosques de sauce y aliso de río, palmares y selvas en galería.',
    fauna: 'Carpincho, ciervo de los pantanos, lobito de río, yacaré, peces migratorios y aves acuáticas.',
    suelos: 'Aluviales jóvenes e hidromorfos, continuamente redistribuidos; albardones bien drenados alternan con bajos anóxicos.',
    saberes: [],
    especies: [
      'Sauce criollo',
      'Aliso de río',
      'Irupé',
      'Camalote',
      'Pindó',
    ],
    cultivos: ['arroz', 'yerba_mate', 'naranjo', 'maiz_tropical', 'trebol_blanco', 'pasto_elefante', 'sauce_mimbre'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'Argentina — ecorregiones oficiales', url: 'https://www.argentina.gob.ar/parquesnacionales/ecorregiones' },
      { label: 'Uruguay — ambientes naturales', url: 'https://www.gub.uy/ministerio-ambiente/politicas-y-gestion/ambientes-del-uruguay' },
    ],
  },
  // CO · confianza alta
  isla_malpelo_xerica: {
    id: 'isla_malpelo_xerica',
    nombre: 'Isla Malpelo: roca oceánica xerófila',
    emoji: '🪨',
    color: '#77776D',
    resumen: 'Pequeña isla volcánica oceánica, rocosa y aislada, con vegetación terrestre mínima sostenida por lluvia, niebla y nutrientes de aves marinas.',
    vegetacion: 'Parches de helechos, líquenes y vegetación herbácea baja en grietas e islotes.',
    fauna: 'Piquero de Nazca, lagartos y cangrejo terrestre endémicos; el sistema terrestre depende fuertemente de aportes marinos.',
    suelos: 'Prácticamente ausentes; detritos y guano se acumulan en fisuras de roca volcánica.',
    saberes: [],
    especies: [
      'Pityrogramma dealbata',
      'Líquenes Caloplaca',
      'Anolis agassizi',
      'Diploglossus millepunctatus',
      'Cangrejo de Malpelo',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'PNN Colombia — Santuario de Malpelo', url: 'https://www.parquesnacionales.gov.co/nuestros-parques/sff-malpelo/' },
    ],
  },
  // CL · confianza media
  islas_desventuradas: {
    id: 'islas_desventuradas',
    nombre: 'Islas Desventuradas: matorral oceánico',
    emoji: '🏝️',
    color: '#6F8060',
    resumen: 'Islas volcánicas hiperaisladas de San Félix y San Ambrosio, con vegetación terrestre escasa, endémica y condicionada por aridez oceánica.',
    vegetacion: 'Matorral bajo, herbazales y plantas rupícolas en grietas y laderas; cobertura muy discontinua.',
    fauna: 'Aves marinas nidificantes, lagartijas endémicas e invertebrados insulares; el entorno marino concentra gran diversidad.',
    suelos: 'Suelos volcánicos someros, secos y expuestos a viento, sal y erosión; depósitos de guano aportan nutrientes localmente.',
    saberes: [],
    especies: [
      'Thamnoseris',
      'Sanambrosia',
      'Atriplex insular',
      'Helechos rupícolas',
      'Liquenes',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'CONAF — Archipiélago Juan Fernández', url: 'https://www.conaf.cl/parque_nacionales/parque-nacional-archipielago-juan-fernandez/' },
      { label: 'MMA Chile — Nazca-Desventuradas', url: 'https://gestioncba.mma.gob.cl/SolicitudAP/Details/34' },
    ],
  },
  // CO, VE · confianza alta
  llanos_orinoquia: {
    id: 'llanos_orinoquia',
    nombre: 'Llanos del Orinoco',
    emoji: '🌾',
    color: '#93A83B',
    resumen: 'Sabanas tropicales de la cuenca del Orinoco con alternancia anual entre sequía e inundación y grandes gradientes de drenaje.',
    vegetacion: 'Pastizales abiertos, sabanas arboladas, morichales, esteros y bosques de galería; bancos, bajos y esteros sostienen comunidades distintas.',
    fauna: 'Chigüiro, venado de cola blanca, oso hormiguero, caimán del Orinoco, anaconda y grandes bandadas de aves acuáticas.',
    suelos: 'Predominan suelos ácidos y pobres; planicies aluviales alternan anoxia e intensa desecación, mientras bancos elevados drenan mejor.',
    saberes: [],
    especies: [
      'Moriche',
      'Chaparra',
      'Samán',
      'Trachypogon',
      'Palma llanera',
    ],
    cultivos: ['arroz', 'maiz_tropical', 'cana_azucar', 'guandul', 'crotalaria', 'pasto_elefante', 'gliricidia', 'vetiver'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'FAO Colombia — pesca artesanal en Orinoco y Amazonía', url: 'https://www.fao.org/voluntary-guidelines-small-scale-fisheries/in-action/where-we-work/colombia/en' },
    ],
  },
  // BR, CO, GF, GY, SR, VE · confianza alta
  manglares_amazon_orinoco_caribe_sur: {
    id: 'manglares_amazon_orinoco_caribe_sur',
    nombre: 'Manglares del Amazonas, Orinoco y Caribe sur',
    emoji: '🌊',
    color: '#156B5A',
    resumen: 'Manglares y humedales mareales de grandes deltas y costas sedimentarias del norte sudamericano, modulados por agua dulce, sedimentos y salinidad.',
    vegetacion: 'Bosques de mangle rojo, negro, blanco y botoncillo, marismas, planicies de marea y bosques pantanosos tierra adentro.',
    fauna: 'Manatí, caimanes, nutrias, cangrejos, moluscos, peces juveniles, ibis y garzas.',
    suelos: 'Lodos finos anóxicos, salobres y ricos en carbono; dependen del intercambio mareal y del aporte fluvial.',
    saberes: [],
    especies: [
      'Mangle rojo',
      'Mangle negro',
      'Mangle blanco',
      'Botoncillo',
      'Mora de pantano',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'Guyana — sistema oficial de manglares', url: 'https://www.mangroves.gov.gy/about/' },
    ],
  },
  // BR · confianza alta
  manglares_atlantico_sur_brasil: {
    id: 'manglares_atlantico_sur_brasil',
    nombre: 'Manglares del Atlántico sur de Brasil',
    emoji: '🌊',
    color: '#247567',
    resumen: 'Manglares subtropicales y tropicales del litoral atlántico sur brasileño, ligados a estuarios, lagunas y planicies de marea.',
    vegetacion: 'Mangle rojo, negro y blanco con marismas y bosques de restinga adyacentes; menor porte hacia el límite austral.',
    fauna: 'Cangrejo uçá, ostras, peces juveniles, garzas, martines pescadores y mamíferos estuarinos.',
    suelos: 'Lodos salobres anóxicos con abundante materia orgánica; relleno, canalización y pérdida de mareas degradan rápidamente el sistema.',
    saberes: [],
    especies: [
      'Mangle rojo',
      'Mangle negro',
      'Mangle blanco',
      'Cangrejo uçá',
      'Spartina',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'IBGE — Vegetação do Brasil', url: 'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR' },
      { label: 'MMA Brasil — biodiversidade y biomas', url: 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade' },
    ],
  },
  // CO, EC, PE · confianza alta
  manglares_pacifico_suramericano: {
    id: 'manglares_pacifico_suramericano',
    nombre: 'Manglares del Pacífico suramericano',
    emoji: '🦀',
    color: '#157367',
    resumen: 'Manglares tropicales del Pacífico de Colombia, Ecuador y extremo norte peruano, sobre estuarios lluviosos o estacionales y amplias planicies de marea.',
    vegetacion: 'Mangle rojo de gran porte en el norte húmedo, mangle negro, blanco y jelí; canales, playones y bosque de guandal asociado.',
    fauna: 'Piangua, cangrejos, camarones, peces juveniles, garzas, pelícanos y mamíferos costeros.',
    suelos: 'Sedimentos mareales blandos, anóxicos y salinos con alto carbono; la elevación centimétrica cambia inundación y especie dominante.',
    saberes: [],
    especies: [
      'Mangle rojo',
      'Mangle negro',
      'Mangle blanco',
      'Jelí',
      'Nato',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'FAO — derechos y pesquería de concha en manglares de Ecuador', url: 'https://www.fao.org/fishery/static/tenure-user-rights/root/volume1/C3%20Rights-based%20Approaches%20in%20Ecuador%E2%80%99s%20Fishery%20for%20Mangrove%20Cockles%20.pdf' },
    ],
  },
  // AR, BR · confianza alta
  mata_araucaria_altura: {
    id: 'mata_araucaria_altura',
    nombre: 'Bosque de araucaria de la Mata Atlántica',
    emoji: '🌲',
    color: '#245F3A',
    resumen: 'Bosque húmedo subtropical de planaltos frescos, dominado por araucaria brasileña y mezclado con lauráceas y mirtáceas.',
    vegetacion: 'Dosel emergente de Araucaria angustifolia sobre bosque siempreverde o semideciduo, con yerba mate, imbuia, helechos y bambúes.',
    fauna: 'Papagayo charao, yacutinga, mono aullador, felinos y pequeños mamíferos consumidores de piñones.',
    suelos: 'Suelos profundos, ácidos y arcillosos derivados de basaltos; alta materia orgánica superficial bajo clima húmedo y fresco.',
    saberes: [],
    especies: [
      'Araucaria brasileña',
      'Yerba mate',
      'Imbuia',
      'Xaxim',
      'Guabiroba',
    ],
    cultivos: ['yerba_mate', 'manzano', 'durazno', 'arandano', 'maiz_tropical', 'nogal', 'trebol_blanco'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'IBGE — Vegetação do Brasil', url: 'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR' },
      { label: 'MMA Brasil — biodiversidade y biomas', url: 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade' },
    ],
  },
  // BR · confianza alta
  mata_atlantica_costera: {
    id: 'mata_atlantica_costera',
    nombre: 'Bosques húmedos costeros de la Mata Atlántica',
    emoji: '🌧️',
    color: '#126A43',
    resumen: 'Bosques tropicales húmedos entre costa y sierras orientales de Brasil, con lluvia oceánica, fuerte gradiente altitudinal y alto endemismo.',
    vegetacion: 'Bosque ombrófilo denso con palmeras, lauráceas, mirtáceas, lianas, bromelias y orquídeas; niebla frecuente en laderas altas.',
    fauna: 'Muriquis, tamarinos, perezosos, tucanes, jacutingas y numerosos anfibios endémicos.',
    suelos: 'Suelos muy meteorizados y ácidos, a menudo someros en laderas; la cobertura protege contra erosión intensa bajo lluvias abundantes.',
    saberes: [],
    especies: [
      'Palmito juçara',
      'Jequitibá',
      'Pau-brasil',
      'Embaúba',
      'Bromelias',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'IBGE — Vegetação do Brasil', url: 'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR' },
      { label: 'MMA Brasil — biodiversidade y biomas', url: 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade' },
    ],
  },
  // BR · confianza alta
  mata_atlantica_interior: {
    id: 'mata_atlantica_interior',
    nombre: 'Bosques interiores de la Mata Atlántica',
    emoji: '🌳',
    color: '#397A3E',
    resumen: 'Bosques estacionales del interior nordestino, más secos y fragmentados que la franja atlántica costera.',
    vegetacion: 'Bosque semideciduo a deciduo con dosel más abierto, lianas y transiciones hacia caatinga y cerrados.',
    fauna: 'Puma, margay, monos, pecaríes y aves forestales que dependen de corredores entre fragmentos.',
    suelos: 'Suelos profundos pero variables, desde latosoles ácidos hasta terrenos más fértiles; la estación seca y la fragmentación elevan el riesgo de fuego.',
    saberes: [],
    especies: [
      'Pau-d’arco',
      'Jatobá',
      'Jequitibá',
      'Sucupira',
      'Barriguda',
    ],
    cultivos: ['yerba_mate', 'cana_azucar', 'naranjo', 'maracuya', 'maiz_tropical', 'nogal_cafetero', 'crotalaria', 'vetiver'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'IBGE — Vegetação do Brasil', url: 'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR' },
      { label: 'MMA Brasil — biodiversidade y biomas', url: 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade' },
    ],
  },
  // BR · confianza alta
  mata_atlantica_restingas: {
    id: 'mata_atlantica_restingas',
    nombre: 'Restingas atlánticas',
    emoji: '🏝️',
    color: '#4E8D67',
    resumen: 'Mosaico costero sobre arenas cuaternarias sometido a sal, viento, sequía edáfica e inundación local.',
    vegetacion: 'Herbazales de dunas, matorrales, bromeliales y bosques bajos; la estructura cambia en pocos metros con relieve y nivel freático.',
    fauna: 'Lagartijas, anfibios de charcas temporarias, aves costeras y pequeños mamíferos endémicos o restringidos.',
    suelos: 'Arenas muy permeables, ácidas y pobres en nutrientes; podzoles y depresiones orgánicas o anegables aparecen detrás de cordones dunares.',
    saberes: [],
    especies: [
      'Clusia',
      'Aechmea',
      'Ipomoea pes-caprae',
      'Guapira',
      'Cereus fernambucensis',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'IBGE — Vegetação do Brasil', url: 'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR' },
      { label: 'MMA Brasil — biodiversidade y biomas', url: 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade' },
    ],
  },
  // BR · confianza alta
  mata_atlantica_seca: {
    id: 'mata_atlantica_seca',
    nombre: 'Bosques secos atlánticos de Brasil',
    emoji: '🍂',
    color: '#8E7940',
    resumen: 'Bosques estacionales deciduos del interior oriental de Brasil, en contacto con Caatinga, Cerrado y Mata Atlántica húmeda.',
    vegetacion: 'Dosel mediano que pierde gran parte de sus hojas, árboles de madera densa, lianas y cactáceas en afloramientos.',
    fauna: 'Muriquis y primates localmente, felinos, pecaríes, armadillos y aves de bosque estacional.',
    suelos: 'Suelos más fértiles que muchos bosques húmedos vecinos, a menudo sobre calizas; muy expuestos a erosión tras la deforestación.',
    saberes: [],
    especies: [
      'Aroeira',
      'Angico',
      'Barriguda',
      'Ipê-roxo',
      'Cereus',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'IBGE — Vegetação do Brasil', url: 'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR' },
      { label: 'MMA Brasil — biodiversidade y biomas', url: 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade' },
    ],
  },
  // CO, VE · confianza alta
  matorrales_xericos_caribe_suramericano: {
    id: 'matorrales_xericos_caribe_suramericano',
    nombre: 'Matorrales xerófilos del Caribe suramericano',
    emoji: '🌵',
    color: '#B0804F',
    resumen: 'Cardonales y matorrales áridos de la costa caribeña de Colombia y Venezuela, bajo lluvias escasas, alta evaporación y vientos salinos.',
    vegetacion: 'Cactáceas columnares, cujíes, dividivis, agaves, bromelias terrestres y herbazales efímeros.',
    fauna: 'Cardenal guajiro, iguanas, lagartijas, zorros, murciélagos nectarívoros y aves marinas costeras.',
    suelos: 'Aridisoles someros, pedregosos o arenosos, frecuentemente salinos; costras y dunas son sensibles al tránsito.',
    saberes: [],
    especies: [
      'Cardón',
      'Cují',
      'Dividivi',
      'Agave cocui',
      'Melocactus',
    ],
    cultivos: ['mijo', 'sorgo', 'chile_seco', 'guandul', 'nopal'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'MinAmbiente Colombia — Bosque Seco Tropical', url: 'https://www.minambiente.gov.co/direccion-de-bosques-biodiversidad-y-servicios-ecosistemicos/bosque-seco-tropical/' },
    ],
  },
  // CO, VE · confianza alta
  montanas_caribe_norte: {
    id: 'montanas_caribe_norte',
    nombre: 'Montañas húmedas del Caribe suramericano',
    emoji: '⛰️',
    color: '#347558',
    resumen: 'Bosques montanos aislados de la Cordillera de la Costa venezolana y Sierra Nevada de Santa Marta, con gradientes desde el Caribe seco hasta cumbres nubladas.',
    vegetacion: 'Bosques siempreverdes montanos, palmares, helechos, epífitas y parches de bosque achaparrado en crestas.',
    fauna: 'Puma, mono aullador, paujiles, colibríes y anfibios de distribución muy restringida.',
    suelos: 'Suelos húmedos de montaña, someros en laderas y con acumulación orgánica bajo niebla; alta susceptibilidad a movimientos en masa.',
    saberes: [],
    especies: [
      'Palma de cera',
      'Podocarpus',
      'Cedro de montaña',
      'Bromelias',
      'Lauráceas',
    ],
    cultivos: ['cafe', 'aguacate', 'lulo', 'mora_andina', 'maracuya', 'platano_sombra', 'inga', 'nogal_cafetero'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'MINAM Perú — Mapa Nacional de Ecosistemas', url: 'https://sinia.minam.gob.pe/documentos/mapa-nacional-ecosistemas-peru' },
      { label: 'PNN Colombia — bosque andino y páramo', url: 'https://www.parquesnacionales.gov.co/nuestros-parques/sff-guanenta-alto-rio-fonce/' },
    ],
  },
  // BO, BR, PY · confianza alta
  pantanal: {
    id: 'pantanal',
    nombre: 'Pantanal',
    emoji: '🐊',
    color: '#3B8D75',
    resumen: 'Una de las mayores planicies inundables continentales, donde el pulso del río Paraguay conecta sabanas, bosques, lagunas y canales.',
    vegetacion: 'Campos inundables, cambarazales, carandazales, capões boscosos, vegetación acuática y bosques ribereños.',
    fauna: 'Jaguar, ciervo de los pantanos, nutria gigante, yacarés, tuiuiú y enorme diversidad de peces.',
    suelos: 'Sedimentos aluviales jóvenes, con hidromorfía, anoxia y fertilidad espacialmente variable; el microrelieve controla duración de la inundación.',
    saberes: [],
    especies: [
      'Carandá',
      'Cambarà',
      'Paratudo',
      'Aguapé',
      'Ipê-amarelo',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'IBGE — Vegetação do Brasil', url: 'https://www.ibge.gov.br/geociencias/informacoes-ambientais/vegetacao/10872-vegetacao.html?lang=pt-BR' },
      { label: 'MMA Brasil — biodiversidade y biomas', url: 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade' },
      { label: 'ICMBio — Pantanal', url: 'https://www.gov.br/icmbio/pt-br/assuntos/biodiversidade/unidade-de-conservacao/unidades-de-biomas/pantanal/pantanal' },
    ],
  },
  // BR, CO, GY, SR, VE · confianza alta
  pantepui_guayana_alta: {
    id: 'pantepui_guayana_alta',
    nombre: 'Pantepui y tierras altas guayanesas',
    emoji: '⛰️',
    color: '#3D6950',
    resumen: 'Montañas y mesetas de arenisca aisladas sobre el Escudo Guayanés, con gradientes abruptos, nubes frecuentes y altísimo endemismo.',
    vegetacion: 'Bosques montanos, matorrales, turberas, sabanas de altura y vegetación rupícola; cada tepuy funciona como isla biogeográfica.',
    fauna: 'Gallito de las rocas, ranas y lagartijas endémicas, pequeños mamíferos y aves de montaña.',
    suelos: 'Suelos someros, ácidos y extremadamente pobres sobre areniscas; turberas locales almacenan agua y carbono.',
    saberes: [],
    especies: [
      'Heliamphora',
      'Bonnetia',
      'Stegolepis',
      'Brocchinia',
      'Orquídeas tepuyanas',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'PNUD — Guiana Shield in Brief', url: 'https://www.undp.org/guyana/publications/guiana-shield-brief' },
      { label: 'Guyana Protected Areas Commission', url: 'https://www.pac.gov.gy/our-work/' },
    ],
  },
  // CO, EC, VE · confianza alta
  paramos_andinos: {
    id: 'paramos_andinos',
    nombre: 'Páramos de los Andes del norte',
    emoji: '🌧️',
    color: '#557B69',
    resumen: 'Ecosistemas fríos y muy húmedos por encima del bosque andino, con niebla, lluvias abundantes y suelos que regulan agua; no son puna árida.',
    vegetacion: 'Pajonales, frailejonales, chuscales, matorrales, turberas, humedales y bosques achaparrados.',
    fauna: 'Oso andino, danta de montaña, venados, cóndor, colibríes y anfibios endémicos.',
    suelos: 'Andisoles y suelos orgánicos profundos, fríos y de alta capacidad de retención; drenaje, quema o labranza pueden liberar carbono y perder regulación hídrica.',
    saberes: [],
    especies: [
      'Frailejones',
      'Chusquea',
      'Calamagrostis',
      'Polylepis',
      'Puya',
    ],
    cultivos: ['papa', 'oca', 'ulluco', 'tarwi', 'quinoa', 'cebada'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'MINAM Perú — Mapa Nacional de Ecosistemas', url: 'https://sinia.minam.gob.pe/documentos/mapa-nacional-ecosistemas-peru' },
      { label: 'PNN Colombia — bosque andino y páramo', url: 'https://www.parquesnacionales.gov.co/nuestros-parques/sff-guanenta-alto-rio-fonce/' },
    ],
  },
  // BO, PE · confianza alta
  puna_humeda_central: {
    id: 'puna_humeda_central',
    nombre: 'Puna húmeda central',
    emoji: '💧',
    color: '#668C61',
    resumen: 'Pastizales altoandinos fríos con lluvias estivales mayores, lagunas, turberas y redes de bofedales que almacenan agua.',
    vegetacion: 'Pajonales densos de ichu, céspedes, bofedales, tolares y bosques relictos de queñoa.',
    fauna: 'Vicuña, taruca, zambullidor del Titicaca, flamencos, vizcachas y aves de humedal.',
    suelos: 'Suelos minerales fríos alternan con turbas y horizontes orgánicos saturados; el drenaje o pisoteo concentrado degrada lentamente los bofedales.',
    saberes: [],
    especies: [
      'Ichu',
      'Queñoa',
      'Puya raimondii',
      'Distichia',
      'Oxychloe',
    ],
    cultivos: ['papa', 'quinoa', 'oca', 'ulluco', 'tarwi', 'amaranto', 'cebada', 'trebol_blanco'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'MINAM Perú — Mapa Nacional de Ecosistemas', url: 'https://sinia.minam.gob.pe/documentos/mapa-nacional-ecosistemas-peru' },
      { label: 'PNN Colombia — bosque andino y páramo', url: 'https://www.parquesnacionales.gov.co/nuestros-parques/sff-guanenta-alto-rio-fonce/' },
    ],
  },
  // AR, BO, CL, PE · confianza alta
  puna_seca_central: {
    id: 'puna_seca_central',
    nombre: 'Puna seca central',
    emoji: '🏔️',
    color: '#9A7A55',
    resumen: 'Altiplano frío y muy árido con grandes amplitudes térmicas, salares y vegetación rala concentrada alrededor de humedales.',
    vegetacion: 'Tolares, pajonales abiertos, yaretales y bofedales muy localizados junto a manantiales y cursos de agua.',
    fauna: 'Vicuña, suri, flamencos altoandinos, vizcacha y zorro culpeo.',
    suelos: 'Aridisoles pedregosos, salinos o volcánicos, con poca materia orgánica; vegas y bofedales tienen suelos orgánicos frágiles.',
    saberes: [],
    especies: [
      'Tola',
      'Yareta',
      'Ichu',
      'Queñoa',
      'Distichia muscoides',
    ],
    cultivos: ['quinoa', 'papa', 'oca', 'ulluco', 'tarwi', 'cebada', 'alfalfa'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'MINAM Perú — Mapa Nacional de Ecosistemas', url: 'https://sinia.minam.gob.pe/documentos/mapa-nacional-ecosistemas-peru' },
      { label: 'PNN Colombia — bosque andino y páramo', url: 'https://www.parquesnacionales.gov.co/nuestros-parques/sff-guanenta-alto-rio-fonce/' },
    ],
  },
  // CL · confianza media
  rapa_nui_bosque_subtropical_transformado: {
    id: 'rapa_nui_bosque_subtropical_transformado',
    nombre: 'Rapa Nui y Sala y Gómez',
    emoji: '🗿',
    color: '#657A4B',
    resumen: 'Islas subtropicales extremadamente aisladas del Pacífico suroriental; la vegetación actual de Rapa Nui está profundamente transformada y no equivale a un bosque intacto.',
    vegetacion: 'Pastizales y matorrales secundarios dominan Rapa Nui; persisten helechos, especies costeras y programas de restauración de flora nativa. Sala y Gómez es roca oceánica con aves marinas.',
    fauna: 'Aves marinas, reptiles e invertebrados; gran parte del endemismo terrestre histórico se perdió o está restringido.',
    suelos: 'Volcánicos, meteorizados y muy expuestos a erosión eólica e hídrica cuando falta cobertura.',
    saberes: [],
    especies: [
      'Toromiro (en restauración)',
      'Sophora',
      'Triumfetta semitriloba',
      'Helechos nativos',
      'Aves marinas',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'CONAF — Parque Nacional Rapa Nui', url: 'https://www.conaf.cl/parque_nacionales/parque-nacional-rapa-nui/' },
    ],
  },
  // BO, BR, PE · confianza alta
  sabanas_beni: {
    id: 'sabanas_beni',
    nombre: 'Sabanas inundables del Beni',
    emoji: '💧',
    color: '#6D9E54',
    resumen: 'Mosaico de sabanas, islas de bosque y humedales estacionales en las planicies de los Llanos de Moxos y alto Madeira.',
    vegetacion: 'Pastizales inundables, palmares, bosques de galería e islas forestales sobre microrelieves elevados.',
    fauna: 'Ciervo de los pantanos, paraba barba azul, londra, capibara, caimanes y aves acuáticas.',
    suelos: 'Suelos aluviales hidromorfos con ciclos de anegamiento y sequía; pequeñas diferencias de cota controlan oxígeno y vegetación.',
    saberes: [],
    especies: [
      'Palma motacú',
      'Tajibo',
      'Patujú',
      'Gramíneas de inundación',
      'Victoria boliviana',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'Science Panel for the Amazon — humedales amazónicos', url: 'https://www.sp-amazon.org/publications/' },
    ],
  },
  // BR, GY, SR, VE · confianza alta
  sabanas_guayanesas: {
    id: 'sabanas_guayanesas',
    nombre: 'Sabanas del Escudo Guayanés',
    emoji: '🌾',
    color: '#8A9B3A',
    resumen: 'Extensas sabanas tropicales sobre el Escudo Guayanés, interrumpidas por bosques de galería, humedales y serranías.',
    vegetacion: 'Pastizales, sabanas arbustivas, morichales y bosques ribereños; la humedad del suelo y el fuego producen mosaicos.',
    fauna: 'Oso hormiguero gigante, venado, jaguar, armadillos, aves de pastizal y peces de cabeceras.',
    suelos: 'Suelos viejos, ácidos y pobres, a menudo arenosos; depresiones estacionales presentan hidromorfía.',
    saberes: [],
    especies: [
      'Trachypogon',
      'Moriche',
      'Curatella americana',
      'Byrsonima',
      'Axonopus',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'PNUD — Guiana Shield in Brief', url: 'https://www.undp.org/guyana/publications/guiana-shield-brief' },
      { label: 'Guyana Protected Areas Commission', url: 'https://www.pac.gov.gy/our-work/' },
    ],
  },
  // BO, CO, PE · confianza alta
  valles_secos_interandinos: {
    id: 'valles_secos_interandinos',
    nombre: 'Valles secos interandinos',
    emoji: '🏜️',
    color: '#A17448',
    resumen: 'Bosques secos y matorrales encerrados entre cordilleras, con fuerte sombra de lluvia, ríos estacionales y elevado endemismo.',
    vegetacion: 'Bosque deciduo bajo, cactáceas, acacias, molles y matorral espinoso; franjas ribereñas contrastan con laderas secas.',
    fauna: 'Venados, zorros, felinos pequeños, loros, colibríes y reptiles adaptados a calor y sequía.',
    suelos: 'Suelos pedregosos o aluviales, frecuentemente someros y erosionables; salinidad local en fondos cerrados.',
    saberes: [],
    especies: [
      'Molle',
      'Tara',
      'Ceiba',
      'Prosopis',
      'Cactáceas columnares',
    ],
    cultivos: ['maiz_tropical', 'poroto_trepador', 'chile_seco', 'aguacate', 'vid', 'cana_azucar', 'guandul', 'nopal'],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'MINAM Perú — Mapa Nacional de Ecosistemas', url: 'https://sinia.minam.gob.pe/documentos/mapa-nacional-ecosistemas-peru' },
      { label: 'PNN Colombia — bosque andino y páramo', url: 'https://www.parquesnacionales.gov.co/nuestros-parques/sff-guanenta-alto-rio-fonce/' },
      { label: 'MinAmbiente Colombia — Bosque Seco Tropical', url: 'https://www.minambiente.gov.co/direccion-de-bosques-biodiversidad-y-servicios-ecosistemicos/bosque-seco-tropical/' },
    ],
  },
  // BR, CO, PE · confianza alta
  varzeas_igapos_amazonicos: {
    id: 'varzeas_igapos_amazonicos',
    nombre: 'Várzeas e igapós amazónicos',
    emoji: '🌊',
    color: '#147D71',
    resumen: 'Bosques y humedales sometidos al pulso anual de inundación de ríos amazónicos; la duración, profundidad y química del agua organizan el paisaje.',
    vegetacion: 'Bosques inundables, palmares, lagos, gramalotes y vegetación flotante. Las várzeas de aguas blancas son más fértiles que los igapós de aguas negras.',
    fauna: 'Manatí amazónico, delfines de río, caimanes, capibaras, peces migratorios, aves acuáticas y primates ribereños.',
    suelos: 'Sedimentos aluviales jóvenes y relativamente fértiles en várzea; arenas y suelos muy pobres y ácidos en igapó. El drenaje artificial rompe el pulso ecológico.',
    saberes: [],
    especies: [
      'Aguaje',
      'Açaí',
      'Camu-camu',
      'Victoria amazónica',
      'Kapok de várzea',
    ],
    fuentes: [
      { label: 'RESOLVE Ecoregions 2017 — catálogo y licencia CC BY 4.0', url: 'https://developers.google.com/earth-engine/datasets/catalog/RESOLVE_ECOREGIONS_2017' },
      { label: 'Dinerstein et al. 2017 — artículo', url: 'https://doi.org/10.1093/biosci/bix014' },
      { label: 'Science Panel for the Amazon — Assessment Report 2021', url: 'https://www.sp-amazon.org/publications/' },
    ],
  },
};
