import type { CensoProvincia } from './pueblosOriginarios';

/**
 * GENERADO. No editar a mano.
 *
 * Lo arma `_research/censo-2022-pueblos-indigenas/build-censo-indigena.mjs`
 * desde los cuadros de resultados definitivos del Censo Nacional de Población,
 * Hogares y Viviendas 2022 (INDEC). Las decisiones de armado están ahí.
 *
 * 1.306.730 personas que se reconocen indígenas o descendientes de pueblos
 * indígenas u originarios, sobre 45.618.787 en viviendas particulares.
 * 58 rótulos de pueblo, 24 jurisdicciones, 527 departamentos.
 *
 * Dos cosas que hay que decir cada vez que se muestran estos números:
 *
 * 1. El censo cuenta **autorreconocimiento donde la persona vive**, no
 *    territorio. Alguien que se reconoce parte de un pueblo del noroeste y
 *    vive en Rosario suma en Santa Fe. Por eso esta capa no dice de quién es la
 *    tierra ni quién estuvo antes: dice cuánta gente se reconoce indígena hoy,
 *    ahí.
 *
 *    El ejemplo va sin nombrar un pueblo a propósito. Los rótulos del censo
 *    —«Kolla», «Qom/Toba», «Diaguita»— se muestran tal cual los publica el
 *    INDEC, porque son lo que la gente contestó y cambiarlos sería falsear la
 *    fuente. Pero usar uno de esos nombres como ejemplo genérico, en minúscula
 *    y en nuestra propia prosa, es otra cosa: fuera de la tabla, «kolla» en
 *    minúscula circula como término despectivo para la gente del altiplano.
 *    En el dato, el nombre de la fuente; en el texto nuestro, ninguno.
 *
 * 2. 431.703 personas —el 33% de las que se reconocen indígenas— no
 *    declararon a qué pueblo pertenecen. La lista de pueblos no es un padrón:
 *    es lo que contestó quien contestó.
 */
export const CENSO_AR: CensoProvincia[] = [
  {
    provincia: "Ciudad Autónoma de Buenos Aires",
    poblacion: 3095454,
    indigena: 74724,
    sinInformacion: 30239,
    pueblos: [
      { pueblo: "Guaraní", personas: 9465 },
      { pueblo: "Quechua", personas: 8374 },
      { pueblo: "Aymara", personas: 6449 },
      { pueblo: "Diaguita", personas: 4154 },
      { pueblo: "Mapuche", personas: 3632 },
      { pueblo: "Kolla", personas: 2572 },
      { pueblo: "Qom/Toba", personas: 1520 },
      { pueblo: "Comechingón", personas: 1355 },
      { pueblo: "Tehuelche", personas: 938 },
      { pueblo: "Charrúa", personas: 878 },
      { pueblo: "Ranquel", personas: 843 },
      { pueblo: "Wichi", personas: 828 },
      { pueblo: "Mapuche Tehuelche", personas: 797 },
      { pueblo: "Huarpe", personas: 640 },
      { pueblo: "Omaguaca", personas: 217 },
      { pueblo: "Moqoit/Mocoví", personas: 189 },
      { pueblo: "Günün A Küna", personas: 143 },
      { pueblo: "Tonokoté", personas: 137 },
      { pueblo: "Atacama", personas: 122 },
      { pueblo: "Querandí", personas: 114 },
      { pueblo: "Chicha", personas: 106 },
      { pueblo: "Mbya Guaraní", personas: 104 },
      { pueblo: "Chana", personas: 98 },
      { pueblo: "Sanavirón", personas: 92 },
      { pueblo: "Lule Vilela", personas: 82 },
      { pueblo: "Diaguita Cacano", personas: 80 },
      { pueblo: "Lule", personas: 75 },
      { pueblo: "Selk´Nam/Ona", personas: 63 },
      { pueblo: "Guaycurú", personas: 62 },
      { pueblo: "Aoniken", personas: 44 },
      { pueblo: "Guarayo", personas: 38 },
      { pueblo: "Pilagá", personas: 38 },
      { pueblo: "Chorote", personas: 32 },
      { pueblo: "Avipón", personas: 31 },
      { pueblo: "Ocloya", personas: 31 },
      { pueblo: "Chané", personas: 23 },
      { pueblo: "Tastil", personas: 20 },
      { pueblo: "Vilela", personas: 14 },
      { pueblo: "Kolla Atacameño", personas: 13 },
      { pueblo: "Corundí", personas: 12 },
      { pueblo: "Toara", personas: 12 },
      { pueblo: "Chulupí/Nivaclé", personas: 11 },
      { pueblo: "Yagán", personas: 9 },
      { pueblo: "Weenhayek", personas: 7 },
      { pueblo: "Fiscara", personas: 6 },
      { pueblo: "Minuán", personas: 5 },
      { pueblo: "Churumata", personas: 2 },
      { pueblo: "Tapiete", personas: 2 },
      { pueblo: "Tilián", personas: 2 },
      { pueblo: "Iogys", personas: 1 },
      { pueblo: "Isoceño", personas: 1 },
      { pueblo: "Jujuí", personas: 1 },
      { pueblo: "Michilingüe", personas: 1 },
    ],
    departamentos: [
      { departamento: "Comuna 1", poblacion: 221001, indigena: 8163 },
      { departamento: "Comuna 10", poblacion: 171896, indigena: 4066 },
      { departamento: "Comuna 11", poblacion: 201905, indigena: 3472 },
      { departamento: "Comuna 12", poblacion: 235364, indigena: 3444 },
      { departamento: "Comuna 13", poblacion: 262330, indigena: 3393 },
      { departamento: "Comuna 14", poblacion: 247252, indigena: 3697 },
      { departamento: "Comuna 15", poblacion: 195265, indigena: 4417 },
      { departamento: "Comuna 2", poblacion: 160609, indigena: 2355 },
      { departamento: "Comuna 3", poblacion: 193537, indigena: 6161 },
      { departamento: "Comuna 4", poblacion: 227024, indigena: 7109 },
      { departamento: "Comuna 5", poblacion: 192449, indigena: 4623 },
      { departamento: "Comuna 6", poblacion: 201764, indigena: 3367 },
      { departamento: "Comuna 7", poblacion: 213262, indigena: 5608 },
      { departamento: "Comuna 8", poblacion: 203888, indigena: 8718 },
      { departamento: "Comuna 9", poblacion: 167908, indigena: 6131 },
    ],
  },
  {
    provincia: "Buenos Aires",
    poblacion: 17408906,
    indigena: 371830,
    sinInformacion: 179726,
    pueblos: [
      { pueblo: "Guaraní", personas: 49845 },
      { pueblo: "Mapuche", personas: 29677 },
      { pueblo: "Quechua", personas: 25770 },
      { pueblo: "Qom/Toba", personas: 16503 },
      { pueblo: "Diaguita", personas: 15949 },
      { pueblo: "Aymara", personas: 8995 },
      { pueblo: "Kolla", personas: 6348 },
      { pueblo: "Comechingón", personas: 5111 },
      { pueblo: "Mapuche Tehuelche", personas: 4993 },
      { pueblo: "Tehuelche", personas: 4860 },
      { pueblo: "Wichi", personas: 4335 },
      { pueblo: "Ranquel", personas: 3648 },
      { pueblo: "Charrúa", personas: 3626 },
      { pueblo: "Huarpe", personas: 1902 },
      { pueblo: "Moqoit/Mocoví", personas: 1573 },
      { pueblo: "Günün A Küna", personas: 1404 },
      { pueblo: "Tonokoté", personas: 921 },
      { pueblo: "Querandí", personas: 710 },
      { pueblo: "Atacama", personas: 696 },
      { pueblo: "Mbya Guaraní", personas: 560 },
      { pueblo: "Chana", personas: 423 },
      { pueblo: "Guaycurú", personas: 412 },
      { pueblo: "Omaguaca", personas: 407 },
      { pueblo: "Sanavirón", personas: 373 },
      { pueblo: "Diaguita Cacano", personas: 340 },
      { pueblo: "Chicha", personas: 309 },
      { pueblo: "Lule", personas: 301 },
      { pueblo: "Lule Vilela", personas: 297 },
      { pueblo: "Selk´Nam/Ona", personas: 285 },
      { pueblo: "Aoniken", personas: 225 },
      { pueblo: "Avipón", personas: 201 },
      { pueblo: "Chorote", personas: 182 },
      { pueblo: "Chané", personas: 145 },
      { pueblo: "Pilagá", personas: 128 },
      { pueblo: "Vilela", personas: 117 },
      { pueblo: "Corundí", personas: 85 },
      { pueblo: "Guarayo", personas: 70 },
      { pueblo: "Kolla Atacameño", personas: 63 },
      { pueblo: "Ocloya", personas: 49 },
      { pueblo: "Toara", personas: 45 },
      { pueblo: "Chulupí/Nivaclé", personas: 41 },
      { pueblo: "Tastil", personas: 36 },
      { pueblo: "Weenhayek", personas: 28 },
      { pueblo: "Fiscara", personas: 25 },
      { pueblo: "Yagán", personas: 23 },
      { pueblo: "Tapiete", personas: 14 },
      { pueblo: "Tilián", personas: 11 },
      { pueblo: "Iogys", personas: 9 },
      { pueblo: "Jujuí", personas: 9 },
      { pueblo: "Mak'A", personas: 8 },
      { pueblo: "Isoceño", personas: 5 },
      { pueblo: "Minuán", personas: 5 },
      { pueblo: "Wayteca/Chono", personas: 3 },
      { pueblo: "Alakaluf", personas: 2 },
      { pueblo: "Churumata", personas: 2 },
    ],
    departamentos: [
      { departamento: "25 de Mayo", poblacion: 35411, indigena: 572 },
      { departamento: "9 de Julio", poblacion: 52366, indigena: 610 },
      { departamento: "Adolfo Alsina", poblacion: 17344, indigena: 287 },
      { departamento: "Adolfo Gonzales Chaves", poblacion: 12847, indigena: 158 },
      { departamento: "Alberti", poblacion: 12906, indigena: 150 },
      { departamento: "Almirante Brown", poblacion: 583209, indigena: 13343 },
      { departamento: "Arrecifes", poblacion: 32077, indigena: 354 },
      { departamento: "Avellaneda", poblacion: 366117, indigena: 7082 },
      { departamento: "Ayacucho", poblacion: 21757, indigena: 261 },
      { departamento: "Azul", poblacion: 75152, indigena: 1272 },
      { departamento: "Bahía Blanca", poblacion: 334505, indigena: 8030 },
      { departamento: "Balcarce", poblacion: 48516, indigena: 622 },
      { departamento: "Baradero", poblacion: 39223, indigena: 572 },
      { departamento: "Benito Juárez", poblacion: 21185, indigena: 372 },
      { departamento: "Berazategui", poblacion: 358328, indigena: 7663 },
      { departamento: "Berisso", poblacion: 100685, indigena: 2442 },
      { departamento: "Bolívar", poblacion: 37194, indigena: 641 },
      { departamento: "Bragado", poblacion: 46227, indigena: 829 },
      { departamento: "Brandsen", poblacion: 32350, indigena: 522 },
      { departamento: "Campana", poblacion: 107976, indigena: 1567 },
      { departamento: "Cañuelas", poblacion: 70542, indigena: 1531 },
      { departamento: "Capitán Sarmiento", poblacion: 15882, indigena: 258 },
      { departamento: "Carlos Casares", poblacion: 22905, indigena: 304 },
      { departamento: "Carlos Tejedor", poblacion: 14007, indigena: 162 },
      { departamento: "Carmen de Areco", poblacion: 17345, indigena: 233 },
      { departamento: "Castelli", poblacion: 9551, indigena: 87 },
      { departamento: "Chacabuco", poblacion: 52409, indigena: 722 },
      { departamento: "Chascomús", poblacion: 42191, indigena: 674 },
      { departamento: "Chivilcoy", poblacion: 70554, indigena: 682 },
      { departamento: "Colón", poblacion: 27406, indigena: 425 },
      { departamento: "Coronel de Marina Leonardo Rosales", poblacion: 65823, indigena: 1212 },
      { departamento: "Coronel Dorrego", poblacion: 15795, indigena: 247 },
      { departamento: "Coronel Pringles", poblacion: 24110, indigena: 345 },
      { departamento: "Coronel Suárez", poblacion: 41713, indigena: 501 },
      { departamento: "Daireaux", poblacion: 18328, indigena: 189 },
      { departamento: "Dolores", poblacion: 31405, indigena: 336 },
      { departamento: "Ensenada", poblacion: 63978, indigena: 1464 },
      { departamento: "Escobar", poblacion: 256071, indigena: 5471 },
      { departamento: "Esteban Echeverría", poblacion: 337880, indigena: 8869 },
      { departamento: "Exaltación de la Cruz", poblacion: 40036, indigena: 1073 },
      { departamento: "Ezeiza", poblacion: 198620, indigena: 4631 },
      { departamento: "Florencio Varela", poblacion: 488103, indigena: 11370 },
      { departamento: "Florentino Ameghino", poblacion: 10759, indigena: 100 },
      { departamento: "General Alvarado", poblacion: 45307, indigena: 1032 },
      { departamento: "General Alvear", poblacion: 10150, indigena: 122 },
      { departamento: "General Arenales", poblacion: 16231, indigena: 181 },
      { departamento: "General Belgrano", poblacion: 20674, indigena: 317 },
      { departamento: "General Guido", poblacion: 3157, indigena: 39 },
      { departamento: "General Juan Madariaga", poblacion: 22566, indigena: 379 },
      { departamento: "General La Madrid", poblacion: 11535, indigena: 182 },
      { departamento: "General Las Heras", poblacion: 17980, indigena: 327 },
      { departamento: "General Lavalle", poblacion: 4846, indigena: 66 },
      { departamento: "General Paz", poblacion: 14141, indigena: 223 },
      { departamento: "General Pinto", poblacion: 12842, indigena: 108 },
      { departamento: "General Pueyrredón", poblacion: 660569, indigena: 14530 },
      { departamento: "General Rodríguez", poblacion: 142315, indigena: 3472 },
      { departamento: "General San Martín", poblacion: 444503, indigena: 8648 },
      { departamento: "General Viamonte", poblacion: 22530, indigena: 2361 },
      { departamento: "General Villegas", poblacion: 35055, indigena: 433 },
      { departamento: "Guaminí", poblacion: 11662, indigena: 214 },
      { departamento: "Hipólito Yrigoyen", poblacion: 10581, indigena: 81 },
      { departamento: "Hurlingham", poblacion: 185361, indigena: 4279 },
      { departamento: "Ituzaingó", poblacion: 177983, indigena: 3939 },
      { departamento: "José C", poblacion: 326527, indigena: 6127 },
      { departamento: "Junín", poblacion: 100964, indigena: 2337 },
      { departamento: "La Costa", poblacion: 100400, indigena: 2468 },
      { departamento: "La Matanza", poblacion: 1837168, indigena: 46771 },
      { departamento: "La Plata", poblacion: 756074, indigena: 22207 },
      { departamento: "Lanús", poblacion: 460081, indigena: 7407 },
      { departamento: "Laprida", poblacion: 11496, indigena: 149 },
      { departamento: "Las Flores", poblacion: 27136, indigena: 355 },
      { departamento: "Leandro N", poblacion: 17153, indigena: 211 },
      { departamento: "Lezama", poblacion: 6170, indigena: 63 },
      { departamento: "Lincoln", poblacion: 45191, indigena: 490 },
      { departamento: "Lobería", poblacion: 18106, indigena: 243 },
      { departamento: "Lobos", poblacion: 41418, indigena: 430 },
      { departamento: "Lomas de Zamora", poblacion: 685644, indigena: 17643 },
      { departamento: "Luján", poblacion: 110111, indigena: 1888 },
      { departamento: "Magdalena", poblacion: 22653, indigena: 379 },
      { departamento: "Maipú", poblacion: 11253, indigena: 128 },
      { departamento: "Malvinas Argentinas", poblacion: 349401, indigena: 6609 },
      { departamento: "Mar Chiquita", poblacion: 32973, indigena: 771 },
      { departamento: "Marcos Paz", poblacion: 64761, indigena: 1525 },
      { departamento: "Mercedes", poblacion: 71002, indigena: 1149 },
      { departamento: "Merlo", poblacion: 581484, indigena: 14107 },
      { departamento: "Monte", poblacion: 24616, indigena: 363 },
      { departamento: "Monte Hermoso", poblacion: 8444, indigena: 171 },
      { departamento: "Moreno", poblacion: 575758, indigena: 14935 },
      { departamento: "Morón", poblacion: 329517, indigena: 6197 },
      { departamento: "Navarro", poblacion: 19888, indigena: 187 },
      { departamento: "Necochea", poblacion: 101483, indigena: 1810 },
      { departamento: "Olavarría", poblacion: 122011, indigena: 2376 },
      { departamento: "Patagones", poblacion: 37499, indigena: 2539 },
      { departamento: "Pehuajó", poblacion: 44594, indigena: 633 },
      { departamento: "Pellegrini", poblacion: 7112, indigena: 67 },
      { departamento: "Pergamino", poblacion: 114988, indigena: 1546 },
      { departamento: "Pila", poblacion: 4615, indigena: 79 },
      { departamento: "Pilar", poblacion: 393614, indigena: 8564 },
      { departamento: "Pinamar", poblacion: 39224, indigena: 1411 },
      { departamento: "Presidente Perón", poblacion: 101994, indigena: 2586 },
      { departamento: "Puan", poblacion: 16391, indigena: 240 },
      { departamento: "Punta Indio", poblacion: 12161, indigena: 266 },
      { departamento: "Quilmes", poblacion: 631774, indigena: 12890 },
      { departamento: "Ramallo", poblacion: 39648, indigena: 481 },
      { departamento: "Rauch", poblacion: 16491, indigena: 264 },
      { departamento: "Rivadavia", poblacion: 19735, indigena: 321 },
      { departamento: "Rojas", poblacion: 25619, indigena: 349 },
      { departamento: "Roque Pérez", poblacion: 13901, indigena: 155 },
      { departamento: "Saavedra", poblacion: 21407, indigena: 335 },
      { departamento: "Saladillo", poblacion: 35423, indigena: 445 },
      { departamento: "Salliqueló", poblacion: 9344, indigena: 120 },
      { departamento: "Salto", poblacion: 39257, indigena: 488 },
      { departamento: "San Andrés de Giles", poblacion: 26399, indigena: 514 },
      { departamento: "San Antonio de Areco", poblacion: 26695, indigena: 355 },
      { departamento: "San Cayetano", poblacion: 8918, indigena: 98 },
      { departamento: "San Fernando", poblacion: 171099, indigena: 3250 },
      { departamento: "San Isidro", poblacion: 295978, indigena: 3927 },
      { departamento: "San Miguel", poblacion: 327650, indigena: 6673 },
      { departamento: "San Nicolás", poblacion: 166657, indigena: 2219 },
      { departamento: "San Pedro", poblacion: 68353, indigena: 877 },
      { departamento: "San Vicente", poblacion: 97929, indigena: 2146 },
      { departamento: "Suipacha", poblacion: 11736, indigena: 165 },
      { departamento: "Tandil", poblacion: 144678, indigena: 2684 },
      { departamento: "Tapalqué", poblacion: 10695, indigena: 182 },
      { departamento: "Tigre", poblacion: 446291, indigena: 8294 },
      { departamento: "Tordillo", poblacion: 2528, indigena: 22 },
      { departamento: "Tornquist", poblacion: 14591, indigena: 343 },
      { departamento: "Trenque Lauquen", poblacion: 49128, indigena: 1073 },
      { departamento: "Tres Arroyos", poblacion: 61889, indigena: 944 },
      { departamento: "Tres de Febrero", poblacion: 362319, indigena: 7419 },
      { departamento: "Tres Lomas", poblacion: 9090, indigena: 120 },
      { departamento: "Vicente López", poblacion: 280541, indigena: 4021 },
      { departamento: "Villa Gesell", poblacion: 37325, indigena: 1204 },
      { departamento: "Villarino", poblacion: 32552, indigena: 1115 },
      { departamento: "Zárate", poblacion: 131415, indigena: 1742 },
    ],
  },
  {
    provincia: "Catamarca",
    poblacion: 427625,
    indigena: 19668,
    sinInformacion: 6045,
    pueblos: [
      { pueblo: "Diaguita", personas: 11919 },
      { pueblo: "Diaguita Cacano", personas: 351 },
      { pueblo: "Kolla", personas: 290 },
      { pueblo: "Kolla Atacameño", personas: 230 },
      { pueblo: "Quechua", personas: 153 },
      { pueblo: "Mapuche", personas: 108 },
      { pueblo: "Guaraní", personas: 103 },
      { pueblo: "Qom/Toba", personas: 79 },
      { pueblo: "Atacama", personas: 62 },
      { pueblo: "Comechingón", personas: 50 },
      { pueblo: "Omaguaca", personas: 42 },
      { pueblo: "Wichi", personas: 35 },
      { pueblo: "Mapuche Tehuelche", personas: 27 },
      { pueblo: "Tehuelche", personas: 24 },
      { pueblo: "Huarpe", personas: 23 },
      { pueblo: "Tastil", personas: 20 },
      { pueblo: "Aymara", personas: 19 },
      { pueblo: "Ranquel", personas: 13 },
      { pueblo: "Charrúa", personas: 11 },
      { pueblo: "Sanavirón", personas: 10 },
      { pueblo: "Mbya Guaraní", personas: 6 },
      { pueblo: "Tonokoté", personas: 6 },
      { pueblo: "Chané", personas: 4 },
      { pueblo: "Günün A Küna", personas: 4 },
      { pueblo: "Chana", personas: 3 },
      { pueblo: "Chorote", personas: 3 },
      { pueblo: "Lule Vilela", personas: 3 },
      { pueblo: "Moqoit/Mocoví", personas: 3 },
      { pueblo: "Pilagá", personas: 3 },
      { pueblo: "Selk´Nam/Ona", personas: 3 },
      { pueblo: "Aoniken", personas: 2 },
      { pueblo: "Guaycurú", personas: 2 },
      { pueblo: "Lule", personas: 2 },
      { pueblo: "Ocloya", personas: 2 },
      { pueblo: "Querandí", personas: 2 },
      { pueblo: "Avipón", personas: 1 },
      { pueblo: "Chicha", personas: 1 },
      { pueblo: "Corundí", personas: 1 },
      { pueblo: "Jujuí", personas: 1 },
      { pueblo: "Tilián", personas: 1 },
      { pueblo: "Vilela", personas: 1 },
    ],
    departamentos: [
      { departamento: "Ambato", poblacion: 5087, indigena: 165 },
      { departamento: "Ancasti", poblacion: 3282, indigena: 48 },
      { departamento: "Andalgalá", poblacion: 19545, indigena: 1618 },
      { departamento: "Antofagasta de la Sierra", poblacion: 1822, indigena: 313 },
      { departamento: "Belén", poblacion: 30353, indigena: 3564 },
      { departamento: "Capayán", poblacion: 19471, indigena: 455 },
      { departamento: "Capital", poblacion: 186466, indigena: 4049 },
      { departamento: "El Alto", poblacion: 4375, indigena: 37 },
      { departamento: "Fray Mamerto Esquiú", poblacion: 14624, indigena: 334 },
      { departamento: "La Paz", poblacion: 26341, indigena: 274 },
      { departamento: "Paclín", poblacion: 4696, indigena: 87 },
      { departamento: "Pomán", poblacion: 12219, indigena: 942 },
      { departamento: "Santa María", poblacion: 26822, indigena: 5465 },
      { departamento: "Santa Rosa", poblacion: 13317, indigena: 153 },
      { departamento: "Tinogasta", poblacion: 25254, indigena: 1564 },
      { departamento: "Valle Viejo", poblacion: 33951, indigena: 600 },
    ],
  },
  {
    provincia: "Chaco",
    poblacion: 1124603,
    indigena: 53798,
    sinInformacion: 8820,
    pueblos: [
      { pueblo: "Qom/Toba", personas: 32677 },
      { pueblo: "Wichi", personas: 6372 },
      { pueblo: "Moqoit/Mocoví", personas: 4223 },
      { pueblo: "Guaraní", personas: 852 },
      { pueblo: "Diaguita", personas: 173 },
      { pueblo: "Mapuche", personas: 133 },
      { pueblo: "Quechua", personas: 116 },
      { pueblo: "Kolla", personas: 47 },
      { pueblo: "Aymara", personas: 38 },
      { pueblo: "Charrúa", personas: 38 },
      { pueblo: "Vilela", personas: 32 },
      { pueblo: "Atacama", personas: 30 },
      { pueblo: "Guaycurú", personas: 30 },
      { pueblo: "Lule Vilela", personas: 24 },
      { pueblo: "Tehuelche", personas: 21 },
      { pueblo: "Mapuche Tehuelche", personas: 20 },
      { pueblo: "Comechingón", personas: 19 },
      { pueblo: "Avipón", personas: 18 },
      { pueblo: "Ranquel", personas: 18 },
      { pueblo: "Chorote", personas: 16 },
      { pueblo: "Pilagá", personas: 13 },
      { pueblo: "Mbya Guaraní", personas: 7 },
      { pueblo: "Günün A Küna", personas: 6 },
      { pueblo: "Sanavirón", personas: 6 },
      { pueblo: "Chané", personas: 5 },
      { pueblo: "Huarpe", personas: 5 },
      { pueblo: "Aoniken", personas: 4 },
      { pueblo: "Chana", personas: 4 },
      { pueblo: "Tonokoté", personas: 4 },
      { pueblo: "Chicha", personas: 3 },
      { pueblo: "Corundí", personas: 3 },
      { pueblo: "Lule", personas: 3 },
      { pueblo: "Ocloya", personas: 3 },
      { pueblo: "Omaguaca", personas: 3 },
      { pueblo: "Diaguita Cacano", personas: 2 },
      { pueblo: "Fiscara", personas: 2 },
      { pueblo: "Selk´Nam/Ona", personas: 2 },
      { pueblo: "Weenhayek", personas: 2 },
      { pueblo: "Chulupí/Nivaclé", personas: 1 },
      { pueblo: "Guarayo", personas: 1 },
      { pueblo: "Iogys", personas: 1 },
      { pueblo: "Yagán", personas: 1 },
    ],
    departamentos: [
      { departamento: "1° de Mayo", poblacion: 14265, indigena: 317 },
      { departamento: "12 de Octubre", poblacion: 23179, indigena: 273 },
      { departamento: "2 de Abril", poblacion: 8310, indigena: 64 },
      { departamento: "25 de Mayo", poblacion: 32606, indigena: 4625 },
      { departamento: "9 de Julio", poblacion: 30223, indigena: 171 },
      { departamento: "Almirante Brown", poblacion: 37794, indigena: 246 },
      { departamento: "Bermejo", poblacion: 28060, indigena: 1814 },
      { departamento: "Chacabuco", poblacion: 34493, indigena: 1032 },
      { departamento: "Comandante Fernández", poblacion: 101086, indigena: 3731 },
      { departamento: "Fray Justo Santa María de Oro", poblacion: 10643, indigena: 89 },
      { departamento: "General Belgrano", poblacion: 12807, indigena: 84 },
      { departamento: "General Donovan", poblacion: 15061, indigena: 341 },
      { departamento: "General Güemes", poblacion: 68429, indigena: 15031 },
      { departamento: "Independencia", poblacion: 21948, indigena: 130 },
      { departamento: "Libertad", poblacion: 13775, indigena: 488 },
      { departamento: "Libertador General San Martín", poblacion: 65304, indigena: 9588 },
      { departamento: "Maipú", poblacion: 26354, indigena: 931 },
      { departamento: "Mayor Luis J", poblacion: 59798, indigena: 2292 },
      { departamento: "O'Higgins", poblacion: 21544, indigena: 1277 },
      { departamento: "Presidencia de la Plaza", poblacion: 13938, indigena: 109 },
      { departamento: "Quitilipi", poblacion: 32430, indigena: 1345 },
      { departamento: "San Fernando", poblacion: 413764, indigena: 9062 },
      { departamento: "San Lorenzo", poblacion: 16045, indigena: 430 },
      { departamento: "Sargento Cabral", poblacion: 18696, indigena: 125 },
      { departamento: "Tapenagá", poblacion: 4051, indigena: 203 },
    ],
  },
  {
    provincia: "Chubut",
    poblacion: 589454,
    indigena: 46670,
    sinInformacion: 6251,
    pueblos: [
      { pueblo: "Mapuche", personas: 23559 },
      { pueblo: "Mapuche Tehuelche", personas: 7566 },
      { pueblo: "Tehuelche", personas: 4858 },
      { pueblo: "Quechua", personas: 1045 },
      { pueblo: "Guaraní", personas: 727 },
      { pueblo: "Diaguita", personas: 679 },
      { pueblo: "Kolla", personas: 374 },
      { pueblo: "Günün A Küna", personas: 244 },
      { pueblo: "Qom/Toba", personas: 210 },
      { pueblo: "Aoniken", personas: 161 },
      { pueblo: "Ranquel", personas: 148 },
      { pueblo: "Comechingón", personas: 139 },
      { pueblo: "Aymara", personas: 134 },
      { pueblo: "Huarpe", personas: 129 },
      { pueblo: "Wichi", personas: 107 },
      { pueblo: "Charrúa", personas: 61 },
      { pueblo: "Omaguaca", personas: 32 },
      { pueblo: "Moqoit/Mocoví", personas: 30 },
      { pueblo: "Atacama", personas: 29 },
      { pueblo: "Mbya Guaraní", personas: 29 },
      { pueblo: "Selk´Nam/Ona", personas: 24 },
      { pueblo: "Diaguita Cacano", personas: 16 },
      { pueblo: "Tonokoté", personas: 13 },
      { pueblo: "Lule", personas: 10 },
      { pueblo: "Guarayo", personas: 9 },
      { pueblo: "Sanavirón", personas: 9 },
      { pueblo: "Avipón", personas: 8 },
      { pueblo: "Querandí", personas: 8 },
      { pueblo: "Chana", personas: 6 },
      { pueblo: "Chané", personas: 6 },
      { pueblo: "Chicha", personas: 6 },
      { pueblo: "Kolla Atacameño", personas: 6 },
      { pueblo: "Yagán", personas: 6 },
      { pueblo: "Chorote", personas: 5 },
      { pueblo: "Guaycurú", personas: 5 },
      { pueblo: "Pilagá", personas: 4 },
      { pueblo: "Ocloya", personas: 3 },
      { pueblo: "Wayteca/Chono", personas: 3 },
      { pueblo: "Chulupí/Nivaclé", personas: 2 },
      { pueblo: "Corundí", personas: 1 },
      { pueblo: "Fiscara", personas: 1 },
      { pueblo: "Haush/Maneken", personas: 1 },
      { pueblo: "Lule Vilela", personas: 1 },
      { pueblo: "Minuán", personas: 1 },
      { pueblo: "Tapiete", personas: 1 },
      { pueblo: "Tastil", personas: 1 },
      { pueblo: "Tilián", personas: 1 },
      { pueblo: "Toara", personas: 1 },
    ],
    departamentos: [
      { departamento: "Biedma", poblacion: 102806, indigena: 6192 },
      { departamento: "Cushamen", poblacion: 28099, indigena: 5991 },
      { departamento: "Escalante", poblacion: 214829, indigena: 8515 },
      { departamento: "Florentino Ameghino", poblacion: 1782, indigena: 156 },
      { departamento: "Futaleufú", poblacion: 49965, indigena: 7578 },
      { departamento: "Gaiman", poblacion: 12505, indigena: 1229 },
      { departamento: "Gastre", poblacion: 1181, indigena: 405 },
      { departamento: "Languiñeo", poblacion: 2862, indigena: 839 },
      { departamento: "Mártires", poblacion: 744, indigena: 87 },
      { departamento: "Paso de Indios", poblacion: 1882, indigena: 475 },
      { departamento: "Rawson", poblacion: 144420, indigena: 11343 },
      { departamento: "Río Senguer", poblacion: 6347, indigena: 1024 },
      { departamento: "Sarmiento", poblacion: 14477, indigena: 1420 },
      { departamento: "Tehuelches", poblacion: 5947, indigena: 1061 },
      { departamento: "Telsen", poblacion: 1608, indigena: 355 },
    ],
  },
  {
    provincia: "Córdoba",
    poblacion: 3812064,
    indigena: 69218,
    sinInformacion: 29139,
    pueblos: [
      { pueblo: "Comechingón", personas: 16982 },
      { pueblo: "Diaguita", personas: 3251 },
      { pueblo: "Guaraní", personas: 2991 },
      { pueblo: "Mapuche", personas: 2751 },
      { pueblo: "Quechua", personas: 2541 },
      { pueblo: "Ranquel", personas: 1927 },
      { pueblo: "Sanavirón", personas: 1632 },
      { pueblo: "Qom/Toba", personas: 1442 },
      { pueblo: "Kolla", personas: 1362 },
      { pueblo: "Aymara", personas: 772 },
      { pueblo: "Wichi", personas: 748 },
      { pueblo: "Huarpe", personas: 676 },
      { pueblo: "Tehuelche", personas: 495 },
      { pueblo: "Mapuche Tehuelche", personas: 483 },
      { pueblo: "Charrúa", personas: 325 },
      { pueblo: "Moqoit/Mocoví", personas: 313 },
      { pueblo: "Omaguaca", personas: 176 },
      { pueblo: "Atacama", personas: 148 },
      { pueblo: "Günün A Küna", personas: 135 },
      { pueblo: "Diaguita Cacano", personas: 95 },
      { pueblo: "Tonokoté", personas: 95 },
      { pueblo: "Chana", personas: 79 },
      { pueblo: "Chicha", personas: 79 },
      { pueblo: "Avipón", personas: 68 },
      { pueblo: "Selk´Nam/Ona", personas: 63 },
      { pueblo: "Chorote", personas: 59 },
      { pueblo: "Mbya Guaraní", personas: 53 },
      { pueblo: "Lule", personas: 49 },
      { pueblo: "Aoniken", personas: 41 },
      { pueblo: "Chané", personas: 39 },
      { pueblo: "Corundí", personas: 28 },
      { pueblo: "Querandí", personas: 26 },
      { pueblo: "Guaycurú", personas: 22 },
      { pueblo: "Ocloya", personas: 22 },
      { pueblo: "Pilagá", personas: 18 },
      { pueblo: "Chulupí/Nivaclé", personas: 17 },
      { pueblo: "Lule Vilela", personas: 13 },
      { pueblo: "Kolla Atacameño", personas: 9 },
      { pueblo: "Tilián", personas: 9 },
      { pueblo: "Toara", personas: 9 },
      { pueblo: "Guarayo", personas: 7 },
      { pueblo: "Vilela", personas: 7 },
      { pueblo: "Tastil", personas: 5 },
      { pueblo: "Yagán", personas: 5 },
      { pueblo: "Fiscara", personas: 3 },
      { pueblo: "Wayteca/Chono", personas: 2 },
      { pueblo: "Weenhayek", personas: 2 },
      { pueblo: "Iogys", personas: 1 },
      { pueblo: "Isoceño", personas: 1 },
      { pueblo: "Jujuí", personas: 1 },
      { pueblo: "Michilingüe", personas: 1 },
      { pueblo: "Tapiete", personas: 1 },
    ],
    departamentos: [
      { departamento: "Calamuchita", poblacion: 75462, indigena: 2034 },
      { departamento: "Capital", poblacion: 1498060, indigena: 27961 },
      { departamento: "Colón", poblacion: 294511, indigena: 6513 },
      { departamento: "Cruz del Eje", poblacion: 64748, indigena: 2354 },
      { departamento: "General Roca", poblacion: 36064, indigena: 672 },
      { departamento: "General San Martín", poblacion: 152397, indigena: 2084 },
      { departamento: "Ischilín", poblacion: 36023, indigena: 688 },
      { departamento: "Juárez Celman", poblacion: 68317, indigena: 830 },
      { departamento: "Marcos Juárez", poblacion: 107286, indigena: 884 },
      { departamento: "Minas", poblacion: 4855, indigena: 158 },
      { departamento: "Pocho", poblacion: 5070, indigena: 140 },
      { departamento: "Presidente Roque Sáenz Peña", poblacion: 37551, indigena: 459 },
      { departamento: "Punilla", poblacion: 219494, indigena: 6382 },
      { departamento: "Río Cuarto", poblacion: 277979, indigena: 4951 },
      { departamento: "Río Primero", poblacion: 58181, indigena: 553 },
      { departamento: "Río Seco", poblacion: 15275, indigena: 210 },
      { departamento: "Río Segundo", poblacion: 113311, indigena: 1193 },
      { departamento: "San Alberto", poblacion: 42029, indigena: 1334 },
      { departamento: "San Javier", poblacion: 62700, indigena: 1840 },
      { departamento: "San Justo", poblacion: 228951, indigena: 1906 },
      { departamento: "Santa María", poblacion: 139012, indigena: 2829 },
      { departamento: "Sobremonte", poblacion: 4381, indigena: 22 },
      { departamento: "Tercero Arriba", poblacion: 120207, indigena: 1636 },
      { departamento: "Totoral", poblacion: 22473, indigena: 338 },
      { departamento: "Tulumba", poblacion: 14092, indigena: 216 },
      { departamento: "Unión", poblacion: 113635, indigena: 1031 },
    ],
  },
  {
    provincia: "Corrientes",
    poblacion: 1209671,
    indigena: 15808,
    sinInformacion: 5878,
    pueblos: [
      { pueblo: "Guaraní", personas: 8259 },
      { pueblo: "Qom/Toba", personas: 557 },
      { pueblo: "Charrúa", personas: 158 },
      { pueblo: "Mapuche", personas: 135 },
      { pueblo: "Wichi", personas: 107 },
      { pueblo: "Guaycurú", personas: 99 },
      { pueblo: "Quechua", personas: 97 },
      { pueblo: "Kolla", personas: 58 },
      { pueblo: "Aymara", personas: 57 },
      { pueblo: "Diaguita", personas: 55 },
      { pueblo: "Moqoit/Mocoví", personas: 52 },
      { pueblo: "Mbya Guaraní", personas: 44 },
      { pueblo: "Atacama", personas: 37 },
      { pueblo: "Tehuelche", personas: 32 },
      { pueblo: "Mapuche Tehuelche", personas: 29 },
      { pueblo: "Comechingón", personas: 21 },
      { pueblo: "Chana", personas: 19 },
      { pueblo: "Avipón", personas: 13 },
      { pueblo: "Chicha", personas: 12 },
      { pueblo: "Ranquel", personas: 12 },
      { pueblo: "Chorote", personas: 10 },
      { pueblo: "Pilagá", personas: 10 },
      { pueblo: "Huarpe", personas: 9 },
      { pueblo: "Guarayo", personas: 7 },
      { pueblo: "Aoniken", personas: 6 },
      { pueblo: "Chané", personas: 6 },
      { pueblo: "Ocloya", personas: 5 },
      { pueblo: "Chulupí/Nivaclé", personas: 3 },
      { pueblo: "Fiscara", personas: 3 },
      { pueblo: "Günün A Küna", personas: 3 },
      { pueblo: "Toara", personas: 3 },
      { pueblo: "Diaguita Cacano", personas: 2 },
      { pueblo: "Vilela", personas: 2 },
      { pueblo: "Corundí", personas: 1 },
      { pueblo: "Isoceño", personas: 1 },
      { pueblo: "Lule", personas: 1 },
      { pueblo: "Omaguaca", personas: 1 },
      { pueblo: "Sanavirón", personas: 1 },
      { pueblo: "Selk´Nam/Ona", personas: 1 },
      { pueblo: "Tilián", personas: 1 },
      { pueblo: "Tonokoté", personas: 1 },
    ],
    departamentos: [
      { departamento: "Bella Vista", poblacion: 44369, indigena: 453 },
      { departamento: "Berón de Astrada", poblacion: 2808, indigena: 105 },
      { departamento: "Capital", poblacion: 437446, indigena: 5875 },
      { departamento: "Concepción", poblacion: 26270, indigena: 441 },
      { departamento: "Curuzú Cuatiá", poblacion: 51489, indigena: 535 },
      { departamento: "Empedrado", poblacion: 17948, indigena: 266 },
      { departamento: "Esquina", poblacion: 39168, indigena: 363 },
      { departamento: "General Alvear", poblacion: 9051, indigena: 87 },
      { departamento: "General Paz", poblacion: 17016, indigena: 229 },
      { departamento: "Goya", poblacion: 106223, indigena: 1013 },
      { departamento: "Itatí", poblacion: 11946, indigena: 198 },
      { departamento: "Ituzaingó", poblacion: 38767, indigena: 855 },
      { departamento: "Lavalle", poblacion: 40406, indigena: 407 },
      { departamento: "Mburucuyá", poblacion: 11541, indigena: 129 },
      { departamento: "Mercedes", poblacion: 49807, indigena: 551 },
      { departamento: "Monte Caseros", poblacion: 45602, indigena: 547 },
      { departamento: "Paso de los Libres", poblacion: 56778, indigena: 709 },
      { departamento: "Saladas", poblacion: 29126, indigena: 283 },
      { departamento: "San Cosme", poblacion: 19679, indigena: 345 },
      { departamento: "San Luis del Palmar", poblacion: 21381, indigena: 302 },
      { departamento: "San Martín", poblacion: 15164, indigena: 256 },
      { departamento: "San Miguel", poblacion: 12700, indigena: 714 },
      { departamento: "San Roque", poblacion: 22682, indigena: 200 },
      { departamento: "Santo Tomé", poblacion: 71922, indigena: 856 },
      { departamento: "Sauce", poblacion: 10382, indigena: 89 },
    ],
  },
  {
    provincia: "Entre Ríos",
    poblacion: 1415097,
    indigena: 18693,
    sinInformacion: 9707,
    pueblos: [
      { pueblo: "Charrúa", personas: 3031 },
      { pueblo: "Guaraní", personas: 2632 },
      { pueblo: "Chana", personas: 528 },
      { pueblo: "Mapuche", personas: 505 },
      { pueblo: "Qom/Toba", personas: 494 },
      { pueblo: "Moqoit/Mocoví", personas: 241 },
      { pueblo: "Diaguita", personas: 213 },
      { pueblo: "Quechua", personas: 195 },
      { pueblo: "Aymara", personas: 161 },
      { pueblo: "Comechingón", personas: 150 },
      { pueblo: "Wichi", personas: 137 },
      { pueblo: "Tehuelche", personas: 103 },
      { pueblo: "Kolla", personas: 97 },
      { pueblo: "Mapuche Tehuelche", personas: 66 },
      { pueblo: "Huarpe", personas: 58 },
      { pueblo: "Ranquel", personas: 46 },
      { pueblo: "Guaycurú", personas: 44 },
      { pueblo: "Minuán", personas: 43 },
      { pueblo: "Atacama", personas: 27 },
      { pueblo: "Günün A Küna", personas: 24 },
      { pueblo: "Mbya Guaraní", personas: 24 },
      { pueblo: "Avipón", personas: 21 },
      { pueblo: "Querandí", personas: 19 },
      { pueblo: "Chané", personas: 17 },
      { pueblo: "Chicha", personas: 16 },
      { pueblo: "Selk´Nam/Ona", personas: 13 },
      { pueblo: "Chorote", personas: 12 },
      { pueblo: "Omaguaca", personas: 11 },
      { pueblo: "Aoniken", personas: 10 },
      { pueblo: "Lule", personas: 10 },
      { pueblo: "Pilagá", personas: 7 },
      { pueblo: "Corundí", personas: 6 },
      { pueblo: "Diaguita Cacano", personas: 4 },
      { pueblo: "Lule Vilela", personas: 4 },
      { pueblo: "Guarayo", personas: 3 },
      { pueblo: "Sanavirón", personas: 3 },
      { pueblo: "Tonokoté", personas: 3 },
      { pueblo: "Weenhayek", personas: 2 },
      { pueblo: "Yagán", personas: 2 },
      { pueblo: "Fiscara", personas: 1 },
      { pueblo: "Tilián", personas: 1 },
      { pueblo: "Toara", personas: 1 },
      { pueblo: "Vilela", personas: 1 },
    ],
    departamentos: [
      { departamento: "Colón", poblacion: 74890, indigena: 1062 },
      { departamento: "Concordia", poblacion: 197603, indigena: 2577 },
      { departamento: "Diamante", poblacion: 52312, indigena: 693 },
      { departamento: "Federación", poblacion: 78264, indigena: 966 },
      { departamento: "Federal", poblacion: 29436, indigena: 347 },
      { departamento: "Feliciano", poblacion: 16717, indigena: 166 },
      { departamento: "Gualeguay", poblacion: 56796, indigena: 635 },
      { departamento: "Gualeguaychú", poblacion: 125176, indigena: 1418 },
      { departamento: "Islas del Ibicuy", poblacion: 13984, indigena: 218 },
      { departamento: "La Paz", poblacion: 75271, indigena: 944 },
      { departamento: "Nogoyá", poblacion: 42954, indigena: 420 },
      { departamento: "Paraná", poblacion: 388716, indigena: 5608 },
      { departamento: "San Salvador", poblacion: 20786, indigena: 204 },
      { departamento: "Tala", poblacion: 31091, indigena: 677 },
      { departamento: "Uruguay", poblacion: 115516, indigena: 1413 },
      { departamento: "Victoria", poblacion: 40301, indigena: 433 },
      { departamento: "Villaguay", poblacion: 55284, indigena: 912 },
    ],
  },
  {
    provincia: "Formosa",
    poblacion: 605507,
    indigena: 47459,
    sinInformacion: 3094,
    pueblos: [
      { pueblo: "Wichi", personas: 22321 },
      { pueblo: "Qom/Toba", personas: 14870 },
      { pueblo: "Pilagá", personas: 5833 },
      { pueblo: "Guaraní", personas: 594 },
      { pueblo: "Chulupí/Nivaclé", personas: 450 },
      { pueblo: "Quechua", personas: 41 },
      { pueblo: "Mapuche", personas: 35 },
      { pueblo: "Kolla", personas: 33 },
      { pueblo: "Diaguita", personas: 28 },
      { pueblo: "Chana", personas: 26 },
      { pueblo: "Charrúa", personas: 15 },
      { pueblo: "Chicha", personas: 14 },
      { pueblo: "Tehuelche", personas: 14 },
      { pueblo: "Comechingón", personas: 9 },
      { pueblo: "Mbya Guaraní", personas: 9 },
      { pueblo: "Aymara", personas: 8 },
      { pueblo: "Guaycurú", personas: 8 },
      { pueblo: "Mapuche Tehuelche", personas: 8 },
      { pueblo: "Ranquel", personas: 8 },
      { pueblo: "Chorote", personas: 6 },
      { pueblo: "Moqoit/Mocoví", personas: 6 },
      { pueblo: "Avipón", personas: 5 },
      { pueblo: "Atacama", personas: 3 },
      { pueblo: "Selk´Nam/Ona", personas: 3 },
      { pueblo: "Toara", personas: 3 },
      { pueblo: "Weenhayek", personas: 3 },
      { pueblo: "Guarayo", personas: 2 },
      { pueblo: "Mak'A", personas: 2 },
      { pueblo: "Omaguaca", personas: 2 },
      { pueblo: "Yagán", personas: 2 },
      { pueblo: "Chané", personas: 1 },
      { pueblo: "Huarpe", personas: 1 },
      { pueblo: "Sanavirón", personas: 1 },
      { pueblo: "Tapiete", personas: 1 },
    ],
    departamentos: [
      { departamento: "Bermejo", poblacion: 15600, indigena: 4841 },
      { departamento: "Formosa", poblacion: 268572, indigena: 5295 },
      { departamento: "Laishi", poblacion: 19275, indigena: 1631 },
      { departamento: "Matacos", poblacion: 17017, indigena: 5280 },
      { departamento: "Patiño", poblacion: 81600, indigena: 11167 },
      { departamento: "Pilagás", poblacion: 19089, indigena: 1181 },
      { departamento: "Pilcomayo", poblacion: 94116, indigena: 3773 },
      { departamento: "Pirané", poblacion: 72560, indigena: 1758 },
      { departamento: "Ramón Lista", poblacion: 17678, indigena: 12533 },
    ],
  },
  {
    provincia: "Jujuy",
    poblacion: 809364,
    indigena: 81538,
    sinInformacion: 18495,
    pueblos: [
      { pueblo: "Kolla", personas: 32276 },
      { pueblo: "Omaguaca", personas: 9173 },
      { pueblo: "Guaraní", personas: 7522 },
      { pueblo: "Atacama", personas: 3960 },
      { pueblo: "Quechua", personas: 3492 },
      { pueblo: "Diaguita", personas: 1628 },
      { pueblo: "Ocloya", personas: 1621 },
      { pueblo: "Aymara", personas: 729 },
      { pueblo: "Wichi", personas: 584 },
      { pueblo: "Tilián", personas: 391 },
      { pueblo: "Chicha", personas: 283 },
      { pueblo: "Toara", personas: 212 },
      { pueblo: "Fiscara", personas: 207 },
      { pueblo: "Mapuche", personas: 195 },
      { pueblo: "Qom/Toba", personas: 188 },
      { pueblo: "Mbya Guaraní", personas: 88 },
      { pueblo: "Kolla Atacameño", personas: 73 },
      { pueblo: "Comechingón", personas: 50 },
      { pueblo: "Churumata", personas: 42 },
      { pueblo: "Guaycurú", personas: 33 },
      { pueblo: "Chané", personas: 29 },
      { pueblo: "Jujuí", personas: 29 },
      { pueblo: "Chorote", personas: 28 },
      { pueblo: "Tehuelche", personas: 25 },
      { pueblo: "Lule", personas: 22 },
      { pueblo: "Moqoit/Mocoví", personas: 21 },
      { pueblo: "Charrúa", personas: 15 },
      { pueblo: "Sanavirón", personas: 14 },
      { pueblo: "Ranquel", personas: 13 },
      { pueblo: "Pilagá", personas: 12 },
      { pueblo: "Huarpe", personas: 11 },
      { pueblo: "Mapuche Tehuelche", personas: 11 },
      { pueblo: "Chulupí/Nivaclé", personas: 10 },
      { pueblo: "Diaguita Cacano", personas: 10 },
      { pueblo: "Tastil", personas: 9 },
      { pueblo: "Lule Vilela", personas: 7 },
      { pueblo: "Aoniken", personas: 5 },
      { pueblo: "Chana", personas: 4 },
      { pueblo: "Günün A Küna", personas: 4 },
      { pueblo: "Tonokoté", personas: 4 },
      { pueblo: "Avipón", personas: 3 },
      { pueblo: "Guarayo", personas: 3 },
      { pueblo: "Iogys", personas: 3 },
      { pueblo: "Querandí", personas: 1 },
      { pueblo: "Selk´Nam/Ona", personas: 1 },
      { pueblo: "Vilela", personas: 1 },
      { pueblo: "Weenhayek", personas: 1 },
    ],
    departamentos: [
      { departamento: "Cochinoca", poblacion: 14998, indigena: 8098 },
      { departamento: "Dr", poblacion: 319469, indigena: 21417 },
      { departamento: "El Carmen", poblacion: 122259, indigena: 3876 },
      { departamento: "Humahuaca", poblacion: 20877, indigena: 8774 },
      { departamento: "Ledesma", poblacion: 94132, indigena: 6845 },
      { departamento: "Palpalá", poblacion: 65522, indigena: 4464 },
      { departamento: "Rinconada", poblacion: 1797, indigena: 1240 },
      { departamento: "San Antonio", poblacion: 6729, indigena: 309 },
      { departamento: "San Pedro", poblacion: 88237, indigena: 3779 },
      { departamento: "Santa Bárbara", poblacion: 20497, indigena: 2111 },
      { departamento: "Santa Catalina", poblacion: 2641, indigena: 1615 },
      { departamento: "Susques", poblacion: 3966, indigena: 3223 },
      { departamento: "Tilcara", poblacion: 14621, indigena: 4510 },
      { departamento: "Tumbaya", poblacion: 5298, indigena: 2700 },
      { departamento: "Valle Grande", poblacion: 2490, indigena: 1185 },
      { departamento: "Yavi", poblacion: 25831, indigena: 7392 },
    ],
  },
  {
    provincia: "La Pampa",
    poblacion: 359193,
    indigena: 15659,
    sinInformacion: 5995,
    pueblos: [
      { pueblo: "Ranquel", personas: 5326 },
      { pueblo: "Mapuche", personas: 2474 },
      { pueblo: "Mapuche Tehuelche", personas: 416 },
      { pueblo: "Guaraní", personas: 342 },
      { pueblo: "Tehuelche", personas: 253 },
      { pueblo: "Diaguita", personas: 119 },
      { pueblo: "Quechua", personas: 119 },
      { pueblo: "Comechingón", personas: 92 },
      { pueblo: "Huarpe", personas: 84 },
      { pueblo: "Qom/Toba", personas: 76 },
      { pueblo: "Wichi", personas: 59 },
      { pueblo: "Aymara", personas: 56 },
      { pueblo: "Kolla", personas: 56 },
      { pueblo: "Charrúa", personas: 52 },
      { pueblo: "Günün A Küna", personas: 40 },
      { pueblo: "Atacama", personas: 21 },
      { pueblo: "Aoniken", personas: 17 },
      { pueblo: "Mbya Guaraní", personas: 12 },
      { pueblo: "Moqoit/Mocoví", personas: 9 },
      { pueblo: "Avipón", personas: 7 },
      { pueblo: "Chicha", personas: 7 },
      { pueblo: "Guaycurú", personas: 4 },
      { pueblo: "Chorote", personas: 3 },
      { pueblo: "Lule", personas: 3 },
      { pueblo: "Sanavirón", personas: 3 },
      { pueblo: "Ocloya", personas: 2 },
      { pueblo: "Omaguaca", personas: 2 },
      { pueblo: "Querandí", personas: 2 },
      { pueblo: "Chana", personas: 1 },
      { pueblo: "Chané", personas: 1 },
      { pueblo: "Chulupí/Nivaclé", personas: 1 },
      { pueblo: "Corundí", personas: 1 },
      { pueblo: "Diaguita Cacano", personas: 1 },
      { pueblo: "Lule Vilela", personas: 1 },
      { pueblo: "Vilela", personas: 1 },
      { pueblo: "Yagán", personas: 1 },
    ],
    departamentos: [
      { departamento: "Atreucó", poblacion: 11053, indigena: 253 },
      { departamento: "Caleu Caleu", poblacion: 2611, indigena: 77 },
      { departamento: "Capital", poblacion: 118504, indigena: 5727 },
      { departamento: "Catriló", poblacion: 8225, indigena: 160 },
      { departamento: "Chalileo", poblacion: 2868, indigena: 966 },
      { departamento: "Chapaleufú", poblacion: 12277, indigena: 281 },
      { departamento: "Chical Co", poblacion: 1461, indigena: 290 },
      { departamento: "Conhelo", poblacion: 15094, indigena: 358 },
      { departamento: "Curacó", poblacion: 1103, indigena: 85 },
      { departamento: "Guatraché", poblacion: 9397, indigena: 186 },
      { departamento: "Hucal", poblacion: 7713, indigena: 162 },
      { departamento: "Lihuel Calel", poblacion: 428, indigena: 14 },
      { departamento: "Limay Mahuida", poblacion: 413, indigena: 49 },
      { departamento: "Loventué", poblacion: 9243, indigena: 881 },
      { departamento: "Maracó", poblacion: 69067, indigena: 2036 },
      { departamento: "Puelén", poblacion: 11636, indigena: 714 },
      { departamento: "Quemú Quemú", poblacion: 8404, indigena: 178 },
      { departamento: "Rancul", poblacion: 11090, indigena: 387 },
      { departamento: "Realicó", poblacion: 17356, indigena: 575 },
      { departamento: "Toay", poblacion: 17927, indigena: 896 },
      { departamento: "Trenel", poblacion: 5637, indigena: 131 },
      { departamento: "Utracán", poblacion: 17686, indigena: 1253 },
    ],
  },
  {
    provincia: "La Rioja",
    poblacion: 382453,
    indigena: 10645,
    sinInformacion: 4928,
    pueblos: [
      { pueblo: "Diaguita", personas: 4285 },
      { pueblo: "Quechua", personas: 244 },
      { pueblo: "Diaguita Cacano", personas: 229 },
      { pueblo: "Guaraní", personas: 165 },
      { pueblo: "Mapuche", personas: 158 },
      { pueblo: "Kolla", personas: 137 },
      { pueblo: "Comechingón", personas: 115 },
      { pueblo: "Huarpe", personas: 94 },
      { pueblo: "Aymara", personas: 53 },
      { pueblo: "Qom/Toba", personas: 40 },
      { pueblo: "Atacama", personas: 33 },
      { pueblo: "Tehuelche", personas: 30 },
      { pueblo: "Wichi", personas: 30 },
      { pueblo: "Charrúa", personas: 16 },
      { pueblo: "Omaguaca", personas: 12 },
      { pueblo: "Ranquel", personas: 12 },
      { pueblo: "Mapuche Tehuelche", personas: 11 },
      { pueblo: "Tastil", personas: 8 },
      { pueblo: "Chicha", personas: 6 },
      { pueblo: "Chana", personas: 4 },
      { pueblo: "Corundí", personas: 4 },
      { pueblo: "Lule Vilela", personas: 4 },
      { pueblo: "Sanavirón", personas: 4 },
      { pueblo: "Günün A Küna", personas: 3 },
      { pueblo: "Moqoit/Mocoví", personas: 3 },
      { pueblo: "Avipón", personas: 2 },
      { pueblo: "Guaycurú", personas: 2 },
      { pueblo: "Lule", personas: 2 },
      { pueblo: "Selk´Nam/Ona", personas: 2 },
      { pueblo: "Vilela", personas: 2 },
      { pueblo: "Aoniken", personas: 1 },
      { pueblo: "Chané", personas: 1 },
      { pueblo: "Chorote", personas: 1 },
      { pueblo: "Kolla Atacameño", personas: 1 },
      { pueblo: "Ocloya", personas: 1 },
      { pueblo: "Tilián", personas: 1 },
      { pueblo: "Tonokoté", personas: 1 },
    ],
    departamentos: [
      { departamento: "Arauco", poblacion: 16251, indigena: 378 },
      { departamento: "Capital", poblacion: 210507, indigena: 5081 },
      { departamento: "Castro Barros", poblacion: 5810, indigena: 377 },
      { departamento: "Chamical", poblacion: 15630, indigena: 332 },
      { departamento: "Chilecito", poblacion: 58681, indigena: 2053 },
      { departamento: "Famatina", poblacion: 6984, indigena: 468 },
      { departamento: "General Ángel V", poblacion: 3184, indigena: 59 },
      { departamento: "General Belgrano", poblacion: 7615, indigena: 157 },
      { departamento: "General Felipe Varela", poblacion: 11371, indigena: 521 },
      { departamento: "General Juan Facundo Quiroga", poblacion: 4013, indigena: 38 },
      { departamento: "General Lamadrid", poblacion: 1885, indigena: 85 },
      { departamento: "General Ortiz de Ocampo", poblacion: 7347, indigena: 103 },
      { departamento: "General San Martín", poblacion: 5017, indigena: 46 },
      { departamento: "Independencia", poblacion: 2399, indigena: 70 },
      { departamento: "Rosario Vera Peñaloza", poblacion: 15764, indigena: 158 },
      { departamento: "San Blas de los Sauces", poblacion: 4306, indigena: 301 },
      { departamento: "Sanagasta", poblacion: 2994, indigena: 317 },
      { departamento: "Vinchina", poblacion: 2695, indigena: 101 },
    ],
  },
  {
    provincia: "Mendoza",
    poblacion: 2030773,
    indigena: 45389,
    sinInformacion: 19180,
    pueblos: [
      { pueblo: "Huarpe", personas: 13467 },
      { pueblo: "Mapuche", personas: 4481 },
      { pueblo: "Quechua", personas: 3148 },
      { pueblo: "Kolla", personas: 1088 },
      { pueblo: "Diaguita", personas: 723 },
      { pueblo: "Guaraní", personas: 646 },
      { pueblo: "Comechingón", personas: 439 },
      { pueblo: "Mapuche Tehuelche", personas: 356 },
      { pueblo: "Aymara", personas: 341 },
      { pueblo: "Ranquel", personas: 316 },
      { pueblo: "Tehuelche", personas: 292 },
      { pueblo: "Qom/Toba", personas: 230 },
      { pueblo: "Wichi", personas: 182 },
      { pueblo: "Atacama", personas: 72 },
      { pueblo: "Charrúa", personas: 66 },
      { pueblo: "Omaguaca", personas: 45 },
      { pueblo: "Moqoit/Mocoví", personas: 40 },
      { pueblo: "Chicha", personas: 38 },
      { pueblo: "Günün A Küna", personas: 30 },
      { pueblo: "Selk´Nam/Ona", personas: 20 },
      { pueblo: "Diaguita Cacano", personas: 17 },
      { pueblo: "Aoniken", personas: 16 },
      { pueblo: "Chorote", personas: 16 },
      { pueblo: "Sanavirón", personas: 16 },
      { pueblo: "Chana", personas: 15 },
      { pueblo: "Chané", personas: 14 },
      { pueblo: "Guaycurú", personas: 12 },
      { pueblo: "Avipón", personas: 10 },
      { pueblo: "Querandí", personas: 9 },
      { pueblo: "Guarayo", personas: 7 },
      { pueblo: "Lule", personas: 7 },
      { pueblo: "Kolla Atacameño", personas: 6 },
      { pueblo: "Lule Vilela", personas: 6 },
      { pueblo: "Tonokoté", personas: 5 },
      { pueblo: "Weenhayek", personas: 5 },
      { pueblo: "Chulupí/Nivaclé", personas: 3 },
      { pueblo: "Corundí", personas: 3 },
      { pueblo: "Mbya Guaraní", personas: 3 },
      { pueblo: "Ocloya", personas: 3 },
      { pueblo: "Michilingüe", personas: 2 },
      { pueblo: "Minuán", personas: 2 },
      { pueblo: "Pilagá", personas: 2 },
      { pueblo: "Toara", personas: 2 },
      { pueblo: "Yagán", personas: 2 },
      { pueblo: "Ansilta", personas: 1 },
      { pueblo: "Churumata", personas: 1 },
      { pueblo: "Fiscara", personas: 1 },
      { pueblo: "Iogys", personas: 1 },
      { pueblo: "Tastil", personas: 1 },
      { pueblo: "Vilela", personas: 1 },
    ],
    departamentos: [
      { departamento: "Capital", poblacion: 123715, indigena: 2551 },
      { departamento: "General Alvear", poblacion: 52379, indigena: 1008 },
      { departamento: "Godoy Cruz", poblacion: 194557, indigena: 3215 },
      { departamento: "Guaymallén", poblacion: 320871, indigena: 7371 },
      { departamento: "Junín", poblacion: 46472, indigena: 790 },
      { departamento: "La Paz", poblacion: 12018, indigena: 242 },
      { departamento: "Las Heras", poblacion: 233839, indigena: 5379 },
      { departamento: "Lavalle", poblacion: 47086, indigena: 4895 },
      { departamento: "Luján de Cuyo", poblacion: 171883, indigena: 3828 },
      { departamento: "Maipú", poblacion: 218887, indigena: 4230 },
      { departamento: "Malargüe", poblacion: 32596, indigena: 1003 },
      { departamento: "Rivadavia", poblacion: 63589, indigena: 962 },
      { departamento: "San Carlos", poblacion: 39752, indigena: 1098 },
      { departamento: "San Martín", poblacion: 139406, indigena: 2411 },
      { departamento: "San Rafael", poblacion: 213204, indigena: 3630 },
      { departamento: "Santa Rosa", poblacion: 19379, indigena: 401 },
      { departamento: "Tunuyán", poblacion: 59972, indigena: 1112 },
      { departamento: "Tupungato", poblacion: 41168, indigena: 1263 },
    ],
  },
  {
    provincia: "Misiones",
    poblacion: 1273347,
    indigena: 26006,
    sinInformacion: 6624,
    pueblos: [
      { pueblo: "Mbya Guaraní", personas: 9957 },
      { pueblo: "Guaraní", personas: 8372 },
      { pueblo: "Mapuche", personas: 200 },
      { pueblo: "Qom/Toba", personas: 147 },
      { pueblo: "Diaguita", personas: 118 },
      { pueblo: "Quechua", personas: 78 },
      { pueblo: "Charrúa", personas: 61 },
      { pueblo: "Kolla", personas: 59 },
      { pueblo: "Comechingón", personas: 51 },
      { pueblo: "Wichi", personas: 41 },
      { pueblo: "Tehuelche", personas: 38 },
      { pueblo: "Moqoit/Mocoví", personas: 33 },
      { pueblo: "Atacama", personas: 28 },
      { pueblo: "Aymara", personas: 24 },
      { pueblo: "Chana", personas: 23 },
      { pueblo: "Mapuche Tehuelche", personas: 20 },
      { pueblo: "Huarpe", personas: 17 },
      { pueblo: "Ranquel", personas: 17 },
      { pueblo: "Guaycurú", personas: 14 },
      { pueblo: "Chicha", personas: 9 },
      { pueblo: "Avipón", personas: 8 },
      { pueblo: "Selk´Nam/Ona", personas: 7 },
      { pueblo: "Aoniken", personas: 6 },
      { pueblo: "Chorote", personas: 6 },
      { pueblo: "Chané", personas: 5 },
      { pueblo: "Tastil", personas: 5 },
      { pueblo: "Chulupí/Nivaclé", personas: 4 },
      { pueblo: "Günün A Küna", personas: 4 },
      { pueblo: "Sanavirón", personas: 4 },
      { pueblo: "Tonokoté", personas: 4 },
      { pueblo: "Diaguita Cacano", personas: 3 },
      { pueblo: "Guarayo", personas: 3 },
      { pueblo: "Lule", personas: 3 },
      { pueblo: "Lule Vilela", personas: 3 },
      { pueblo: "Kolla Atacameño", personas: 2 },
      { pueblo: "Omaguaca", personas: 2 },
      { pueblo: "Pilagá", personas: 2 },
      { pueblo: "Corundí", personas: 1 },
      { pueblo: "Fiscara", personas: 1 },
      { pueblo: "Mak'A", personas: 1 },
      { pueblo: "Querandí", personas: 1 },
    ],
    departamentos: [
      { departamento: "25 de Mayo", poblacion: 30877, indigena: 591 },
      { departamento: "Apóstoles", poblacion: 50503, indigena: 457 },
      { departamento: "Cainguás", poblacion: 59875, indigena: 867 },
      { departamento: "Candelaria", poblacion: 34945, indigena: 797 },
      { departamento: "Capital", poblacion: 391498, indigena: 5812 },
      { departamento: "Concepción", poblacion: 10303, indigena: 227 },
      { departamento: "Eldorado", poblacion: 91133, indigena: 1673 },
      { departamento: "General Manuel Belgrano", poblacion: 45456, indigena: 743 },
      { departamento: "Guaraní", poblacion: 77075, indigena: 1971 },
      { departamento: "Iguazú", poblacion: 99838, indigena: 3617 },
      { departamento: "Leandro N", poblacion: 49391, indigena: 388 },
      { departamento: "Libertador General San Martín", poblacion: 52166, indigena: 3751 },
      { departamento: "Montecarlo", poblacion: 38620, indigena: 748 },
      { departamento: "Oberá", poblacion: 120703, indigena: 1058 },
      { departamento: "San Ignacio", poblacion: 63194, indigena: 1797 },
      { departamento: "San Javier", poblacion: 23080, indigena: 146 },
      { departamento: "San Pedro", poblacion: 34690, indigena: 1363 },
    ],
  },
  {
    provincia: "Neuquén",
    poblacion: 708578,
    indigena: 54436,
    sinInformacion: 7357,
    pueblos: [
      { pueblo: "Mapuche", personas: 39976 },
      { pueblo: "Mapuche Tehuelche", personas: 2657 },
      { pueblo: "Tehuelche", personas: 923 },
      { pueblo: "Guaraní", personas: 741 },
      { pueblo: "Quechua", personas: 698 },
      { pueblo: "Diaguita", personas: 429 },
      { pueblo: "Kolla", personas: 316 },
      { pueblo: "Huarpe", personas: 200 },
      { pueblo: "Qom/Toba", personas: 189 },
      { pueblo: "Aymara", personas: 172 },
      { pueblo: "Comechingón", personas: 153 },
      { pueblo: "Wichi", personas: 135 },
      { pueblo: "Ranquel", personas: 130 },
      { pueblo: "Aoniken", personas: 61 },
      { pueblo: "Charrúa", personas: 53 },
      { pueblo: "Günün A Küna", personas: 41 },
      { pueblo: "Moqoit/Mocoví", personas: 22 },
      { pueblo: "Atacama", personas: 19 },
      { pueblo: "Omaguaca", personas: 17 },
      { pueblo: "Chana", personas: 13 },
      { pueblo: "Mbya Guaraní", personas: 13 },
      { pueblo: "Chané", personas: 12 },
      { pueblo: "Chorote", personas: 12 },
      { pueblo: "Ocloya", personas: 12 },
      { pueblo: "Sanavirón", personas: 11 },
      { pueblo: "Selk´Nam/Ona", personas: 10 },
      { pueblo: "Vilela", personas: 9 },
      { pueblo: "Chicha", personas: 8 },
      { pueblo: "Lule", personas: 8 },
      { pueblo: "Pilagá", personas: 7 },
      { pueblo: "Avipón", personas: 5 },
      { pueblo: "Kolla Atacameño", personas: 5 },
      { pueblo: "Querandí", personas: 4 },
      { pueblo: "Lule Vilela", personas: 3 },
      { pueblo: "Tonokoté", personas: 3 },
      { pueblo: "Chulupí/Nivaclé", personas: 2 },
      { pueblo: "Corundí", personas: 2 },
      { pueblo: "Guaycurú", personas: 2 },
      { pueblo: "Iogys", personas: 2 },
      { pueblo: "Yagán", personas: 2 },
      { pueblo: "Minuán", personas: 1 },
      { pueblo: "Tapiete", personas: 1 },
    ],
    departamentos: [
      { departamento: "Aluminé", poblacion: 10173, indigena: 3342 },
      { departamento: "Añelo", poblacion: 18150, indigena: 1207 },
      { departamento: "Catán Lil", poblacion: 2641, indigena: 914 },
      { departamento: "Chos Malal", poblacion: 18289, indigena: 897 },
      { departamento: "Collón Curá", poblacion: 4832, indigena: 1086 },
      { departamento: "Confluencia", poblacion: 467217, indigena: 25889 },
      { departamento: "Huiliches", poblacion: 20853, indigena: 4721 },
      { departamento: "Lácar", poblacion: 39567, indigena: 3903 },
      { departamento: "Loncopué", poblacion: 7696, indigena: 1942 },
      { departamento: "Los Lagos", poblacion: 15502, indigena: 1324 },
      { departamento: "Minas", poblacion: 9267, indigena: 668 },
      { departamento: "Ñorquín", poblacion: 5572, indigena: 1354 },
      { departamento: "Pehuenches", poblacion: 29721, indigena: 1300 },
      { departamento: "Picún Leufú", poblacion: 5087, indigena: 436 },
      { departamento: "Picunches", poblacion: 8471, indigena: 1028 },
      { departamento: "Zapala", poblacion: 45540, indigena: 4425 },
    ],
  },
  {
    provincia: "Río Negro",
    poblacion: 747697,
    indigena: 48194,
    sinInformacion: 8147,
    pueblos: [
      { pueblo: "Mapuche", personas: 30173 },
      { pueblo: "Mapuche Tehuelche", personas: 4333 },
      { pueblo: "Tehuelche", personas: 2083 },
      { pueblo: "Guaraní", personas: 787 },
      { pueblo: "Quechua", personas: 632 },
      { pueblo: "Diaguita", personas: 352 },
      { pueblo: "Kolla", personas: 270 },
      { pueblo: "Ranquel", personas: 238 },
      { pueblo: "Qom/Toba", personas: 199 },
      { pueblo: "Aymara", personas: 166 },
      { pueblo: "Huarpe", personas: 165 },
      { pueblo: "Comechingón", personas: 149 },
      { pueblo: "Wichi", personas: 102 },
      { pueblo: "Aoniken", personas: 75 },
      { pueblo: "Charrúa", personas: 67 },
      { pueblo: "Günün A Küna", personas: 60 },
      { pueblo: "Selk´Nam/Ona", personas: 24 },
      { pueblo: "Moqoit/Mocoví", personas: 21 },
      { pueblo: "Atacama", personas: 17 },
      { pueblo: "Tonokoté", personas: 17 },
      { pueblo: "Omaguaca", personas: 16 },
      { pueblo: "Chicha", personas: 14 },
      { pueblo: "Mbya Guaraní", personas: 13 },
      { pueblo: "Chana", personas: 8 },
      { pueblo: "Querandí", personas: 8 },
      { pueblo: "Sanavirón", personas: 8 },
      { pueblo: "Lule Vilela", personas: 7 },
      { pueblo: "Ocloya", personas: 6 },
      { pueblo: "Yagán", personas: 5 },
      { pueblo: "Avipón", personas: 3 },
      { pueblo: "Chulupí/Nivaclé", personas: 3 },
      { pueblo: "Corundí", personas: 3 },
      { pueblo: "Guaycurú", personas: 3 },
      { pueblo: "Lule", personas: 3 },
      { pueblo: "Pilagá", personas: 3 },
      { pueblo: "Chané", personas: 2 },
      { pueblo: "Chorote", personas: 2 },
      { pueblo: "Diaguita Cacano", personas: 2 },
      { pueblo: "Kolla Atacameño", personas: 2 },
      { pueblo: "Tilián", personas: 2 },
      { pueblo: "Alakaluf", personas: 1 },
      { pueblo: "Guarayo", personas: 1 },
      { pueblo: "Tapiete", personas: 1 },
      { pueblo: "Vilela", personas: 1 },
    ],
    departamentos: [
      { departamento: "25 de Mayo", poblacion: 16555, indigena: 3064 },
      { departamento: "9 de Julio", poblacion: 3682, indigena: 882 },
      { departamento: "Adolfo Alsina", poblacion: 63845, indigena: 4393 },
      { departamento: "Avellaneda", poblacion: 41160, indigena: 1970 },
      { departamento: "Bariloche", poblacion: 161443, indigena: 12270 },
      { departamento: "Conesa", poblacion: 7398, indigena: 435 },
      { departamento: "El Cuy", poblacion: 6960, indigena: 760 },
      { departamento: "General Roca", poblacion: 379627, indigena: 18104 },
      { departamento: "Ñorquincó", poblacion: 1452, indigena: 926 },
      { departamento: "Pichi Mahuida", poblacion: 16493, indigena: 758 },
      { departamento: "Pilcaniyeu", poblacion: 9309, indigena: 1389 },
      { departamento: "San Antonio", poblacion: 35473, indigena: 2535 },
      { departamento: "Valcheta", poblacion: 4300, indigena: 708 },
    ],
  },
  {
    provincia: "Salta",
    poblacion: 1434225,
    indigena: 142870,
    sinInformacion: 21636,
    pueblos: [
      { pueblo: "Guaraní", personas: 35460 },
      { pueblo: "Wichi", personas: 31723 },
      { pueblo: "Kolla", personas: 21703 },
      { pueblo: "Diaguita", personas: 16635 },
      { pueblo: "Chané", personas: 2937 },
      { pueblo: "Chorote", personas: 2783 },
      { pueblo: "Qom/Toba", personas: 1941 },
      { pueblo: "Lule", personas: 1819 },
      { pueblo: "Tastil", personas: 1275 },
      { pueblo: "Atacama", personas: 1251 },
      { pueblo: "Quechua", personas: 1090 },
      { pueblo: "Tapiete", personas: 628 },
      { pueblo: "Mapuche", personas: 378 },
      { pueblo: "Aymara", personas: 332 },
      { pueblo: "Chulupí/Nivaclé", personas: 314 },
      { pueblo: "Omaguaca", personas: 254 },
      { pueblo: "Weenhayek", personas: 125 },
      { pueblo: "Kolla Atacameño", personas: 86 },
      { pueblo: "Comechingón", personas: 56 },
      { pueblo: "Tehuelche", personas: 51 },
      { pueblo: "Pilagá", personas: 46 },
      { pueblo: "Diaguita Cacano", personas: 35 },
      { pueblo: "Chicha", personas: 34 },
      { pueblo: "Ocloya", personas: 34 },
      { pueblo: "Iogys", personas: 29 },
      { pueblo: "Charrúa", personas: 24 },
      { pueblo: "Huarpe", personas: 23 },
      { pueblo: "Lule Vilela", personas: 21 },
      { pueblo: "Mbya Guaraní", personas: 21 },
      { pueblo: "Ranquel", personas: 21 },
      { pueblo: "Mapuche Tehuelche", personas: 20 },
      { pueblo: "Moqoit/Mocoví", personas: 20 },
      { pueblo: "Selk´Nam/Ona", personas: 11 },
      { pueblo: "Günün A Küna", personas: 10 },
      { pueblo: "Aoniken", personas: 8 },
      { pueblo: "Chana", personas: 7 },
      { pueblo: "Tilián", personas: 7 },
      { pueblo: "Avipón", personas: 6 },
      { pueblo: "Sanavirón", personas: 6 },
      { pueblo: "Tonokoté", personas: 4 },
      { pueblo: "Guaycurú", personas: 3 },
      { pueblo: "Corundí", personas: 1 },
      { pueblo: "Fiscara", personas: 1 },
      { pueblo: "Querandí", personas: 1 },
    ],
    departamentos: [
      { departamento: "Anta", poblacion: 69442, indigena: 2087 },
      { departamento: "Cachi", poblacion: 8928, indigena: 1577 },
      { departamento: "Cafayate", poblacion: 17822, indigena: 3013 },
      { departamento: "Capital", poblacion: 624003, indigena: 23335 },
      { departamento: "Cerrillos", poblacion: 55713, indigena: 1852 },
      { departamento: "Chicoana", poblacion: 24715, indigena: 995 },
      { departamento: "General Güemes", poblacion: 55746, indigena: 982 },
      { departamento: "General José de San Martín", poblacion: 177448, indigena: 42352 },
      { departamento: "Guachipas", poblacion: 3491, indigena: 265 },
      { departamento: "Iruya", poblacion: 6116, indigena: 4384 },
      { departamento: "La Caldera", poblacion: 12246, indigena: 926 },
      { departamento: "La Candelaria", poblacion: 7182, indigena: 161 },
      { departamento: "La Poma", poblacion: 1789, indigena: 940 },
      { departamento: "La Viña", poblacion: 8888, indigena: 273 },
      { departamento: "Los Andes", poblacion: 7182, indigena: 3581 },
      { departamento: "Metán", poblacion: 48028, indigena: 1194 },
      { departamento: "Molinos", poblacion: 5808, indigena: 3127 },
      { departamento: "Orán", poblacion: 159715, indigena: 22494 },
      { departamento: "Rivadavia", poblacion: 38062, indigena: 16879 },
      { departamento: "Rosario de la Frontera", poblacion: 33750, indigena: 245 },
      { departamento: "Rosario de Lerma", poblacion: 50961, indigena: 3522 },
      { departamento: "San Carlos", poblacion: 7779, indigena: 2289 },
      { departamento: "Santa Victoria", poblacion: 9411, indigena: 6397 },
    ],
  },
  {
    provincia: "San Juan",
    poblacion: 819445,
    indigena: 14457,
    sinInformacion: 5394,
    pueblos: [
      { pueblo: "Huarpe", personas: 6463 },
      { pueblo: "Diaguita", personas: 1398 },
      { pueblo: "Mapuche", personas: 379 },
      { pueblo: "Quechua", personas: 261 },
      { pueblo: "Guaraní", personas: 117 },
      { pueblo: "Kolla", personas: 59 },
      { pueblo: "Comechingón", personas: 49 },
      { pueblo: "Atacama", personas: 45 },
      { pueblo: "Qom/Toba", personas: 40 },
      { pueblo: "Aymara", personas: 36 },
      { pueblo: "Diaguita Cacano", personas: 33 },
      { pueblo: "Mapuche Tehuelche", personas: 32 },
      { pueblo: "Tehuelche", personas: 26 },
      { pueblo: "Wichi", personas: 23 },
      { pueblo: "Omaguaca", personas: 12 },
      { pueblo: "Charrúa", personas: 11 },
      { pueblo: "Chicha", personas: 9 },
      { pueblo: "Chana", personas: 8 },
      { pueblo: "Günün A Küna", personas: 8 },
      { pueblo: "Ranquel", personas: 8 },
      { pueblo: "Chané", personas: 7 },
      { pueblo: "Selk´Nam/Ona", personas: 6 },
      { pueblo: "Avipón", personas: 5 },
      { pueblo: "Mbya Guaraní", personas: 4 },
      { pueblo: "Aoniken", personas: 3 },
      { pueblo: "Chorote", personas: 3 },
      { pueblo: "Lule", personas: 3 },
      { pueblo: "Moqoit/Mocoví", personas: 3 },
      { pueblo: "Pilagá", personas: 2 },
      { pueblo: "Tastil", personas: 2 },
      { pueblo: "Ansilta", personas: 1 },
      { pueblo: "Corundí", personas: 1 },
      { pueblo: "Kolla Atacameño", personas: 1 },
      { pueblo: "Ocloya", personas: 1 },
      { pueblo: "Querandí", personas: 1 },
      { pueblo: "Toara", personas: 1 },
      { pueblo: "Tonokoté", personas: 1 },
      { pueblo: "Yagán", personas: 1 },
    ],
    departamentos: [
      { departamento: "25 de Mayo", poblacion: 20824, indigena: 1128 },
      { departamento: "9 de Julio", poblacion: 12498, indigena: 161 },
      { departamento: "Albardón", poblacion: 31281, indigena: 348 },
      { departamento: "Angaco", poblacion: 10172, indigena: 114 },
      { departamento: "Calingasta", poblacion: 10667, indigena: 142 },
      { departamento: "Capital", poblacion: 114849, indigena: 1650 },
      { departamento: "Caucete", poblacion: 44017, indigena: 1194 },
      { departamento: "Chimbas", poblacion: 103772, indigena: 1294 },
      { departamento: "Iglesia", poblacion: 8826, indigena: 149 },
      { departamento: "Jáchal", poblacion: 25269, indigena: 733 },
      { departamento: "Pocito", poblacion: 72879, indigena: 937 },
      { departamento: "Rawson", poblacion: 136582, indigena: 1575 },
      { departamento: "Rivadavia", poblacion: 101334, indigena: 1378 },
      { departamento: "San Martín", poblacion: 15037, indigena: 135 },
      { departamento: "Santa Lucía", poblacion: 62697, indigena: 681 },
      { departamento: "Sarmiento", poblacion: 27188, indigena: 1774 },
      { departamento: "Ullum", poblacion: 6454, indigena: 64 },
      { departamento: "Valle Fértil", poblacion: 8425, indigena: 884 },
      { departamento: "Zonda", poblacion: 6674, indigena: 116 },
    ],
  },
  {
    provincia: "San Luis",
    poblacion: 540548,
    indigena: 8340,
    sinInformacion: 2445,
    pueblos: [
      { pueblo: "Huarpe", personas: 1322 },
      { pueblo: "Comechingón", personas: 1274 },
      { pueblo: "Ranquel", personas: 1012 },
      { pueblo: "Mapuche", personas: 652 },
      { pueblo: "Guaraní", personas: 369 },
      { pueblo: "Quechua", personas: 274 },
      { pueblo: "Diaguita", personas: 230 },
      { pueblo: "Qom/Toba", personas: 150 },
      { pueblo: "Aymara", personas: 105 },
      { pueblo: "Kolla", personas: 86 },
      { pueblo: "Mapuche Tehuelche", personas: 69 },
      { pueblo: "Tehuelche", personas: 58 },
      { pueblo: "Wichi", personas: 54 },
      { pueblo: "Charrúa", personas: 51 },
      { pueblo: "Günün A Küna", personas: 25 },
      { pueblo: "Michilingüe", personas: 23 },
      { pueblo: "Moqoit/Mocoví", personas: 22 },
      { pueblo: "Sanavirón", personas: 17 },
      { pueblo: "Atacama", personas: 13 },
      { pueblo: "Omaguaca", personas: 12 },
      { pueblo: "Tonokoté", personas: 10 },
      { pueblo: "Querandí", personas: 8 },
      { pueblo: "Chana", personas: 7 },
      { pueblo: "Chicha", personas: 7 },
      { pueblo: "Chorote", personas: 6 },
      { pueblo: "Guaycurú", personas: 6 },
      { pueblo: "Avipón", personas: 4 },
      { pueblo: "Diaguita Cacano", personas: 4 },
      { pueblo: "Mbya Guaraní", personas: 3 },
      { pueblo: "Selk´Nam/Ona", personas: 3 },
      { pueblo: "Chané", personas: 2 },
      { pueblo: "Corundí", personas: 2 },
      { pueblo: "Kolla Atacameño", personas: 2 },
      { pueblo: "Lule Vilela", personas: 2 },
      { pueblo: "Pilagá", personas: 2 },
      { pueblo: "Toara", personas: 2 },
      { pueblo: "Weenhayek", personas: 2 },
      { pueblo: "Aoniken", personas: 1 },
      { pueblo: "Chulupí/Nivaclé", personas: 1 },
      { pueblo: "Guarayo", personas: 1 },
      { pueblo: "Tastil", personas: 1 },
      { pueblo: "Vilela", personas: 1 },
    ],
    departamentos: [
      { departamento: "Ayacucho", poblacion: 23653, indigena: 321 },
      { departamento: "Belgrano", poblacion: 5575, indigena: 77 },
      { departamento: "Chacabuco", poblacion: 26522, indigena: 498 },
      { departamento: "Coronel Pringles", poblacion: 16044, indigena: 189 },
      { departamento: "General Pedernera", poblacion: 148671, indigena: 1863 },
      { departamento: "Gobernador Dupuy", poblacion: 14334, indigena: 186 },
      { departamento: "Juan Martín de Pueyrredón", poblacion: 260769, indigena: 4005 },
      { departamento: "Junín", poblacion: 40289, indigena: 1164 },
      { departamento: "Libertador General San Martín", poblacion: 4691, indigena: 37 },
    ],
  },
  {
    provincia: "Santa Cruz",
    poblacion: 335677,
    indigena: 12525,
    sinInformacion: 3189,
    pueblos: [
      { pueblo: "Mapuche", personas: 3245 },
      { pueblo: "Tehuelche", personas: 1776 },
      { pueblo: "Mapuche Tehuelche", personas: 1016 },
      { pueblo: "Diaguita", personas: 708 },
      { pueblo: "Quechua", personas: 611 },
      { pueblo: "Guaraní", personas: 487 },
      { pueblo: "Kolla", personas: 484 },
      { pueblo: "Aoniken", personas: 187 },
      { pueblo: "Qom/Toba", personas: 151 },
      { pueblo: "Wichi", personas: 132 },
      { pueblo: "Aymara", personas: 77 },
      { pueblo: "Comechingón", personas: 73 },
      { pueblo: "Huarpe", personas: 62 },
      { pueblo: "Ranquel", personas: 52 },
      { pueblo: "Charrúa", personas: 41 },
      { pueblo: "Omaguaca", personas: 38 },
      { pueblo: "Selk´Nam/Ona", personas: 28 },
      { pueblo: "Moqoit/Mocoví", personas: 24 },
      { pueblo: "Günün A Küna", personas: 16 },
      { pueblo: "Diaguita Cacano", personas: 14 },
      { pueblo: "Lule", personas: 14 },
      { pueblo: "Atacama", personas: 12 },
      { pueblo: "Ocloya", personas: 9 },
      { pueblo: "Kolla Atacameño", personas: 6 },
      { pueblo: "Sanavirón", personas: 6 },
      { pueblo: "Lule Vilela", personas: 5 },
      { pueblo: "Alakaluf", personas: 4 },
      { pueblo: "Chané", personas: 4 },
      { pueblo: "Chicha", personas: 4 },
      { pueblo: "Chorote", personas: 4 },
      { pueblo: "Chulupí/Nivaclé", personas: 4 },
      { pueblo: "Querandí", personas: 4 },
      { pueblo: "Tastil", personas: 4 },
      { pueblo: "Yagán", personas: 4 },
      { pueblo: "Guaycurú", personas: 3 },
      { pueblo: "Mbya Guaraní", personas: 3 },
      { pueblo: "Pilagá", personas: 3 },
      { pueblo: "Tapiete", personas: 3 },
      { pueblo: "Toara", personas: 3 },
      { pueblo: "Tonokoté", personas: 3 },
      { pueblo: "Vilela", personas: 3 },
      { pueblo: "Wayteca/Chono", personas: 3 },
      { pueblo: "Mak'A", personas: 2 },
      { pueblo: "Avipón", personas: 1 },
      { pueblo: "Chana", personas: 1 },
      { pueblo: "Fiscara", personas: 1 },
      { pueblo: "Iogys", personas: 1 },
    ],
    departamentos: [
      { departamento: "Corpen Aike", poblacion: 15035, indigena: 500 },
      { departamento: "Deseado", poblacion: 126266, indigena: 5294 },
      { departamento: "Güer Aike", poblacion: 137309, indigena: 4270 },
      { departamento: "Lago Argentino", poblacion: 25384, indigena: 1044 },
      { departamento: "Lago Buenos Aires", poblacion: 12584, indigena: 595 },
      { departamento: "Magallanes", poblacion: 12828, indigena: 380 },
      { departamento: "Río Chico", poblacion: 6271, indigena: 442 },
    ],
  },
  {
    provincia: "Santa Fe",
    poblacion: 3519059,
    indigena: 57193,
    sinInformacion: 24984,
    pueblos: [
      { pueblo: "Moqoit/Mocoví", personas: 11278 },
      { pueblo: "Qom/Toba", personas: 7773 },
      { pueblo: "Guaraní", personas: 3934 },
      { pueblo: "Mapuche", personas: 1478 },
      { pueblo: "Diaguita", personas: 1246 },
      { pueblo: "Quechua", personas: 1243 },
      { pueblo: "Comechingón", personas: 972 },
      { pueblo: "Wichi", personas: 512 },
      { pueblo: "Kolla", personas: 466 },
      { pueblo: "Charrúa", personas: 384 },
      { pueblo: "Avipón", personas: 347 },
      { pueblo: "Chana", personas: 301 },
      { pueblo: "Tehuelche", personas: 273 },
      { pueblo: "Aymara", personas: 268 },
      { pueblo: "Ranquel", personas: 263 },
      { pueblo: "Mapuche Tehuelche", personas: 258 },
      { pueblo: "Corundí", personas: 230 },
      { pueblo: "Huarpe", personas: 134 },
      { pueblo: "Sanavirón", personas: 113 },
      { pueblo: "Guaycurú", personas: 98 },
      { pueblo: "Tonokoté", personas: 88 },
      { pueblo: "Atacama", personas: 78 },
      { pueblo: "Mbya Guaraní", personas: 44 },
      { pueblo: "Günün A Küna", personas: 43 },
      { pueblo: "Querandí", personas: 42 },
      { pueblo: "Vilela", personas: 37 },
      { pueblo: "Chorote", personas: 34 },
      { pueblo: "Pilagá", personas: 33 },
      { pueblo: "Diaguita Cacano", personas: 31 },
      { pueblo: "Chicha", personas: 29 },
      { pueblo: "Aoniken", personas: 25 },
      { pueblo: "Lule Vilela", personas: 23 },
      { pueblo: "Chané", personas: 21 },
      { pueblo: "Selk´Nam/Ona", personas: 21 },
      { pueblo: "Tilián", personas: 17 },
      { pueblo: "Omaguaca", personas: 13 },
      { pueblo: "Minuán", personas: 12 },
      { pueblo: "Lule", personas: 11 },
      { pueblo: "Chulupí/Nivaclé", personas: 9 },
      { pueblo: "Kolla Atacameño", personas: 6 },
      { pueblo: "Ocloya", personas: 4 },
      { pueblo: "Guarayo", personas: 3 },
      { pueblo: "Toara", personas: 3 },
      { pueblo: "Fiscara", personas: 2 },
      { pueblo: "Tapiete", personas: 2 },
      { pueblo: "Tastil", personas: 2 },
      { pueblo: "Yagán", personas: 2 },
      { pueblo: "Michilingüe", personas: 1 },
      { pueblo: "Wayteca/Chono", personas: 1 },
      { pueblo: "Weenhayek", personas: 1 },
    ],
    departamentos: [
      { departamento: "9 de Julio", poblacion: 30942, indigena: 556 },
      { departamento: "Belgrano", poblacion: 48544, indigena: 449 },
      { departamento: "Caseros", poblacion: 86261, indigena: 895 },
      { departamento: "Castellanos", poblacion: 189464, indigena: 1959 },
      { departamento: "Constitución", poblacion: 93000, indigena: 1215 },
      { departamento: "Garay", poblacion: 24853, indigena: 1943 },
      { departamento: "General López", poblacion: 200455, indigena: 2947 },
      { departamento: "General Obligado", poblacion: 197533, indigena: 3351 },
      { departamento: "Iriondo", poblacion: 73636, indigena: 654 },
      { departamento: "La Capital", poblacion: 568259, indigena: 9830 },
      { departamento: "Las Colonias", poblacion: 114730, indigena: 1415 },
      { departamento: "Rosario", poblacion: 1337958, indigena: 21628 },
      { departamento: "San Cristóbal", poblacion: 72593, indigena: 658 },
      { departamento: "San Javier", poblacion: 33180, indigena: 1590 },
      { departamento: "San Jerónimo", poblacion: 84617, indigena: 983 },
      { departamento: "San Justo", poblacion: 46486, indigena: 2237 },
      { departamento: "San Lorenzo", poblacion: 193786, indigena: 2275 },
      { departamento: "San Martín", poblacion: 67299, indigena: 695 },
      { departamento: "Vera", poblacion: 55463, indigena: 1913 },
    ],
  },
  {
    provincia: "Santiago del Estero",
    poblacion: 1057752,
    indigena: 28022,
    sinInformacion: 8966,
    pueblos: [
      { pueblo: "Tonokoté", personas: 9065 },
      { pueblo: "Diaguita Cacano", personas: 3429 },
      { pueblo: "Lule Vilela", personas: 1763 },
      { pueblo: "Quechua", personas: 1145 },
      { pueblo: "Diaguita", personas: 901 },
      { pueblo: "Sanavirón", personas: 736 },
      { pueblo: "Vilela", personas: 628 },
      { pueblo: "Qom/Toba", personas: 282 },
      { pueblo: "Guaraní", personas: 180 },
      { pueblo: "Guaycurú", personas: 135 },
      { pueblo: "Wichi", personas: 133 },
      { pueblo: "Mapuche", personas: 126 },
      { pueblo: "Kolla", personas: 80 },
      { pueblo: "Lule", personas: 66 },
      { pueblo: "Comechingón", personas: 61 },
      { pueblo: "Tehuelche", personas: 52 },
      { pueblo: "Moqoit/Mocoví", personas: 45 },
      { pueblo: "Avipón", personas: 39 },
      { pueblo: "Atacama", personas: 37 },
      { pueblo: "Aymara", personas: 33 },
      { pueblo: "Mapuche Tehuelche", personas: 20 },
      { pueblo: "Charrúa", personas: 18 },
      { pueblo: "Ranquel", personas: 18 },
      { pueblo: "Chicha", personas: 11 },
      { pueblo: "Huarpe", personas: 10 },
      { pueblo: "Aoniken", personas: 5 },
      { pueblo: "Chané", personas: 4 },
      { pueblo: "Mbya Guaraní", personas: 4 },
      { pueblo: "Selk´Nam/Ona", personas: 4 },
      { pueblo: "Chorote", personas: 3 },
      { pueblo: "Günün A Küna", personas: 3 },
      { pueblo: "Omaguaca", personas: 3 },
      { pueblo: "Pilagá", personas: 3 },
      { pueblo: "Chana", personas: 2 },
      { pueblo: "Corundí", personas: 2 },
      { pueblo: "Yagán", personas: 2 },
      { pueblo: "Fiscara", personas: 1 },
      { pueblo: "Iogys", personas: 1 },
      { pueblo: "Isoceño", personas: 1 },
      { pueblo: "Kolla Atacameño", personas: 1 },
      { pueblo: "Ocloya", personas: 1 },
      { pueblo: "Tastil", personas: 1 },
      { pueblo: "Tilián", personas: 1 },
      { pueblo: "Weenhayek", personas: 1 },
    ],
    departamentos: [
      { departamento: "Aguirre", poblacion: 8959, indigena: 463 },
      { departamento: "Alberdi", poblacion: 20104, indigena: 754 },
      { departamento: "Atamisqui", poblacion: 14894, indigena: 2224 },
      { departamento: "Avellaneda", poblacion: 25462, indigena: 1482 },
      { departamento: "Banda", poblacion: 170401, indigena: 2027 },
      { departamento: "Belgrano", poblacion: 10809, indigena: 115 },
      { departamento: "Capital", poblacion: 328824, indigena: 4348 },
      { departamento: "Choya", poblacion: 43692, indigena: 506 },
      { departamento: "Copo", poblacion: 35653, indigena: 1904 },
      { departamento: "Figueroa", poblacion: 20246, indigena: 4482 },
      { departamento: "General Taboada", poblacion: 46304, indigena: 453 },
      { departamento: "Guasayán", poblacion: 9251, indigena: 496 },
      { departamento: "Jiménez", poblacion: 18622, indigena: 145 },
      { departamento: "Juan Felipe Ibarra", poblacion: 20567, indigena: 487 },
      { departamento: "Loreto", poblacion: 24047, indigena: 673 },
      { departamento: "Mitre", poblacion: 1440, indigena: 128 },
      { departamento: "Moreno", poblacion: 40352, indigena: 804 },
      { departamento: "Ojo de Agua", poblacion: 15008, indigena: 163 },
      { departamento: "Pellegrini", poblacion: 26193, indigena: 316 },
      { departamento: "Quebrachos", poblacion: 12336, indigena: 218 },
      { departamento: "Río Hondo", poblacion: 66637, indigena: 1134 },
      { departamento: "Rivadavia", poblacion: 5314, indigena: 42 },
      { departamento: "Robles", poblacion: 53879, indigena: 551 },
      { departamento: "Salavina", poblacion: 12775, indigena: 2098 },
      { departamento: "San Martín", poblacion: 11183, indigena: 1756 },
      { departamento: "Sarmiento", poblacion: 5034, indigena: 102 },
      { departamento: "Silípica", poblacion: 9766, indigena: 151 },
    ],
  },
  {
    provincia: "Tierra del Fuego",
    poblacion: 184958,
    indigena: 5942,
    sinInformacion: 1397,
    pueblos: [
      { pueblo: "Mapuche", personas: 1014 },
      { pueblo: "Diaguita", personas: 733 },
      { pueblo: "Selk´Nam/Ona", personas: 610 },
      { pueblo: "Kolla", personas: 357 },
      { pueblo: "Quechua", personas: 345 },
      { pueblo: "Guaraní", personas: 316 },
      { pueblo: "Mapuche Tehuelche", personas: 167 },
      { pueblo: "Qom/Toba", personas: 144 },
      { pueblo: "Tehuelche", personas: 142 },
      { pueblo: "Yagán", personas: 122 },
      { pueblo: "Comechingón", personas: 93 },
      { pueblo: "Huarpe", personas: 93 },
      { pueblo: "Wichi", personas: 86 },
      { pueblo: "Aymara", personas: 64 },
      { pueblo: "Omaguaca", personas: 55 },
      { pueblo: "Charrúa", personas: 34 },
      { pueblo: "Ranquel", personas: 34 },
      { pueblo: "Moqoit/Mocoví", personas: 26 },
      { pueblo: "Atacama", personas: 15 },
      { pueblo: "Aoniken", personas: 14 },
      { pueblo: "Tonokoté", personas: 12 },
      { pueblo: "Mbya Guaraní", personas: 7 },
      { pueblo: "Günün A Küna", personas: 6 },
      { pueblo: "Ocloya", personas: 6 },
      { pueblo: "Sanavirón", personas: 6 },
      { pueblo: "Haush/Maneken", personas: 5 },
      { pueblo: "Wayteca/Chono", personas: 4 },
      { pueblo: "Alakaluf", personas: 3 },
      { pueblo: "Chana", personas: 3 },
      { pueblo: "Diaguita Cacano", personas: 3 },
      { pueblo: "Guaycurú", personas: 3 },
      { pueblo: "Lule Vilela", personas: 3 },
      { pueblo: "Querandí", personas: 3 },
      { pueblo: "Vilela", personas: 3 },
      { pueblo: "Chané", personas: 2 },
      { pueblo: "Chorote", personas: 2 },
      { pueblo: "Kolla Atacameño", personas: 2 },
      { pueblo: "Lule", personas: 2 },
      { pueblo: "Toara", personas: 2 },
      { pueblo: "Avipón", personas: 1 },
      { pueblo: "Chicha", personas: 1 },
      { pueblo: "Chulupí/Nivaclé", personas: 1 },
      { pueblo: "Isoceño", personas: 1 },
    ],
    departamentos: [
      { departamento: "Río Grande", poblacion: 98922, indigena: 3004 },
      { departamento: "Tolhuin", poblacion: 6027, indigena: 164 },
      { departamento: "Ushuaia", poblacion: 80009, indigena: 2774 },
    ],
  },
  {
    provincia: "Tucumán",
    poblacion: 1727337,
    indigena: 37646,
    sinInformacion: 14067,
    pueblos: [
      { pueblo: "Diaguita", personas: 20096 },
      { pueblo: "Kolla", personas: 503 },
      { pueblo: "Quechua", personas: 442 },
      { pueblo: "Lule", personas: 437 },
      { pueblo: "Guaraní", personas: 326 },
      { pueblo: "Mapuche", personas: 319 },
      { pueblo: "Wichi", personas: 294 },
      { pueblo: "Qom/Toba", personas: 222 },
      { pueblo: "Tonokoté", personas: 211 },
      { pueblo: "Aymara", personas: 158 },
      { pueblo: "Diaguita Cacano", personas: 71 },
      { pueblo: "Atacama", personas: 63 },
      { pueblo: "Omaguaca", personas: 60 },
      { pueblo: "Tehuelche", personas: 53 },
      { pueblo: "Comechingón", personas: 46 },
      { pueblo: "Mapuche Tehuelche", personas: 41 },
      { pueblo: "Moqoit/Mocoví", personas: 34 },
      { pueblo: "Lule Vilela", personas: 31 },
      { pueblo: "Charrúa", personas: 29 },
      { pueblo: "Huarpe", personas: 27 },
      { pueblo: "Chicha", personas: 18 },
      { pueblo: "Sanavirón", personas: 17 },
      { pueblo: "Avipón", personas: 10 },
      { pueblo: "Chorote", personas: 10 },
      { pueblo: "Ranquel", personas: 10 },
      { pueblo: "Chané", personas: 9 },
      { pueblo: "Kolla Atacameño", personas: 8 },
      { pueblo: "Chana", personas: 7 },
      { pueblo: "Mbya Guaraní", personas: 6 },
      { pueblo: "Guaycurú", personas: 4 },
      { pueblo: "Günün A Küna", personas: 4 },
      { pueblo: "Ocloya", personas: 3 },
      { pueblo: "Aoniken", personas: 2 },
      { pueblo: "Selk´Nam/Ona", personas: 2 },
      { pueblo: "Vilela", personas: 2 },
      { pueblo: "Chulupí/Nivaclé", personas: 1 },
      { pueblo: "Querandí", personas: 1 },
      { pueblo: "Tastil", personas: 1 },
      { pueblo: "Tilián", personas: 1 },
    ],
    departamentos: [
      { departamento: "Burruyacú", poblacion: 45459, indigena: 387 },
      { departamento: "Capital", poblacion: 587289, indigena: 9294 },
      { departamento: "Chicligasta", poblacion: 92308, indigena: 798 },
      { departamento: "Cruz Alta", poblacion: 227688, indigena: 2298 },
      { departamento: "Famaillá", poblacion: 42669, indigena: 658 },
      { departamento: "Graneros", poblacion: 15539, indigena: 58 },
      { departamento: "Juan Bautista Alberdi", poblacion: 34745, indigena: 286 },
      { departamento: "La Cocha", poblacion: 21196, indigena: 155 },
      { departamento: "Leales", poblacion: 66352, indigena: 424 },
      { departamento: "Lules", poblacion: 93464, indigena: 1795 },
      { departamento: "Monteros", poblacion: 77469, indigena: 1070 },
      { departamento: "Río Chico", poblacion: 64927, indigena: 776 },
      { departamento: "Simoca", poblacion: 36946, indigena: 292 },
      { departamento: "Tafí del Valle", poblacion: 22382, indigena: 12247 },
      { departamento: "Tafí Viejo", poblacion: 172877, indigena: 3182 },
      { departamento: "Trancas", poblacion: 23438, indigena: 2147 },
      { departamento: "Yerba Buena", poblacion: 102589, indigena: 1779 },
    ],
  },
];

/** El total del país, para poder comparar la provincia contra él. */
export const CENSO_PAIS = {
  poblacion: 45618787,
  indigena: 1306730,
  sinInformacion: 431703,
  /** Rótulos distintos en el cuadro nacional; en una provincia hay menos. */
  pueblos: 58,
} as const;
