/**
 * Saberes territoriales — capa 2 del sistema de ecorregiones.
 *
 * ARCHIVO GENERADO. No se edita a mano: sale de los tres inventarios de
 * `_research/ecosistemas-saberes-<region>/fase-2-saberes-territoriales/`.
 *
 * Qué es esta capa y por qué está separada de `BiomaFicha.saberes`:
 *
 * La ficha ecológica describe un bioma y se resuelve por ECO_ID, que es un dato
 * del terreno. Un saber territorial no funciona así. "Careo de Sierra Nevada" no
 * es una propiedad del matorral mediterráneo: es una práctica de unas
 * comunidades concretas de la Alpujarra, con nombre, autoridad y cartografía
 * propia. Activarlo porque el predio cayó en el mismo ECO_ID, o porque está en
 * España, sería atribuirle a un usuario un saber que no es de su territorio.
 *
 * Por eso ninguno de estos 85 se activa por país, por Köppen ni por
 * ecorregión: hace falta un polígono con procedencia y licencia verificadas, y
 * el punto tiene que caer adentro. Hoy hay 85 documentados y cero
 * activables, porque el registro de geometrías está vacío a propósito. La regla
 * y el registro viven en `lib/saberes.ts`.
 *
 * Reparto: mesoamerica-caribe 9, mexico-estados-unidos 21, europa-occidental 26, sudamerica 29.
 */

import type { SaberTerritorial } from './saberesTipos';

export const SABERES_TERRITORIALES: readonly SaberTerritorial[] = [
  {
    id: "cac_bosques_comunales_y_milpa_k_iche_mam",
    nombre: "Bosques comunales y milpa K’iche’/Mam",
    region: "mesoamerica-caribe",
    portadores: "comunidades Maya K’iche’ y Mam.",
    paises: ["GT"],
    ecoIdsCompatibles: [],
    territorioMinimo: "`country_code == GT` y departamentos/municipios cubiertos por la investigación original; hasta cargar esa capa, usar solo a nivel editorial.",
    sintesisPublica: "diversidad de la milpa, árboles útiles, semillas locales, restauración y reglas comunales de bosque. Reconocer el rol de mujeres en la custodia de semillas y plantas.",
    cautelas: [
      "lugares ceremoniales, detalles de plantas medicinales ni la idea de una única práctica “maya”.",
    ],
    fuentes: [
      { label: "CATIE — milpa K’iche’", url: "https://repositorio.catie.ac.cr/handle/11554/9716", revisada: "2026-09-03" },
      { label: "CATIE — restauración con conocimientos Mam y K’iche’", url: "https://repositorio.catie.ac.cr/handle/11554/12692", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/centroamerica-caribe/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "cac_quesungual",
    nombre: "Quesungual",
    region: "mesoamerica-caribe",
    portadores: "campesinado del occidente de Honduras, especialmente Lempira.",
    paises: ["HN"],
    ecoIdsCompatibles: [],
    territorioMinimo: "`country_code == HN`, `admin1` o polígono de la zona Quesungual. No activarlo en todo el ECO_ID 527.",
    sintesisPublica: "retención y poda de árboles/arbustos, siembra de maíz-frijol-sorgo, cobertura con residuos y abandono de la quema; mejora de infiltración, humedad y control de erosión.",
    cautelas: [
      "no convertir distancias, densidades o podas en receta sin diagnóstico de pendiente, suelo y árbol.",
    ],
    fuentes: [
      { label: "FAO — Quesungual", url: "https://www.fao.org/4/Y5030E/y5030e19.htm", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/centroamerica-caribe/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "cac_kuxur_rum",
    nombre: "Kuxur Rum",
    region: "mesoamerica-caribe",
    portadores: "comunidades Ch’orti’ del corredor seco de Guatemala.",
    paises: ["GT"],
    ecoIdsCompatibles: [],
    territorioMinimo: "`country_code == GT` y municipios Ch’orti’ documentados.",
    sintesisPublica: "madre cacao o madreado (`Gliricidia sepium`) con granos básicos, poda, biomasa sobre el suelo, no quema y conservación de humedad.",
    cautelas: [
      "conservar el nombre local y no fusionarlo con Quesungual aunque compartan principios.",
    ],
    fuentes: [
      { label: "FAO Guatemala — Kuxur Rum", url: "https://www.fao.org/guatemala/detalle/historia-de-inter%C3%A9s-humano/detail/combatir-la-sequ%C3%ADa-con-t%C3%A9cnicas-ancestrales/es", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/centroamerica-caribe/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "cac_conocimiento_mayangna_de_bosawas",
    nombre: "Conocimiento Mayangna de BOSAWAS",
    region: "mesoamerica-caribe",
    portadores: "pueblo Mayangna de Nicaragua.",
    paises: ["NI"],
    ecoIdsCompatibles: [],
    territorioMinimo: "`country_code == NI` y territorio Mayangna dentro de BOSAWAS.",
    sintesisPublica: "categorías propias de clasificación de flora/fauna y conocimientos sobre hábitat, reproducción, migración y aprovechamiento sostenible de peces y tortugas.",
    cautelas: [
      "puntos de captura, lugares sagrados o conocimientos restringidos. La fuente fue construida con participación y consentimiento; la app debe mantener la atribución.",
    ],
    fuentes: [
      { label: "UNESCO — transmisión del conocimiento Mayangna", url: "https://ich.unesco.org/en/project-education/reinforcing-the-transmission-of-mayangna-knowledge-and-culture-in-the-classroom-00493", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/centroamerica-caribe/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "cac_cacao_bribri_y_cabecar",
    nombre: "Cacao Bribri y Cabécar",
    region: "mesoamerica-caribe",
    portadores: "pueblos Bribri y Cabécar de Costa Rica y áreas transfronterizas documentadas.",
    paises: ["CR"],
    ecoIdsCompatibles: [],
    territorioMinimo: "territorios indígenas o fincas de Talamanca incluidos en las fuentes; como mínimo `country_code == CR` y cantones/territorios relevantes.",
    sintesisPublica: "cacaotales diversos de dos a tres estratos; laurel, Inga, cítricos, musáceas, palmas, parches y galerías de bosque; usos múltiples de plantas.",
    cautelas: [
      "las 283 especies registradas en el estudio no son una lista universal ni una receta para todas las fincas.",
    ],
    fuentes: [
      { label: "CATIE — cacaotales Bribri y Cabécar", url: "https://repositorio.catie.ac.cr/handle/11554/6038", revisada: "2026-09-03" },
      { label: "CATIE — plantas útiles", url: "https://repositorio.catie.ac.cr/handle/11554/6675", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/centroamerica-caribe/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "cac_agricultura_nainu_guna",
    nombre: "Agricultura nainu Guna",
    region: "mesoamerica-caribe",
    portadores: "pueblo Guna de Panamá.",
    paises: ["PA"],
    ecoIdsCompatibles: [],
    territorioMinimo: "`country_code == PA` y comarca/comunidad Guna documentada.",
    sintesisPublica: "parcelas manejadas dentro del bosque, huertos familiares, cultivos ribereños, frutales en bordes y recolección; la diversidad espacial reduce riesgo y mantiene cobertura.",
    cautelas: [
      "localización de sitios sagrados ni conocimiento ceremonial.",
    ],
    fuentes: [
      { label: "FAO — agricultura nainu", url: "https://www.fao.org/fileadmin/templates/esw/esw_new/documents/SARD/good_practices_Latin_America/13_Nainu_agriculture_Panama1.pdf", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/centroamerica-caribe/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "cac_vinales_y_conuco_cubano",
    nombre: "Viñales y conuco cubano",
    region: "mesoamerica-caribe",
    portadores: "familias campesinas de Viñales; conuco familiar documentado en Cuba oriental como entrada separada.",
    paises: ["CU"],
    ecoIdsCompatibles: [],
    territorioMinimo: "polígono del Paisaje Cultural Valle de Viñales, Pinar del Río. **No** activar por ECO_ID 459 completo.",
    sintesisPublica: "pequeñas fincas, tabaco y métodos agrícolas tradicionales integrados al paisaje de mogotes. huerto multiestrato con alimentos, frutales, sombra y plantas de uso familiar; aclarar que composición y función varían entre hogares.",
    cautelas: [],
    fuentes: [
      { label: "UNESCO — Valle de Viñales", url: "https://whc.unesco.org/en/list/840/", revisada: "2026-09-03" },
      { label: "FAO — conuco cubano", url: "https://www.fao.org/4/w8801e/w8801e03.htm", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/centroamerica-caribe/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "cac_cockpit_country_maroon",
    nombre: "Cockpit Country Maroon",
    region: "mesoamerica-caribe",
    portadores: "Maroons de Sotavento de Jamaica.",
    paises: ["JM"],
    ecoIdsCompatibles: [],
    territorioMinimo: "polígono oficial de Cockpit Country Protected Area y validación cultural.",
    sintesisPublica: "relación histórica con senderos y paisaje kárstico; conocimiento intergeneracional de plantas nativas y endémicas.",
    cautelas: [
      "Peace Cave, Kindah tree u otros sitios como coordenadas; tampoco recetas medicinales.",
    ],
    fuentes: [
      { label: "UNESCO — Cockpit Country Protected Area", url: "https://whc.unesco.org/en/tentativelists/6822/", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/centroamerica-caribe/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "cac_agroforesteria_kalinago_de_dominica",
    nombre: "Agroforestería Kalinago de Dominica",
    region: "mesoamerica-caribe",
    portadores: "pueblo Kalinago de Dominica.",
    paises: ["DM"],
    ecoIdsCompatibles: [],
    territorioMinimo: "`country_code == DM`, preferentemente polígono de Kalinago Territory.",
    sintesisPublica: "sistemas multiestrato con coco/cítricos, musáceas, café/cacao y raíces; cortavientos, cercas vivas, fibras y materiales forestales.",
    cautelas: [
      "no extender esta descripción a Guadalupe, Martinica, Santa Lucía u otras Antillas por compartir ECO_ID.",
    ],
    fuentes: [
      { label: "FAO — agroforestería de Dominica", url: "https://www.fao.org/4/x5656e/x5656e05.htm", revisada: "2026-09-03" },
      { label: "FAO — conocimiento forestal Kalinago", url: "https://www.fao.org/4/x6689e/X6689E13.htm", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/centroamerica-caribe/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "milpa_maya_ich_kool",
    nombre: "Milpa maya / Ich Kool",
    region: "mexico-estados-unidos",
    portadores: "familias y comunidades mayas de la península de Yucatán.",
    paises: ["MX"],
    ecoIdsCompatibles: [494, 519, 551],
    territorioMinimo: "`MX` + Yucatán/Campeche/Quintana Roo + área maya documentada; ECO_ID frecuentes `494`, `519`, `551`.",
    sintesisPublica: "policultivo de maíz, frijoles, calabazas y especies locales articulado con solares, monte y fases de descanso; selección de semillas y lectura de lluvia, suelo y sucesión.",
    cautelas: [
      "no convertir la roza-quema en prescripción. Duración de descanso, fuego y especies dependen del sitio y la autoridad comunitaria.",
      "no presentar roza-quema como instrucción aislada. La fuente FAO destaca que el ciclo depende del descanso y del conocimiento local.",
    ],
    fuentes: [
      { label: "FAO GIAHS — Ich Kool", url: "https://www.fao.org/giahs/giahs-around-the-world/mexico-ich-kool-mayan-milpa-system/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "mx_chinampa_xochimilco",
    nombre: "Chinampa de Xochimilco–Tláhuac",
    region: "mexico-estados-unidos",
    portadores: "comunidades y familias chinamperas.",
    paises: ["MX"],
    ecoIdsCompatibles: [559],
    territorioMinimo: "polígono SIPAM de Xochimilco, Tláhuac y zona lacustre asociada; no alcanza con Ciudad de México ni ECO_ID `559`.",
    sintesisPublica: "camas elevadas construidas con sedimento y materia orgánica, red de canales, ahuejotes, riego y policultivo intensivo. El sistema enlaza producción, control hídrico y hábitat acuático.",
    cautelas: [
      "calidad del agua, subsidencia y urbanización condicionan cualquier consejo actual.",
    ],
    fuentes: [
      { label: "FAO GIAHS — Chinampas", url: "https://www.fao.org/giahs/giahs-around-the-world/mexico-chinampas-agricultural-system/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "mx_metepantle_tlaxcala",
    nombre: "Metepantle de Tlaxcala",
    region: "mexico-estados-unidos",
    portadores: "familias campesinas y comunidades nahuas de Tlaxcala.",
    paises: ["MX"],
    ecoIdsCompatibles: [559],
    territorioMinimo: "municipios del sitio SIPAM en zonas montañosas de Tlaxcala; ECO_ID habitual `559`.",
    sintesisPublica: "terrazas y franjas con maguey que frenan escorrentía y erosión, combinadas con maíz, frijol, calabaza, árboles y flora espontánea; conserva semillas y corredores.",
    cautelas: [
      "no generalizar medidas, pendientes ni densidades de maguey.",
    ],
    fuentes: [
      { label: "FAO GIAHS — Metepantle", url: "https://www.fao.org/giahs/giahs-around-the-world/mexico-meteplante/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "mx_agua_tehuacan_cuicatlan",
    nombre: "Tecnologías de agua de Tehuacán–Cuicatlán",
    region: "mexico-estados-unidos",
    portadores: "comunidades popolocas, nahuas, cuicatecas, mazatecas, mixtecas, ixcatecas y otras del valle, según localidad.",
    paises: ["MX"],
    ecoIdsCompatibles: [610],
    territorioMinimo: "polígono del sitio Patrimonio Mundial y comunidad identificada; ECO_ID `610`.",
    sintesisPublica: "larga historia de domesticación de plantas y manejo de agua mediante terrazas, canales, pozos, acueductos y presas adaptados a un valle árido biodiverso.",
    cautelas: [
      "no publicar ubicación de elementos arqueológicos ni conocimientos vivos sin autorización.",
    ],
    fuentes: [
      { label: "UNESCO — Tehuacán-Cuicatlán", url: "https://whc.unesco.org/en/list/1534", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "mx_bosque_comunal_sierra_norte_oaxaca",
    nombre: "Tequio y manejo forestal zapoteca de Sierra Norte",
    region: "mexico-estados-unidos",
    portadores: "comunidades zapotecas; la fuente ejemplifica San Pablo Macuiltianguis y Pueblos Mancomunados.",
    paises: ["MX"],
    ecoIdsCompatibles: [487, 557],
    territorioMinimo: "núcleos agrarios documentados de Sierra Norte de Oaxaca; ECO_ID probables `487`, `557`.",
    sintesisPublica: "asamblea comunal, tequio, monitoreo y decisiones colectivas organizan protección, restauración y aprovechamiento; los calendarios y actos de reciprocidad pertenecen a cada comunidad.",
    cautelas: [
      "no equiparar certificación forestal con consentimiento para difundir saberes.",
    ],
    fuentes: [
      { label: "CONAFOR — Pedir permiso al bosque", url: "https://www.gob.mx/conafor/articulos/pedir-permiso-al-bosque", revisada: "2026-09-03" },
      { label: "CONAFOR — Pueblos Mancomunados", url: "https://www.gob.mx/conafor/prensa/pueblos-mancomunados-de-oaxaca-ejemplo-de-aprovechamiento-forestal-sostenible", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "mx_milpa_regional",
    nombre: "Milpas regionales de México",
    region: "mexico-estados-unidos",
    portadores: "pueblos indígenas y comunidades campesinas según región.",
    paises: ["MX"],
    ecoIdsCompatibles: [],
    territorioMinimo: "comunidad o programa documentado; nunca `MX` completo.",
    sintesisPublica: "la milpa es un policultivo dinámico centrado en maíz y combinado con frijoles, calabazas, chiles, tomates, quelites, arbustos y árboles según ambiente. Conserva agrobiodiversidad y conocimiento intergeneracional.",
    cautelas: [
      "no reducirla a una receta fija de “tres hermanas”; nombres, especies, densidades y funciones varían.",
    ],
    fuentes: [
      { label: "CONABIO — La milpa", url: "https://www.biodiversidad.gob.mx/diversidad/sistemas-productivos/milpa", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "mx_silvicultura_comunitaria",
    nombre: "Silvicultura comunitaria y ejidal",
    region: "mexico-estados-unidos",
    portadores: "ejidos y comunidades forestales específicas.",
    paises: ["MX"],
    ecoIdsCompatibles: [],
    territorioMinimo: "núcleo agrario con programa de manejo y fuente verificable; útil en Sierras Madre, Eje Volcánico y Oaxaca.",
    sintesisPublica: "gobernanza comunal, ordenamiento, manejo maderable y no maderable, vigilancia y cadenas de valor pueden sostener bosque y economía local.",
    cautelas: [
      "es una categoría contemporánea amplia; no llamarla ancestral ni atribuir etnia sin fuente local.",
    ],
    fuentes: [
      { label: "CONAFOR — Silvicultura comunitaria", url: "https://www.gob.mx/conafor/documentos/silvicultura-comunitaria-27813", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "mx_caborachi_extension_comunitaria",
    nombre: "Caborachi y extensión forestal comunitaria",
    region: "mexico-estados-unidos",
    portadores: "Ejido Caborachi, Chihuahua.",
    paises: ["MX"],
    ecoIdsCompatibles: [326],
    territorioMinimo: "geometría del ejido o localidad documentada; ECO_ID probable `326`.",
    sintesisPublica: "intercambio “de ejidatario a ejidatario” para manejo forestal, biodiversidad y servicios ambientales.",
    cautelas: [
      "práctica contemporánea localizada; no inferir que representa a todo el pueblo Rarámuri ni a toda la Sierra Madre Occidental.",
    ],
    fuentes: [
      { label: "CONAFOR — De comunidad a comunidad", url: "https://www.gob.mx/conafor/articulos/de-comunidad-a-comunidad-de-ejidatario-a-ejidatario?idiom=es", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "us_three_sisters_local",
    nombre: "Agricultura de las Tres Hermanas",
    region: "mexico-estados-unidos",
    portadores: "naciones agrícolas específicas; la expresión tiene especial asociación Haudenosaunee y también variantes en otras regiones.",
    paises: ["US"],
    ecoIdsCompatibles: [],
    territorioMinimo: "nación/comunidad y proyecto documentado; no todo el este estadounidense.",
    sintesisPublica: "maíz, frijol y calabaza se cultivan como asociación biológica y cultural; cultivares, montículos, tiempos y significados dependen de la nación.",
    cautelas: [
      "la propia revisión de USDA advierte que mucha bibliografía no centró voces indígenas; usar solo como introducción.",
    ],
    fuentes: [
      { label: "USDA National Agricultural Library — Three Sisters", url: "https://www.nal.usda.gov/collections/stories/three-sisters", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "us_ojibwe_manoomin",
    nombre: "Manoomin y humedales de los Grandes Lagos",
    region: "mexico-estados-unidos",
    portadores: "naciones Anishinaabe/Ojibwe vinculadas con los lagos y humedales documentados.",
    paises: ["US"],
    ecoIdsCompatibles: [333, 334, 342, 344],
    territorioMinimo: "aguas de tratados o territorios tribales concretos de Grandes Lagos; ECO_ID frecuentes `333`, `334`, `342`, `344`.",
    sintesisPublica: "manoomin (arroz silvestre) es alimento, ser cultural y especie indicadora; su cuidado vincula hidrología, calidad del agua, cosecha, clima y gobernanza de tratados.",
    cautelas: [
      "no divulgar sitios de cosecha ni transformar protocolos culturales en instrucciones.",
    ],
    fuentes: [
      { label: "NPS — recursos de conocimiento indígena, región Central", url: "https://www.nps.gov/subjects/tek/central.htm", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "us_rivercane_cherokee_southeast",
    nombre: "Rivercane y canebrakes del Sudeste",
    region: "mexico-estados-unidos",
    portadores: "Cherokee y otras naciones del Sudeste según proyecto.",
    paises: ["US"],
    ecoIdsCompatibles: [329, 331, 336, 399],
    territorioMinimo: "restauración o comunidad documentada en Apalaches/Sudeste; ECO_ID frecuentes `329`, `331`, `336`, `399`.",
    sintesisPublica: "los canebrakes ribereños se mantuvieron con fuego y otros cuidados; estabilizan orillas y proveen hábitat y material culturalmente protegido.",
    cautelas: [
      "técnicas de cestería y sitios de recolección no son contenido abierto por defecto.",
    ],
    fuentes: [
      { label: "NPS — Rivercane", url: "https://home.nps.gov/articles/000/rivercane.htm", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "us_tribal_bison_restoration",
    nombre: "Restauración de bisonte y conexión tribal",
    region: "mexico-estados-unidos",
    portadores: "naciones de las Grandes Llanuras y proyectos tribales específicos.",
    paises: ["US"],
    ecoIdsCompatibles: [387, 402],
    territorioMinimo: "rebaño, reserva/refugio o convenio documentado; ECO_ID de praderas `387`–`402` según sitio.",
    sintesisPublica: "recuperación del rol ecológico del bisonte y de la relación cultural, con co-manejo y consulta temprana.",
    cautelas: [
      "no inferir carga, rotación o manejo sanitario a partir de la ficha.",
    ],
    fuentes: [
      { label: "U.S. Fish & Wildlife Service — Bison management policy", url: "https://www.fws.gov/policy-library/701fw8", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "us_pueblo_dryland_farming",
    nombre: "Agricultura de secano Pueblo",
    region: "mexico-estados-unidos",
    portadores: "Pueblos actuales vinculados con Pajarito Plateau/Río Grande y otras localidades documentadas.",
    paises: ["US"],
    ecoIdsCompatibles: [353, 428, 429],
    territorioMinimo: "comunidad/sitio del norte de Nuevo México; ECO_ID frecuentes `353`, `428`, `429`.",
    sintesisPublica: "selección de semilla, ubicación según escorrentía y microrelieve, policultivo y flexibilidad frente a heladas y lluvias variables sostienen agricultura de secano.",
    cautelas: [
      "el sitio arqueológico informa historia; las comunidades Pueblo vivas deben definir el uso contemporáneo.",
    ],
    fuentes: [
      { label: "NPS — Ancestral Pueblo Farming", url: "https://home.nps.gov/band/learn/historyculture/ancestral-pueblo-farming.htm", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "us_pinyon_juniper_cultural_landscape",
    nombre: "Piñón–enebro del Suroeste y Gran Cuenca",
    region: "mexico-estados-unidos",
    portadores: "múltiples naciones del Suroeste y Gran Cuenca.",
    paises: ["US"],
    ecoIdsCompatibles: [356, 429, 430, 438],
    territorioMinimo: "nación y proyecto documentado dentro de `356`, `429`, `430` o `438`.",
    sintesisPublica: "piñones y enebros tienen usos y significados culturales; el manejo debe distinguir arbolado antiguo, expansión reciente, pastizal y mosaicos históricos.",
    cautelas: [
      "la fuente resume comentarios; requiere co-producción con la tribu antes de recomendar remoción o fuego.",
    ],
    fuentes: [
      { label: "BLM — Pinyon and Juniper Woodlands comment summary", url: "https://www.blm.gov/sites/default/files/docs/2024-08/Management%20and%20Conservation%20of%20Pinyon%20and%20Juniper%20Woodlands%20Comment%20Summary%20Report.pdf", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "us_karuk_yurok_cultural_burning",
    nombre: "Fuego cultural Karuk y Yurok",
    region: "mexico-estados-unidos",
    portadores: "Karuk y Yurok, noroeste de California.",
    paises: ["US"],
    ecoIdsCompatibles: [357, 359],
    territorioMinimo: "cuencas y sitios de proyecto validados; ECO_ID frecuentes `357`, `359`.",
    sintesisPublica: "quema cultural de baja intensidad para renovar avellano y otros recursos, favorecer calidad de tallos y recomponer mosaicos de bosque/pradera.",
    cautelas: [
      "no publicar frecuencia, ventana meteorológica ni sitio como receta; el fuego exige autoridad tribal, legal y técnica.",
    ],
    fuentes: [
      { label: "USFS Research — Karuk and Yurok cultural burning", url: "https://research.fs.usda.gov/treesearch/62061", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "us_warm_springs_fire_huckleberry",
    nombre: "Fuego y huckleberry de Warm Springs",
    region: "mexico-estados-unidos",
    portadores: "Confederated Tribes of Warm Springs: Ichishkin, Wasco y Northern Paiute.",
    paises: ["US"],
    ecoIdsCompatibles: [352, 354],
    territorioMinimo: "área participativa documentada en Cascadas orientales de Oregon; ECO_ID frecuentes `352`, `354`.",
    sintesisPublica: "uso de fuego y cuidado de aperturas para huckleberry culturalmente importante, integrado con ronda estacional y principios tribales.",
    cautelas: [
      "los datos geoespaciales participativos y entrevistas no deben republicarse.",
    ],
    fuentes: [
      { label: "USFS Research — Warm Springs fire knowledge", url: "https://research.fs.usda.gov/treesearch/59061", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "us_nimiipuu_camas",
    nombre: "Camas y praderas del Noroeste",
    region: "mexico-estados-unidos",
    portadores: "Nimiipuu/Nez Perce y, en otras áreas, pueblos localmente documentados.",
    paises: ["US"],
    ecoIdsCompatibles: [398],
    territorioMinimo: "Weippe/Camas Prairie y sitios validados; ECO_ID frecuente `398`.",
    sintesisPublica: "cosecha cuidadosa que deja bulbos pequeños, mantenimiento de claros/praderas y transmisión de técnicas de preparación; el conocimiento Nimiipuu ya informa manejo del NPS.",
    cautelas: [
      "no señalar parches de recolección activos.",
    ],
    fuentes: [
      { label: "NPS — Camas", url: "https://home.nps.gov/articles/000/camas.htm", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "us_pacific_tribal_salmon_comanagement",
    nombre: "Salmón y co-manejo tribal del Pacífico",
    region: "mexico-estados-unidos",
    portadores: "tribus con derechos de tratado y otras naciones costeras/ribereñas específicas.",
    paises: ["US"],
    ecoIdsCompatibles: [],
    territorioMinimo: "cuenca y jurisdicción de co-manejo verificadas; ecorregiones costeras y fluviales del Pacífico.",
    sintesisPublica: "el salmón es alimento primordial y relación cultural; tribus participan como co-gestoras de cosecha, hábitat, criaderos y recuperación.",
    cautelas: [
      "derechos y datos de pesca son específicos de tratado, tribu, especie y agua.",
    ],
    fuentes: [
      { label: "NOAA — West Coast salmon management", url: "https://www.fisheries.noaa.gov/west-coast/sustainable-fisheries/west-coast-salmon-and-steelhead-fisheries-management", revisada: "2026-09-03" },
      { label: "NOAA — sovereign relations", url: "https://www.fisheries.noaa.gov/index.php/west-coast/partners/sovereign-relations-west-coast", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "us_alaska_native_lktks",
    nombre: "Subsistencia y conocimiento local/tradicional de Alaska",
    region: "mexico-estados-unidos",
    portadores: "comunidades y pueblos Alaska Native específicos.",
    paises: ["US"],
    ecoIdsCompatibles: [],
    territorioMinimo: "comunidad y proyecto de co-producción; no usar `US-AK` completo.",
    sintesisPublica: "observaciones intergeneracionales de hielo, ríos, peces, mamíferos y estacionalidad sostienen movilidad, intercambio y subsistencia; el cambio rápido exige adaptación dirigida por comunidades.",
    cautelas: [
      "nunca mostrar rutas, campamentos, ventanas de cosecha o abundancias localizadas sin permiso.",
    ],
    fuentes: [
      { label: "NOAA Fisheries — Multiple Knowledge Systems and Subsistence", url: "https://www.fisheries.noaa.gov/alaska/socioeconomics/multiple-knowledge-systems-and-subsistence", revisada: "2026-09-03" },
      { label: "Alaska DFG — local knowledge of Mulchatna caribou", url: "https://www.adfg.alaska.gov/index.cfm?adfg=wildlifenews.view_article&articles_id=864", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "us_hawaii_ahupuaa_moku",
    nombre: "Ahupuaʻa, moku y gobernanza biocultural hawaiana",
    region: "mexico-estados-unidos",
    portadores: "Kānaka Maoli y organizaciones comunitarias de cada moku/ahupuaʻa.",
    paises: ["US"],
    ecoIdsCompatibles: [623, 636, 639, 640, 641],
    territorioMinimo: "ahupuaʻa o moku documentado, no todo Hawái; ECO_ID `623`, `636`, `639`, `640`, `641` según sitio.",
    sintesisPublica: "manejo integrado de montaña a mar, relaciones genealógicas con ʻāina, restauración de cuencas, sistemas alimentarios y cuidado costero bajo gobernanza comunitaria.",
    cautelas: [
      "ahupuaʻa es unidad territorial y social, no etiqueta climática; respetar soberanía del conocimiento.",
    ],
    fuentes: [
      { label: "NOAA — Hawaiʻi Indigenous Knowledge", url: "https://sanctuaries.noaa.gov/bwet/hawaii/indigenous-knowledge.html", revisada: "2026-09-03" },
      { label: "NOAA — moku climate resilience", url: "https://www.coast.noaa.gov/states/stories/hawaii.html", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "us_everglades_miccosukee_seminole",
    nombre: "Paisaje vivo Miccosukee y Seminole de Everglades",
    region: "mexico-estados-unidos",
    portadores: "Miccosukee Tribe of Indians of Florida, Seminole Tribe of Florida y otras entidades culturalmente asociadas según consulta.",
    paises: ["US"],
    ecoIdsCompatibles: [581, 612],
    territorioMinimo: "sur de Florida y sitios documentados en Everglades/Big Cypress; ECO_ID `581` y localmente `612`.",
    sintesisPublica: "movilidad, residencia y uso tradicional se adaptan al pulso de inundación, islas de árboles, cipresales y canales; la alteración hidrológica transformó el paisaje y los modos de vida.",
    cautelas: [
      "no reconstruir usos de recursos ni sitios a partir de datos arqueológicos.",
    ],
    fuentes: [
      { label: "NPS — Native People of Everglades", url: "https://www.nps.gov/ever/learn/historyculture/native-people.htm", revisada: "2026-09-03" },
      { label: "NPS — Big Cypress foundation", url: "https://www.nps.gov/bicy/learn/management/foundation-overview.htm", revisada: "2026-09-03" },
      { label: "guía NOAA para incluir conocimiento indígena", url: "https://www.noaa.gov/sites/default/files/2024-05/NOAA_Indigenous%20Knowledge_Guidance_with_Appendix_FINAL_e-signed%205-17-24%20%282%29.pdf", revisada: "2026-09-03" },
      { label: "Indigenous Stewardship Methods and NRCS Conservation Practices", url: "https://www.nrcs.usda.gov/sites/default/files/2024-10/IndigenousStewardship.pdf", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-mesoamerica-norteamerica/insumos/mexico-estados-unidos/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "dehesa",
    nombre: "Dehesa",
    region: "europa-occidental",
    portadores: "Península ibérica",
    paises: ["ES"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Extremadura, Salamanca, Huelva, Sevilla, Córdoba — unidad mínima: comarca.",
    sintesisPublica: "Encinar y alcornocal pastoreado con bellota, corcho y cereal de secano.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "montado",
    nombre: "Montado",
    region: "europa-occidental",
    portadores: "Península ibérica",
    paises: ["PT"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Alentejo, Ribatejo, Algarve serrano — unidad mínima: distrito o concelho.",
    sintesisPublica: "El equivalente portugués, con más peso del corcho.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "careo_de_sierra_nevada",
    nombre: "Careo de Sierra Nevada",
    region: "europa-occidental",
    portadores: "Península ibérica",
    paises: ["ES"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Alpujarra granadina y almeriense — unidad mínima: cuenca de acequia.",
    sintesisPublica: "Acequias que infiltran agua de deshielo en cabecera para que aflore semanas después en manantiales aguas abajo. Reconocido como sistema histórico de recarga.",
    cautelas: [
      "es el saber europeo más directamente relevante para lo que la app calcula.",
    ],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "boqueras_y_riego_de_turbias",
    nombre: "Boqueras y riego de turbias",
    region: "europa-occidental",
    portadores: "Península ibérica",
    paises: ["ES"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Almería, Murcia, Alicante — unidad mínima: rambla.",
    sintesisPublica: "Derivación de la avenida de rambla hacia bancales para dejar agua y limo.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "huerta_de_valencia_y_tribunal_de_las_aguas",
    nombre: "Huerta de Valencia y Tribunal de las Aguas",
    region: "europa-occidental",
    portadores: "Península ibérica",
    paises: ["ES"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Vega del Turia — unidad mínima: acequia madre.",
    sintesisPublica: "Reparto por turnos con tribunal consuetudinario.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "bancales_de_la_ribeira_sacra_y_del_duero_vinatero",
    nombre: "Bancales de la Ribeira Sacra y del Duero vinatero",
    region: "europa-occidental",
    portadores: "Península ibérica",
    paises: ["ES", "PT"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Galicia interior, Douro portugués — unidad mínima: comarca.",
    sintesisPublica: "Viña en terrazas de pizarra sobre pendientes extremas.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "souto_y_minifundio_gallego",
    nombre: "Souto y minifundio gallego",
    region: "europa-occidental",
    portadores: "Península ibérica",
    paises: ["ES", "PT"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Galicia, norte de Portugal — unidad mínima: parroquia.",
    sintesisPublica: "Castañar de fruto, prado de siega, monte comunal en mano común.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "branas_y_pastos_de_montana_cantabricos",
    nombre: "Brañas y pastos de montaña cantábricos",
    region: "europa-occidental",
    portadores: "Península ibérica",
    paises: ["ES"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Asturias, Cantabria, León — unidad mínima: concejo.",
    sintesisPublica: "Trashumancia corta a pastos de altura.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "trashumancia_por_canadas_reales",
    nombre: "Trashumancia por cañadas reales",
    region: "europa-occidental",
    portadores: "Península ibérica",
    paises: ["ES"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Castilla, Extremadura, Aragón — unidad mínima: traza de cañada.",
    sintesisPublica: "Red de vías pecuarias con estatuto jurídico propio.",
    cautelas: [],
    fuentes: [],
    estado: "cartografia_oficial_sin_licencia",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "bocage_breton_y_normando",
    nombre: "Bocage bretón y normando",
    region: "europa-occidental",
    portadores: "Francia, Bélgica, Países Bajos, Luxemburgo",
    paises: ["FR"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Bretaña, Normandía, Mayenne — unidad mínima: departamento o país tradicional.",
    sintesisPublica: "Setos sobre talud, trasmochos, parcelas chicas.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "bocage_de_las_ardenas",
    nombre: "Bocage de las Ardenas",
    region: "europa-occidental",
    portadores: "Francia, Bélgica, Países Bajos, Luxemburgo",
    paises: ["BE", "FR", "LU"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Ardenas belgas y francesas, Luxemburgo — unidad mínima: comarca.",
    sintesisPublica: "Variante de altura, con más pastura permanente.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "hortillonnages_de_amiens",
    nombre: "Hortillonnages de Amiens",
    region: "europa-occidental",
    portadores: "Francia, Bélgica, Países Bajos, Luxemburgo",
    paises: ["FR"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Somme — unidad mínima: sitio.",
    sintesisPublica: "Huertas sobre islas entre canales en llanura aluvial.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "marais_y_wateringues",
    nombre: "Marais y wateringues",
    region: "europa-occidental",
    portadores: "Francia, Bélgica, Países Bajos, Luxemburgo",
    paises: ["FR", "BE", "NL"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Flandes marítimo, Pas-de-Calais, Zelanda — unidad mínima: cuenca de wateringue.",
    sintesisPublica: "Drenaje colectivo de marisma con juntas de agua históricas.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "polder_y_waterschap",
    nombre: "Polder y waterschap",
    region: "europa-occidental",
    portadores: "Francia, Bélgica, Países Bajos, Luxemburgo",
    paises: ["NL"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Países Bajos — unidad mínima: polder.",
    sintesisPublica: "Gestión colectiva del nivel freático por corporación de agua, con estatuto público desde el siglo XIII.",
    cautelas: [],
    fuentes: [],
    estado: "cartografia_oficial_sin_licencia",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "houtwallen_y_elzensingels",
    nombre: "Houtwallen y Elzensingels",
    region: "europa-occidental",
    portadores: "Francia, Bélgica, Países Bajos, Luxemburgo",
    paises: ["NL"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Drenthe, Achterhoek, Twente — unidad mínima: comarca.",
    sintesisPublica: "Bandas leñosas sobre camellón de tierra como límite, cortaviento y leña.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "essen_y_plaggenboden",
    nombre: "Essen y plaggenboden",
    region: "europa-occidental",
    portadores: "Francia, Bélgica, Países Bajos, Luxemburgo",
    paises: ["NL", "BE"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Drenthe, Veluwe, Campine — unidad mínima: comarca.",
    sintesisPublica: "Suelos antropogénicos construidos durante siglos con capas de brezo, arena y estiércol sobre podzol pobre.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "landes_y_pastoreo_del_brezal",
    nombre: "Landes y pastoreo del brezal",
    region: "europa-occidental",
    portadores: "Francia, Bélgica, Países Bajos, Luxemburgo",
    paises: ["FR", "BE"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Landas de Gascuña, Campine — unidad mínima: comarca.",
    sintesisPublica: "Manejo del brezal con pastoreo y quema controlada previo a la forestación masiva.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "downland_grazing_sobre_creta",
    nombre: "Downland grazing sobre creta",
    region: "europa-occidental",
    portadores: "Islas británicas e Irlanda",
    paises: ["GB"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Chilterns, North y South Downs — unidad mínima: cadena de colinas.",
    sintesisPublica: "Pastoreo ovino extensivo que sostiene el pastizal calcáreo.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "hedgerow_y_enclosure",
    nombre: "Hedgerow y enclosure",
    region: "europa-occidental",
    portadores: "Islas británicas e Irlanda",
    paises: ["GB"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Inglaterra y Gales — unidad mínima: condado.",
    sintesisPublica: "Setos de espino como límite legal, cortaviento y hábitat, con normativa de protección propia.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "ffridd_y_hafod_hendre_gales",
    nombre: "Ffridd y hafod-hendre galés",
    region: "europa-occidental",
    portadores: "Islas británicas e Irlanda",
    paises: ["GB"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Gales — unidad mínima: comarca.",
    sintesisPublica: "Movimiento estacional entre granja de valle y pasto de altura.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "machair",
    nombre: "Machair",
    region: "europa-occidental",
    portadores: "Islas británicas e Irlanda",
    paises: ["GB", "IE"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Hébridas Exteriores, costa oeste de Irlanda — unidad mínima: costa insular.",
    sintesisPublica: "Rotación de cebada y avena con descanso y pastoreo invernal sobre arena de conchilla. Extremadamente frágil.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "crofting",
    nombre: "Crofting",
    region: "europa-occidental",
    portadores: "Islas británicas e Irlanda",
    paises: ["GB"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Highlands e islas de Escocia — unidad mínima: crofting township.",
    sintesisPublica: "Tenencia pequeña regulada por ley propia, con pasto común.",
    cautelas: [],
    fuentes: [],
    estado: "cartografia_oficial_sin_licencia",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "corte_de_turba_domestica",
    nombre: "Corte de turba doméstica",
    region: "europa-occidental",
    portadores: "Islas británicas e Irlanda",
    paises: ["IE", "GB"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Irlanda, Escocia — unidad mínima: bog.",
    sintesisPublica: "Práctica de subsistencia histórica hoy en conflicto con la conservación de turbera.",
    cautelas: [
      "documentar, no recomendar; drenar turbera es contrario a lo que la app debería aconsejar.",
    ],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "muinteanas_y_campos_de_piedra_del_oeste_irlandes",
    nombre: "Muinteanas y campos de piedra del oeste irlandés",
    region: "europa-occidental",
    portadores: "Islas británicas e Irlanda",
    paises: ["IE"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Connemara, Aran, Burren — unidad mínima: comarca.",
    sintesisPublica: "Muros de piedra seca y suelos construidos con arena y algas.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "winterage_del_burren",
    nombre: "Winterage del Burren",
    region: "europa-occidental",
    portadores: "Islas británicas e Irlanda",
    paises: ["IE"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Clare — unidad mínima: comarca.",
    sintesisPublica: "Pastoreo invertido: el ganado sube a la caliza en invierno y baja en verano, al revés de la trashumancia alpina.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "bisses_del_valais",
    nombre: "Bisses del Valais",
    region: "europa-occidental",
    portadores: "Suiza occidental",
    paises: ["CH"],
    ecoIdsCompatibles: [],
    territorioMinimo: "Valais — unidad mínima: cuenca de bisse.",
    sintesisPublica: "Canales de gravedad en ladera con turnos comunitarios. Ya está recogido en `alpino_montano_europeo` vía la inscripción de UNESCO sobre riego tradicional; conviene moverlo a esta capa cuando exista.",
    cautelas: [],
    fuentes: [],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-europa-occidental/CAPAS_CULTURALES_LOCALES.md",
  },
  {
    id: "chakra_amazonica_napo",
    nombre: "Chakra amazónica de Napo",
    region: "sudamerica",
    portadores: "Comunidades Kichwa amazónicas; liderazgo de chakramamas",
    paises: ["EC"],
    ecoIdsCompatibles: [483],
    territorioMinimo: "Provincia de Napo, únicamente predios y comunidades del sistema SIPAM documentado",
    sintesisPublica: "Sistema agroforestal familiar diverso que integra cultivos alimentarios, árboles, especies forestales y regeneración; conserva agrobiodiversidad y continuidad entre casa, chakra y bosque.",
    cautelas: [
      "No inferir composición, medicina, rituales ni calendarios. Usar el polígono oficial del SIPAM y atribución comunitaria.",
    ],
    fuentes: [
      { label: "FAO GIAHS — Amazonian Chakra", url: "https://www.fao.org/giahs/giahs-around-the-world/ecuador-amazonian-chakra/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "aja_shuar_amazonia_ecuatoriana",
    nombre: "Aja Shuar",
    region: "sudamerica",
    portadores: "Mujeres y comunidades Shuar",
    paises: ["EC"],
    ecoIdsCompatibles: [505],
    territorioMinimo: "Comunidades Shuar participantes del sur-centro amazónico ecuatoriano",
    sintesisPublica: "Huerto o sistema agroforestal biodiverso asociado a producción alimentaria, regeneración de suelo, polinizadores y cuidado territorial.",
    cautelas: [
      "La fuente documenta participantes concretos, no todo el pueblo Shuar. No publicar plantas medicinales, rituales ni localizaciones sensibles.",
    ],
    fuentes: [
      { label: "FAO — Guardianes del saber, la tierra y los alimentos", url: "https://www.fao.org/americas/news/stories/detail/guardianes-del-saber/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "chakra_andina_cotacachi",
    nombre: "Chakra andina de Cotacachi",
    region: "sudamerica",
    portadores: "Comunidades Kichwa de Cotacachi; mujeres agricultoras",
    paises: ["EC"],
    ecoIdsCompatibles: [486, 593],
    territorioMinimo: "Cantón Cotacachi, sitios reconocidos por el SIPAM entre aproximadamente 2.500 y 3.400 m",
    sintesisPublica: "Sistema agrícola diverso que conecta pisos altitudinales y conserva variedades locales mediante parcelas familiares, redes de semillas y organización comunitaria.",
    cautelas: [
      "No extender a todos los Andes ecuatorianos ni publicar calendarios rituales. La delimitación SIPAM manda sobre ECO_ID.",
    ],
    fuentes: [
      { label: "FAO GIAHS — Chakra andina de Cotacachi", url: "https://www.fao.org/giahs/around-the-world/detail/ecuador-andean-chakra/es", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "agricultura_andina_cusco_puno",
    nombre: "Agricultura andina de Cusco y Puno",
    region: "sudamerica",
    portadores: "Comunidades Quechua y Aymara del corredor SIPAM",
    paises: ["PE"],
    ecoIdsCompatibles: [493, 587, 588, 589],
    territorioMinimo: "Microcuencas SIPAM de Cusco y Puno en el transecto Machu Picchu–Vilcanota–La Raya–Titicaca",
    sintesisPublica: "Manejo complementario de pisos, terrazas, campos elevados, pequeños reservorios y rotaciones comunales; conserva cultivos y variedades altoandinas.",
    cautelas: [
      "No convertir técnicas en receta universal ni trasladarlas fuera del sitio. Omitir sitios sagrados, rituales y calendarios.",
    ],
    fuentes: [
      { label: "FAO GIAHS — Andean Agriculture, Peru", url: "https://www.fao.org/giahs/giahs-around-the-world/peru-andean-agriculture/20th-anniversary-celebrations-of-the-globally-important-agricultural-heritage-systems-%28giahs%29-programme/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "sistema_camellidos_norte_chile",
    nombre: "Ganadería camélida y agricultura altoandina del norte de Chile",
    region: "sudamerica",
    portadores: "Comunidades Aymara, Quechua y Likan Antay",
    paises: ["CL"],
    ecoIdsCompatibles: [587, 588, 598],
    territorioMinimo: "Sitios SIPAM de Arica y Parinacota, Tarapacá y Antofagasta, aproximadamente 3.000–4.500 m",
    sintesisPublica: "Integra camélidos, cultivos andinos y gestión comunitaria del agua con movilidad estacional adaptada a ambientes altoandinos áridos.",
    cautelas: [
      "No publicar rutas de trashumancia, vertientes ni normas consuetudinarias. No prescribir carga animal o riego fuera del sistema.",
    ],
    fuentes: [
      { label: "FAO GIAHS — sistema altoandino del norte de Chile", url: "https://www.fao.org/giahs/giahs-around-the-world/chile-high-andean-camelids-system/es", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "sistema_pehuenche_ngulumapu",
    nombre: "Sistema ancestral Pehuenche del Ngulumapu",
    region: "sudamerica",
    portadores: "Comunidades Mapuche-Pehuenche y familias campesinas participantes",
    paises: ["CL"],
    ecoIdsCompatibles: [563, 595],
    territorioMinimo: "Sitios SIPAM de la cordillera Pehuenche en el sur de Chile",
    sintesisPublica: "Integra huertas familiares, recolección vinculada al pewen y ganadería trashumante en un paisaje de bosque y montaña.",
    cautelas: [
      "No publicar lugares de recolección, veranadas, plantas medicinales ni prácticas ceremoniales. Exige polígono SIPAM.",
    ],
    fuentes: [
      { label: "FAO GIAHS — sistema Pehuenche", url: "https://www.fao.org/giahs/giahs-around-the-world/chile-andean-pehuenche-system/es", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "agricultura_chiloe",
    nombre: "Agricultura de Chiloé",
    region: "sudamerica",
    portadores: "Familias agricultoras chilotas y comunidades locales del sistema SIPAM",
    paises: ["CL"],
    ecoIdsCompatibles: [563],
    territorioMinimo: "Sitios SIPAM del archipiélago de Chiloé",
    sintesisPublica: "Sistema insular diversificado centrado en variedades locales de papa, huertas y pequeña ganadería, sostenido por selección campesina e intercambio.",
    cautelas: [
      "No activar para todo el bosque valdiviano ni publicar material genético o conocimiento no autorizado.",
    ],
    fuentes: [
      { label: "FAO GIAHS — Chiloé Agriculture", url: "https://www.fao.org/giahs/giahs-around-the-world/chile-chiloe-agriculture/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "erva_mate_sombreada_parana",
    nombre: "Erva-mate sombreada en bosque de araucaria",
    region: "sudamerica",
    portadores: "Pueblos indígenas y comunidades tradicionales del sistema GIAHS de Paraná",
    paises: ["BR"],
    ecoIdsCompatibles: [440],
    territorioMinimo: "Polígono GIAHS del sistema de erva-mate sombreada en Paraná",
    sintesisPublica: "Agroforestería bajo dosel nativo que integra erva-mate, alimentos, frutos y regeneración del bosque de araucaria.",
    cautelas: [
      "No trasladar a toda la Mata Atlántica. No publicar reglas internas, semillas o prácticas ceremoniales sin consentimiento.",
    ],
    fuentes: [
      { label: "FAO GIAHS — shade-grown Erva-mate", url: "https://www.fao.org/giahs/giahs-around-the-world/brazil-erva-mate/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "apanhadores_sempre_vivas",
    nombre: "Sistema de apanhadores de flores sempre-vivas",
    region: "sudamerica",
    portadores: "Comunidades apanhadoras de flores sempre-vivas representadas por CODECEX",
    paises: ["BR"],
    ecoIdsCompatibles: [566],
    territorioMinimo: "Seis comunidades y áreas de uso común del sistema GIAHS en Espinhaço Meridional, Minas Gerais",
    sintesisPublica: "Combina recolección manejada, pastoreo estacional en tierras comunes, huertas agroforestales y cultivos de secano a diferentes altitudes.",
    cautelas: [
      "No publicar poblaciones de flores, recorridos ni técnicas finas de extracción. La geometría comunitaria y los derechos de uso son obligatorios.",
    ],
    fuentes: [
      { label: "FAO GIAHS — Espinhaço Meridional", url: "https://www.fao.org/giahs/giahs-around-the-world/brazil-minas-gerais-agricultural-system/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "quebradeiras_coco_babacu",
    nombre: "Quebradeiras de coco babaçu",
    region: "sudamerica",
    portadores: "Movimento Interestadual das Quebradeiras de Coco Babaçu y comunidades asociadas",
    paises: ["BR"],
    ecoIdsCompatibles: [540, 508, 518],
    territorioMinimo: "Comunidades documentadas en Maranhão, Tocantins, Pará y Piauí; no todo el ECO_ID",
    sintesisPublica: "Recolección y transformación integral del babaçu sostenida por conocimiento intergeneracional, organización de mujeres y defensa del acceso a palmares.",
    cautelas: [
      "No inferir derechos de acceso por presencia de palmas. Exige territorios y organizaciones reconocidas; no publicar sitios de recolección.",
    ],
    fuentes: [
      { label: "FAO Brasil — quebradeiras de coco y organización", url: "https://www.fao.org/brasil/noticias/detail-events/en/c/1156038/", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "chagra_amazonia_colombiana",
    nombre: "Chagra amazónica colombiana",
    region: "sudamerica",
    portadores: "Familias y comunidades indígenas documentadas por cada proyecto",
    paises: ["CO"],
    ecoIdsCompatibles: [446, 473, 483, 503],
    territorioMinimo: "Comunidad fuente y su área de uso autorizada en Amazonas, Caquetá, Guainía, Guaviare, Putumayo o Vaupés",
    sintesisPublica: "Sistema agroforestal de cultivos diversos, barbechos manejados y regeneración forestal; su composición y significado dependen de cada pueblo y comunidad.",
    cautelas: [
      "No usar “chagra” como receta panamazónica. Exige fuente y consentimiento por comunidad; omitir medicina, rituales y variedades sensibles.",
    ],
    fuentes: [
      { label: "FAO GLIS — chagra de una comunidad amazónica colombiana", url: "https://glis.fao.org/glis/csures/326", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "gobernanza_indigena_bosque_colombia",
    nombre: "Gobernanza indígena de bosques amazónicos",
    region: "sudamerica",
    portadores: "Organizaciones y pueblos que priorizaron proyectos del programa Visión Amazonía",
    paises: ["CO"],
    ecoIdsCompatibles: [446, 473, 483, 503],
    territorioMinimo: "Los 69 proyectos acordados en seis departamentos, sólo una vez disponibles sus polígonos públicos autorizados",
    sintesisPublica: "Iniciativas definidas autónomamente para gobernanza territorial, manejo forestal y bienestar, integrando conocimientos tradicionales y conservación.",
    cautelas: [
      "La página no autoriza publicar límites internos ni contenidos de cada proyecto. No activar hasta contar con geometría y atribución del proponente.",
    ],
    fuentes: [
      { label: "FAO Colombia — proyectos indígenas y manejo forestal", url: "https://www.fao.org/in-action/redd-rbp-colombia/indigenous-peoples-and-forest-management/indigenous-projects/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "bioay_ashaninka_yanesha",
    nombre: "Gestión biocultural en Oxapampa–Asháninka–Yánesha",
    region: "sudamerica",
    portadores: "Pueblos Asháninka y Yánesha y comunidades de la reserva de biosfera",
    paises: ["PE"],
    ecoIdsCompatibles: [493, 512],
    territorioMinimo: "Reserva de Biosfera Oxapampa–Asháninka–Yánesha, según zonificación oficial pública",
    sintesisPublica: "Gestión de paisaje que articula conocimiento indígena y local, conservación de bosque y medios de vida en gradientes andino-amazónicos.",
    cautelas: [
      "No atribuir una práctica única a ambos pueblos ni publicar sitios culturales. Activar sólo con la zonificación oficial pertinente.",
    ],
    fuentes: [
      { label: "UNESCO — Amazon Biosphere Reserves Project, Peru", url: "https://www.unesco.org/en/amazon-biosphere-reserves-project/peru", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "tacana_gestion_territorial",
    nombre: "Gestión territorial Tacana",
    region: "sudamerica",
    portadores: "Pueblo Tacana y organizaciones participantes",
    paises: ["BO"],
    ecoIdsCompatibles: [505, 565],
    territorioMinimo: "Comunidades Tacana del proyecto citado por FAO, con geometría provista por su organización",
    sintesisPublica: "La fuente documenta conservación de biodiversidad, seguridad alimentaria y medios de vida dentro de una visión de territorio, cultura y transmisión intergeneracional.",
    cautelas: [
      "No extrapolar al conjunto del ECO_ID ni revelar recursos, senderos o sitios sensibles.",
    ],
    fuentes: [
      { label: "FAO — Guardianes del saber, la tierra y los alimentos", url: "https://www.fao.org/americas/news/stories/detail/guardianes-del-saber/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "pemon_gran_sabana",
    nombre: "Conocimiento territorial Pemón en Gran Sabana",
    region: "sudamerica",
    portadores: "Comunidades Pemón participantes del proyecto citado por FAO",
    paises: ["VE"],
    ecoIdsCompatibles: [570, 464],
    territorioMinimo: "Comunidad y territorio participante en Gran Sabana, estado Bolívar",
    sintesisPublica: "Conservación y producción local vinculadas a paisaje de sabana y bosque, con conocimiento transmitido entre generaciones.",
    cautelas: [
      "No publicar patrones de quema, sitios sagrados, recursos medicinales ni ubicación de especies. La fuente es testimonial, no un manual.",
    ],
    fuentes: [
      { label: "FAO — Guardianes del saber, la tierra y los alimentos", url: "https://www.fao.org/americas/news/stories/detail/guardianes-del-saber/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "macushi_iwokrama_rupununi",
    nombre: "Manejo Macushi en Iwokrama y Rupununi",
    region: "sudamerica",
    portadores: "Comunidades Macushi vinculadas a Iwokrama y áreas vecinas",
    paises: ["GY"],
    ecoIdsCompatibles: [465, 570],
    territorioMinimo: "Iwokrama Forest y territorios comunitarios con autorización; no toda la sabana Rupununi",
    sintesisPublica: "Gobernanza y uso sostenible del bosque articulados con conservación, investigación y beneficios comunitarios.",
    cautelas: [
      "No inferir usos culturales de toda persona Macushi. Exige límites comunitarios y acuerdo de la institución o comunidad.",
    ],
    fuentes: [
      { label: "Guyana Protected Areas Commission — Iwokrama", url: "https://www.pac.gov.gy/our-work/", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "patamona_kaieteur",
    nombre: "Relación territorial Patamona en Kaieteur",
    region: "sudamerica",
    portadores: "Comunidades Patamona",
    paises: ["GY"],
    ecoIdsCompatibles: [464, 466],
    territorioMinimo: "Entorno cultural documentado de Kaieteur con límites públicos no sensibles",
    sintesisPublica: "La fuente oficial reconoce dependencia histórica, cultural y de medios de vida en el paisaje de tierras altas y bosques.",
    cautelas: [
      "No publicar sitios sagrados ni senderos tradicionales. La fuente no ofrece prácticas agrícolas transferibles.",
    ],
    fuentes: [
      { label: "Guyana Protected Areas Commission", url: "https://www.pac.gov.gy/", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "ip_lc_suriname_conservacion",
    nombre: "Conservación indígena y local en Surinam",
    region: "sudamerica",
    portadores: "Comunidades indígenas y locales participantes de iniciativas FAO documentadas",
    paises: ["SR"],
    ecoIdsCompatibles: [465, 463, 570],
    territorioMinimo: "Comunidades participantes identificadas por la organización ejecutora",
    sintesisPublica: "Acciones de conservación, seguridad alimentaria e ingresos que se apoyan en conocimiento territorial y transmisión intergeneracional.",
    cautelas: [
      "No asumir homogeneidad entre pueblos o comunidades; sin polígono y atribución específica permanece sólo como inventario.",
    ],
    fuentes: [
      { label: "FAO — Guardianes del saber, la tierra y los alimentos", url: "https://www.fao.org/americas/news/stories/detail/guardianes-del-saber/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "kayapo_islas_bosque",
    nombre: "Enriquecimiento de bosque por comunidades Kayapó",
    region: "sudamerica",
    portadores: "Comunidades Kayapó citadas por la literatura FAO",
    paises: ["BR"],
    ecoIdsCompatibles: [507, 518, 567],
    territorioMinimo: "Tierras indígenas Kayapó donde la comunidad confirme continuidad y publicación del conocimiento",
    sintesisPublica: "Manejo y enriquecimiento de áreas forestales con especies útiles, descrito como parte de sistemas amazónicos de recursos comunes.",
    cautelas: [
      "Fuente histórica y secundaria: requiere validación contemporánea. No publicar especies, técnicas, sitios o calendarios como receta.",
    ],
    fuentes: [
      { label: "FAO — Common forest resource management", url: "https://www.fao.org/4/u9040e/u9040e13.htm", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "ribeirinhos_varzea_amazonica",
    nombre: "Manejo ribereño de várzeas y productos forestales",
    region: "sudamerica",
    portadores: "Comunidades ribeirinhas o caboclas documentadas localmente",
    paises: ["BR"],
    ecoIdsCompatibles: [467, 480, 482, 496],
    territorioMinimo: "Comunidad y tramo de várzea documentados; nunca toda la cuenca",
    sintesisPublica: "Sistemas diversificados que combinan pesca, cultivos de pulso fluvial, árboles y productos no maderables en mosaicos de inundación.",
    cautelas: [
      "La fuente es regional e histórica. Exige verificación actual, polígono comunitario y reglas de acceso; no publicar pesqueros o plantas medicinales.",
    ],
    fuentes: [
      { label: "FAO Unasylva — Amazon forest dwellers", url: "https://www.fao.org/4/w1033e/w1033e04.htm", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "yanesha_bora_barbeco_manejado",
    nombre: "Continuo chacra–barbecho manejado en Amazonía peruana",
    region: "sudamerica",
    portadores: "Comunidades Yánesha/Amuesha y Bora citadas por la fuente",
    paises: ["PE"],
    ecoIdsCompatibles: [469, 493, 512],
    territorioMinimo: "Palcazú para Yánesha/Amuesha y comunidades Bora cercanas a Iquitos, según fuente y validación local",
    sintesisPublica: "La parcela continúa siendo manejada durante el barbecho mediante combinación de cultivos anuales, árboles perennes y regeneración natural.",
    cautelas: [
      "Documento antiguo; confirmar vigencia y autodenominación. No trasladar especies o duraciones de barbecho fuera de la comunidad.",
    ],
    fuentes: [
      { label: "FAO — Common forest resource management", url: "https://www.fao.org/4/u9040e/u9040e13.htm", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "pantaneiros_manejo_paisaje",
    nombre: "Conocimiento territorial pantaneiro",
    region: "sudamerica",
    portadores: "Comunidades tradicionales pantaneiras reconocidas oficialmente",
    paises: ["BR"],
    ecoIdsCompatibles: [584],
    territorioMinimo: "Comunidades Barra de São Lourenço, Amolar u otras con reconocimiento y polígono autorizado",
    sintesisPublica: "Conocimiento situado del pulso de inundación, movilidad y uso múltiple del paisaje pantanero para sostener medios de vida.",
    cautelas: [
      "La fuente sustenta portadores y territorio, no una receta. No publicar rutas, pesqueros, niveles de agua ni calendarios.",
    ],
    fuentes: [
      { label: "CNDH Brasil — comunidades tradicionales pantaneiras", url: "https://www.gov.br/mdh/pt-br/acesso-a-informacao/participacao-social/conselho-nacional-de-direitos-humanos-cndh/RELATRIOSOBREOSDIREITOSDOSPOVOSECOMUNIDADESTRADICIONAISv2.pdf", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "wichi_monte_chaco",
    nombre: "Conocimiento Wichí del monte y alimentos",
    region: "sudamerica",
    portadores: "Comunidades Wichí participantes del proyecto Wichí Lahäk",
    paises: ["AR"],
    ecoIdsCompatibles: [569],
    territorioMinimo: "Comunidades participantes del norte de Salta y Formosa, según consentimiento del proyecto",
    sintesisPublica: "Conocimiento colectivo sobre alimentos del monte y río, documentado mediante diálogo intercultural para transmisión comunitaria.",
    cautelas: [
      "El calendario cultural pertenece a las comunidades: no copiar fechas, sitios, recetas ni plantas medicinales. Mostrar sólo una síntesis atribuida.",
    ],
    fuentes: [
      { label: "INTA — Wichí Lahäk", url: "https://intainforma.inta.gob.ar/wichi-lahak-el-calendario-cultural-para-rescatar-y-revalorizar-saberes-ancestrales/", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "guarani_erva_mate_bosque",
    nombre: "Agroforestería de yerba mate bajo bosque",
    region: "sudamerica",
    portadores: "Pueblos indígenas y comunidades tradicionales participantes del GIAHS; validar específicamente presencia Guaraní",
    paises: ["BR"],
    ecoIdsCompatibles: [439, 440],
    territorioMinimo: "Polígono GIAHS de Paraná y comunidades identificadas por el expediente",
    sintesisPublica: "Cultivo sombreado y regeneración de bosque que integra yerba mate con alimentos y especies nativas.",
    cautelas: [
      "No etiquetar automáticamente como Guaraní sin fuente comunitaria. No extender al Alto Paraná argentino o paraguayo sin investigación local.",
    ],
    fuentes: [
      { label: "FAO GIAHS — shade-grown Erva-mate", url: "https://www.fao.org/giahs/giahs-around-the-world/brazil-erva-mate/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "caatingueiros_fundos_pasto",
    nombre: "Sistemas territoriales de Caatingueiros y Fundos de Pasto",
    region: "sudamerica",
    portadores: "Comunidades caatingueiras y de fundos e fechos de pasto reconocidas por el Estado brasileño",
    paises: ["BR"],
    ecoIdsCompatibles: [525, 445],
    territorioMinimo: "Territorios tradicionales reconocidos o polígonos provistos por sus asociaciones en el semiárido",
    sintesisPublica: "Uso comunitario y familiar situado de la Caatinga y áreas de pastoreo, asociado a identidad territorial y conocimiento de ciclos semiáridos.",
    cautelas: [
      "La fuente reconoce sujetos de derecho, no describe técnicas. Antes de publicar prácticas hace falta fuente comunitaria específica.",
    ],
    fuentes: [
      { label: "MDA Brasil — pueblos y comunidades tradicionales", url: "https://www.gov.br/mda/pt-br/acesso-a-informacao/acoes-e-programas/programas-projetos-acoes-obras-e-atividades/programa-de-apoio-ao-acesso-a-terra-e-ao-territorio-e-a-protecao-socioterritorial-de-povos-e-comunidades-tradicionais-territorio-tradicional/quem-pode-acessar", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "ganaderia_familiar_campo_natural_uruguay",
    nombre: "Conocimiento local de ganadería familiar sobre campo natural",
    region: "sudamerica",
    portadores: "Productores y productoras familiares participantes del Proyecto Pastizales",
    paises: ["UY"],
    ecoIdsCompatibles: [574],
    territorioMinimo: "Zonas piloto del norte y sudeste de Uruguay documentadas por FAO/MGAP/MA",
    sintesisPublica: "Evaluación participativa y manejo adaptativo del campo natural a escala de predio y paisaje, combinando experiencia local y conocimiento técnico.",
    cautelas: [
      "No presentar como saber indígena ni como receta ganadera universal. Exige identificar zona piloto y familia o colectivo participante.",
    ],
    fuentes: [
      { label: "FAO Uruguay — mejores prácticas sobre campo natural", url: "https://www.fao.org/uruguay/noticias/detail/es/c/1604855/", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "concheras_manglar_ecuador",
    nombre: "Recolección artesanal de concha en manglares ecuatorianos",
    region: "sudamerica",
    portadores: "Asociaciones y comunidades manglar-dependientes documentadas en la fuente",
    paises: ["EC"],
    ecoIdsCompatibles: [615],
    territorioMinimo: "Áreas de custodia y comunidades de San Lorenzo, estuario de Cojimíes, Golfo de Guayaquil o Hualtaco según expediente autorizado",
    sintesisPublica: "Pesquería artesanal con derechos de acceso y conocimiento ecológico local de estuarios y manglares.",
    cautelas: [
      "No publicar bancos de concha, tallas locales, rutas ni calendarios. Usar sólo áreas de custodia públicas y autorización de la asociación.",
    ],
    fuentes: [
      { label: "FAO — Rights-based Approaches in Ecuador’s Fishery for Mangrove Cockles", url: "https://www.fao.org/fishery/static/tenure-user-rights/root/volume1/C3%20Rights-based%20Approaches%20in%20Ecuador%E2%80%99s%20Fishery%20for%20Mangrove%20Cockles%20.pdf", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "pesca_artesanal_orinoco_amazonia_colombia",
    nombre: "Pesca artesanal y de subsistencia en Orinoco y Amazonía colombiana",
    region: "sudamerica",
    portadores: "Comunidades indígenas y ribereñas y organizaciones de pesca artesanal",
    paises: ["CO"],
    ecoIdsCompatibles: [446, 473, 583],
    territorioMinimo: "Cuenca, comunidad y organización participante del plan nacional de pesca a pequeña escala",
    sintesisPublica: "Sistemas de pesca de importancia cultural y alimentaria articulados a ríos y pulsos hidrológicos.",
    cautelas: [
      "No publicar pesqueros, temporadas, artes, especies sensibles ni reglas de captura. El ECO_ID no demuestra pertenencia a una comunidad.",
    ],
    fuentes: [
      { label: "FAO — pesca a pequeña escala en Colombia", url: "https://www.fao.org/voluntary-guidelines-small-scale-fisheries/in-action/where-we-work/colombia/en", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
  {
    id: "caiçaras_manglar_restinga_brasil",
    nombre: "Conocimiento territorial caiçara y pesquero artesanal",
    region: "sudamerica",
    portadores: "Comunidades caiçaras, pescadores artesanales y extrativistas costeros reconocidos oficialmente",
    paises: ["BR"],
    ecoIdsCompatibles: [441, 500, 616],
    territorioMinimo: "Territorios tradicionales reconocidos y asociaciones costeras con polígono autorizado",
    sintesisPublica: "Inventario de portadores vinculados a mosaicos de restinga, Mata Atlántica y estuario; las prácticas concretas deben documentarse comunidad por comunidad.",
    cautelas: [
      "No inferir pesca, agricultura o recolección desde la etiqueta caiçara. La fuente reconoce colectivos, no autoriza divulgar conocimiento.",
    ],
    fuentes: [
      { label: "MDA Brasil — pueblos y comunidades tradicionales", url: "https://www.gov.br/mda/pt-br/acesso-a-informacao/acoes-e-programas/programas-projetos-acoes-obras-e-atividades/programa-de-apoio-ao-acesso-a-terra-e-ao-territorio-e-a-protecao-socioterritorial-de-povos-e-comunidades-tradicionais-territorio-tradicional/quem-pode-acessar", revisada: "2026-09-03" },
    ],
    estado: "documentado_sin_geometria",
    fuenteInventario: "_research/ecosistemas-saberes-sudamerica/fase-2-saberes-territoriales/inventario-saberes-documentados.json",
  },
];
