import Link from 'next/link';
import { requireUser } from '@/lib/auth/session';

export const metadata = { title: 'Guía de uso y fuentes' };

const dimensions = [
  ['Relieve', 'Reconocer pendientes, cotas, formas y recorridos posibles del agua.', 'Se cruza con agua, suelo, exposición y diseño.', 'La resolución cambia por país y disponibilidad. La fuente activa aparece junto al resultado.'],
  ['Agua', 'Orientar escorrentía, captación, infiltración, cuencas y reservorios preliminares.', 'Se cruza con relieve, suelo, cobertura y tormenta de diseño.', 'No reemplaza cálculo hidráulico, aforo ni verificación de campo.'],
  ['Clima', 'Reconocer patrones históricos de lluvia, temperatura, heladas, radiación y viento.', 'Se cruza con orientación, agua, vegetación y calendario.', 'Los datos de grilla no sustituyen una estación local bien mantenida.'],
  ['Suelo', 'Anticipar textura, agua útil, infiltración y restricciones posibles.', 'Se cruza con relieve, agua, cobertura y uso productivo.', 'Una estimación remota no reemplaza calicata, análisis de laboratorio ni observación local.'],
  ['Contexto', 'Reconocer coberturas, accesos, ecorregión, biodiversidad observada y relaciones territoriales.', 'Se cruza con todas las dimensiones del predio.', 'La cobertura y actualidad varían mucho según la región.'],
];

export default async function GuidePage() {
  await requireUser();
  return <main className="min-h-screen bg-bone-50 px-4 py-10"><div className="mx-auto max-w-5xl"><header className="mb-10 flex flex-wrap items-center justify-between gap-4"><img src="/marca/logo-color.png" alt="acequia" width={1200} height={395} className="h-9 w-auto" /><div className="flex gap-4 text-sm"><Link href="/bienvenida" className="text-moss-700 hover:underline">Primeros pasos</Link><Link href="/mapa" className="text-moss-700 hover:underline">Volver al mapa</Link></div></header><section className="max-w-3xl"><p className="eyebrow">Manual dentro de la aplicación</p><h1 className="mt-3 font-display text-4xl leading-tight text-ink-950 md:text-5xl">Cómo interpretar una lectura territorial.</h1><p className="mt-5 text-base leading-relaxed text-ink-700/75">Acequia trabaja con datos globales y, cuando existen, fuentes regionales de mayor detalle. Cada resultado debe leerse junto con su fuente activa, fecha, escala, confianza y límites.</p></section><section className="mt-10 grid gap-4 md:grid-cols-2">{dimensions.map(([title, use, cross, limit]) => <article key={title} className="rounded-2xl border border-bone-200 bg-white p-6"><h2 className="font-display text-2xl text-ink-950">{title}</h2><dl className="mt-5 space-y-4 text-sm"><div><dt className="font-semibold text-water-700">Para qué se usa</dt><dd className="mt-1 leading-relaxed text-ink-700/70">{use}</dd></div><div><dt className="font-semibold text-water-700">Cómo se cruza</dt><dd className="mt-1 leading-relaxed text-ink-700/70">{cross}</dd></div><div><dt className="font-semibold text-water-700">Qué verificar</dt><dd className="mt-1 leading-relaxed text-ink-700/70">{limit}</dd></div></dl></article>)}</section><section className="mt-10 rounded-2xl bg-ink-950 p-7 text-bone-50 md:p-9"><p className="eyebrow !text-water-300">Trazabilidad</p><h2 className="mt-3 font-display text-3xl">La fuente exacta acompaña al dato.</h2><p className="mt-3 max-w-3xl text-sm leading-relaxed text-bone-50/70">En el mapa y el informe se muestra el proveedor efectivamente utilizado. Para relieve, Acequia puede elegir automáticamente un modelo global o una fuente nacional disponible; también podés importar un modelo propio. El mismo criterio de trazabilidad se aplica a clima, suelo, cobertura y contexto.</p></section><section className="mt-8 flex flex-wrap gap-3"><Link href="/mapa" className="rounded-lg bg-moss-700 px-5 py-3 text-sm font-semibold text-white hover:bg-moss-900">Aplicarlo en el mapa</Link><a href="mailto:info@arteytierra.org?subject=Consulta%20sobre%20una%20fuente%20de%20Acequia" className="rounded-lg border border-bone-200 bg-white px-5 py-3 text-sm font-semibold text-ink-700">Consultar una fuente</a></section></div></main>;
}
