create table if not exists terreno.eventos_recorrido (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, event_name text not null check (event_name in ('page_view','onboarding_started','map_opened','account_viewed','feedback_opened')), path text not null check (char_length(path) between 1 and 500), metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists eventos_recorrido_user_created_idx on terreno.eventos_recorrido (user_id, created_at desc);
create index if not exists eventos_recorrido_event_created_idx on terreno.eventos_recorrido (event_name, created_at desc);
alter table terreno.eventos_recorrido enable row level security;
create policy "eventos_recorrido_insert_self" on terreno.eventos_recorrido for insert to authenticated with check (user_id = auth.uid());
revoke all on terreno.eventos_recorrido from anon;
grant insert on terreno.eventos_recorrido to authenticated;
grant select on terreno.eventos_recorrido to service_role;
grant usage, select on sequence terreno.eventos_recorrido_id_seq to authenticated, service_role;
